def kubernetes_service_deployment(
        deployment_target,
        require_shared_policy,
        name,
        component,
        cluster,
        namespace,
        release,
        service_kind = "web",
        ingress_mode = "",
        health_path = "/healthz",
        smoke = None,
        smoke_exception = None,
        publisher = "helm-release",
        publisher_config = "helm/values.yaml",
        provisioner = "",
        provisioner_config = "",
        protection_class = "shared_nonprod",
        lane_policy = None,
        environment_stage = "",
        admission_policy = None,
        prerequisites = [],
        secret_requirements = [],
        runtime_config_requirements = [],
        vault_runtime = {},
        labels = [],
        visibility = ["PUBLIC"]):
    if protection_class != "local_only":
        require_shared_policy(lane_policy, environment_stage, admission_policy)
    effective_ingress_mode = ingress_mode
    if not effective_ingress_mode:
        effective_ingress_mode = "none" if service_kind == "worker" else "public"
    deployment_target(
        name = name,
        provider = "kubernetes",
        component = component,
        component_kind = "service",
        publisher = publisher,
        publisher_config = publisher_config,
        provisioner = provisioner,
        provisioner_config = provisioner_config,
        protection_class = protection_class,
        lane_policy = lane_policy,
        environment_stage = environment_stage,
        admission_policy = admission_policy,
        components = [{
            "id": "default",
            "kind": "service",
            "target": component,
        }],
        provider_target = {
            "cluster": cluster,
            "namespace": namespace,
            "release": release,
            "service_kind": service_kind,
            "ingress_mode": effective_ingress_mode,
            "health_path": health_path,
        },
        smoke = smoke or {},
        smoke_exception = smoke_exception or {},
        prerequisites = prerequisites,
        secret_requirements = secret_requirements,
        runtime_config_requirements = runtime_config_requirements,
        vault_runtime = vault_runtime,
        labels = labels + [
            "kind:deployment",
            "deployment:kubernetes",
            "deployment-component:service",
        ],
        visibility = visibility,
    )
