def require_shared_policy(lane_policy, environment_stage, admission_policy):
    if lane_policy == None:
        fail("protected/shared deployments must set lane_policy")
    if not environment_stage:
        fail("protected/shared deployments must set environment_stage")
    if admission_policy == None:
        fail("protected/shared deployments must set admission_policy")

def nixos_shared_host_static_webapp_deployment(
        deployment_target,
        name,
        component,
        app_name,
        container_port,
        health_path = "",
        target_group = "",
        provider_target = {},
        smoke = None,
        smoke_exception = None,
        publisher = "nixos-shared-host-static-webapp",
        provisioner = "nixos-shared-host-manifest",
        protection_class = "shared_nonprod",
        lane_policy = None,
        deployment_family = "",
        environment_stage = "",
        admission_policy = None,
        bootstrap = None,
        prerequisites = [],
        secret_requirements = [],
        runtime_config_requirements = [],
        external_requirement_profiles = [],
        ingress_hostnames = [],
        resource_sizing = {},
        vault_runtime = {},
        secret_backend = "",
        deployment_context = "",
        infisical_runtime = {},
        infisical_secret_mappings = {},
        release_actions = [],
        target_exceptions = [],
        labels = [],
        visibility = ["PUBLIC"]):
    if protection_class != "local_only":
        require_shared_policy(lane_policy, environment_stage, admission_policy)
    deployment_target(
        name = name,
        provider = "nixos-shared-host",
        component = component,
        component_kind = "static-webapp",
        publisher = publisher,
        provisioner = provisioner,
        protection_class = protection_class,
        lane_policy = lane_policy,
        deployment_family = deployment_family,
        environment_stage = environment_stage,
        admission_policy = admission_policy,
        components = [{
            "id": "default",
            "kind": "static-webapp",
            "target": component,
            "app_name": app_name,
            "container_port": str(container_port),
            "health_path": health_path,
            "target_group": target_group,
        }],
        provider_target = provider_target,
        ingress_hostnames = ingress_hostnames,
        resource_sizing = resource_sizing,
        app_name = app_name,
        container_port = container_port,
        health_path = health_path,
        target_group = target_group,
        smoke = smoke or {},
        smoke_exception = smoke_exception or {},
        bootstrap = bootstrap or {},
        prerequisites = prerequisites,
        secret_requirements = secret_requirements,
        runtime_config_requirements = runtime_config_requirements,
        external_requirement_profiles = external_requirement_profiles,
        vault_runtime = vault_runtime,
        secret_backend = secret_backend,
        deployment_context = deployment_context,
        infisical_runtime = infisical_runtime,
        infisical_secret_mappings = infisical_secret_mappings,
        release_actions = release_actions,
        target_exceptions = target_exceptions,
        labels = labels + ["kind:deployment", "deployment:nixos-shared-host", "deployment-component:static-webapp"],
        visibility = visibility,
    )
def nixos_shared_host_ssr_webapp_deployment(
        deployment_target,
        name,
        component,
        app_name,
        container_port,
        framework,
        health_path = "",
        target_group = "",
        smoke = None,
        smoke_exception = None,
        publisher = "nixos-shared-host-ssr-webapp",
        provisioner = "nixos-shared-host-manifest",
        protection_class = "shared_nonprod",
        lane_policy = None,
        deployment_family = "",
        environment_stage = "",
        admission_policy = None,
        bootstrap = None,
        prerequisites = [],
        secret_requirements = [],
        runtime_config_requirements = [],
        external_requirement_profiles = [],
        vault_runtime = {},
        secret_backend = "",
        deployment_context = "",
        infisical_runtime = {},
        infisical_secret_mappings = {},
        release_actions = [],
        target_exceptions = [],
        labels = [],
        visibility = ["PUBLIC"]):
    if protection_class != "local_only":
        require_shared_policy(lane_policy, environment_stage, admission_policy)
    deployment_target(
        name = name,
        provider = "nixos-shared-host",
        component = component,
        component_kind = "ssr-webapp",
        publisher = publisher,
        provisioner = provisioner,
        protection_class = protection_class,
        lane_policy = lane_policy,
        deployment_family = deployment_family,
        environment_stage = environment_stage,
        admission_policy = admission_policy,
        components = [{
            "id": "default",
            "kind": "ssr-webapp",
            "target": component,
            "app_name": app_name,
            "container_port": str(container_port),
            "health_path": health_path,
            "target_group": target_group,
            "ssr_framework": framework,
            "ssr_runtime_contract": "node-dist-server-v1",
            "ssr_server_entry": "dist/server/index.js",
            "ssr_client_dir": "dist/client",
            "ssr_serving_topology": "single-host-node-with-nginx",
            "ssr_environment_neutral_build": "true",
        }],
        smoke = smoke or {},
        smoke_exception = smoke_exception or {},
        bootstrap = bootstrap or {},
        prerequisites = prerequisites,
        secret_requirements = secret_requirements,
        runtime_config_requirements = runtime_config_requirements,
        external_requirement_profiles = external_requirement_profiles,
        vault_runtime = vault_runtime,
        secret_backend = secret_backend,
        deployment_context = deployment_context,
        infisical_runtime = infisical_runtime,
        infisical_secret_mappings = infisical_secret_mappings,
        release_actions = release_actions,
        target_exceptions = target_exceptions,
        labels = labels + ["kind:deployment", "deployment:nixos-shared-host", "deployment-component:ssr-webapp"],
        visibility = visibility,
    )
def nixos_shared_host_multi_static_webapp_deployment(
        deployment_target,
        name,
        components,
        rollout_policy,
        target_group = "",
        smoke = None,
        smoke_exception = None,
        publisher = "nixos-shared-host-static-webapp",
        provisioner = "nixos-shared-host-manifest",
        protection_class = "shared_nonprod",
        lane_policy = None,
        deployment_family = "",
        environment_stage = "",
        admission_policy = None,
        bootstrap = None,
        prerequisites = [],
        secret_requirements = [],
        runtime_config_requirements = [],
        external_requirement_profiles = [],
        vault_runtime = {},
        secret_backend = "",
        deployment_context = "",
        infisical_runtime = {},
        infisical_secret_mappings = {},
        release_actions = [],
        target_exceptions = [],
        labels = [],
        visibility = ["PUBLIC"]):
    if protection_class != "local_only":
        require_shared_policy(lane_policy, environment_stage, admission_policy)
    rollout_steps = rollout_policy.get("steps", [])
    rollout_fields = {
        "mode": rollout_policy.get("mode", ""),
        "abort": rollout_policy.get("abort", ""),
        "smoke": rollout_policy.get("smoke", ""),
    }
    deployment_target(
        name = name,
        provider = "nixos-shared-host",
        component = components[0]["target"],
        component_kind = "static-webapp",
        publisher = publisher,
        provisioner = provisioner,
        protection_class = protection_class,
        lane_policy = lane_policy,
        deployment_family = deployment_family,
        environment_stage = environment_stage,
        admission_policy = admission_policy,
        components = [
            {
                "id": component["id"],
                "kind": "static-webapp",
                "target": component["target"],
                "app_name": component["app_name"],
                "container_port": str(component["container_port"]),
                "health_path": component.get("health_path", ""),
                "target_group": component.get("target_group", target_group),
            }
            for component in components
        ],
        rollout_policy = rollout_fields,
        rollout_steps = rollout_steps,
        target_group = target_group,
        smoke = smoke or {},
        smoke_exception = smoke_exception or {},
        bootstrap = bootstrap or {},
        prerequisites = prerequisites,
        secret_requirements = secret_requirements,
        runtime_config_requirements = runtime_config_requirements,
        external_requirement_profiles = external_requirement_profiles,
        vault_runtime = vault_runtime,
        secret_backend = secret_backend,
        deployment_context = deployment_context,
        infisical_runtime = infisical_runtime,
        infisical_secret_mappings = infisical_secret_mappings,
        release_actions = release_actions,
        target_exceptions = target_exceptions,
        labels = labels + ["kind:deployment", "deployment:nixos-shared-host", "deployment-component:static-webapp", "deployment:multi-component"],
        visibility = visibility,
    )
