def opentofu_foundation_deployment(
        deployment_target,
        require_shared_policy,
        name,
        component,
        provisioner_config,
        provider_target,
        lane_policy = None,
        environment_stage = "",
        admission_policy = None,
        protection_class = "shared_nonprod",
        prerequisites = [],
        secret_requirements = [],
        runtime_config_requirements = [],
        external_requirement_profiles = [],
        ingress_hostnames = [],
        resource_sizing = {},
        vault_runtime = {},
        secret_backend = "",
        infisical_runtime = {},
        infisical_secret_mappings = {},
        migration_bundle = None,
        labels = [],
        visibility = ["PUBLIC"]):
    if protection_class != "local_only":
        require_shared_policy(lane_policy, environment_stage, admission_policy)
    bundle = migration_bundle or component
    deployment_target(
        name = name,
        provider = "opentofu",
        component = component,
        component_kind = "provision-only",
        publisher = "provision-only",
        publisher_config = "",
        provisioner = "opentofu-stack",
        provisioner_config = provisioner_config,
        protection_class = protection_class,
        lane_policy = lane_policy,
        environment_stage = environment_stage,
        admission_policy = admission_policy,
        components = [{
            "id": "default",
            "kind": "provision-only",
            "target": component,
        }],
        provider_target = provider_target,
        prerequisites = prerequisites,
        secret_requirements = secret_requirements,
        runtime_config_requirements = runtime_config_requirements,
        external_requirement_profiles = external_requirement_profiles,
        ingress_hostnames = ingress_hostnames,
        resource_sizing = resource_sizing,
        vault_runtime = vault_runtime,
        secret_backend = secret_backend,
        infisical_runtime = infisical_runtime,
        infisical_secret_mappings = infisical_secret_mappings,
        migration_bundle = bundle,
        labels = labels + [
            "kind:deployment",
            "deployment:opentofu",
            "deployment-component:provision-only",
        ],
        visibility = visibility,
    )
