def s3_static_webapp_deployment(
        deployment_target,
        require_shared_policy,
        name,
        component,
        account,
        bucket,
        region,
        distribution = "",
        smoke = None,
        smoke_exception = None,
        publisher = "aws-s3-sync",
        publisher_config = "aws-s3-sync.jsonc",
        provisioner = "",
        protection_class = "shared_nonprod",
        lane_policy = None,
        deployment_family = "",
        environment_stage = "",
        admission_policy = None,
        prerequisites = [],
        secret_requirements = [],
        runtime_config_requirements = [],
        external_requirement_profiles = [],
        vault_runtime = {},
        secret_backend = "",
        infisical_runtime = {},
        infisical_secret_mappings = {},
        release_actions = [],
        target_exceptions = [],
        labels = [],
        visibility = ["PUBLIC"]):
    if protection_class != "local_only":
        require_shared_policy(lane_policy, environment_stage, admission_policy)
    deployment_target(
        name = name,
        provider = "s3-static",
        component = component,
        component_kind = "static-webapp",
        publisher = publisher,
        publisher_config = publisher_config,
        provisioner = provisioner,
        protection_class = protection_class,
        lane_policy = lane_policy,
        deployment_family = deployment_family,
        environment_stage = environment_stage,
        admission_policy = admission_policy,
        components = [{
            "id": "default",
            "kind": "static-webapp",
            "target": component,
        }],
        provider_target = {
            "account": account,
            "bucket": bucket,
            "region": region,
            "distribution": distribution,
        },
        smoke = smoke or {},
        smoke_exception = smoke_exception or {},
        prerequisites = prerequisites,
        secret_requirements = secret_requirements,
        runtime_config_requirements = runtime_config_requirements,
        external_requirement_profiles = external_requirement_profiles,
        vault_runtime = vault_runtime,
        secret_backend = secret_backend,
        infisical_runtime = infisical_runtime,
        infisical_secret_mappings = infisical_secret_mappings,
        release_actions = release_actions,
        target_exceptions = target_exceptions,
        labels = labels + [
            "kind:deployment",
            "deployment:s3-static",
            "deployment-component:static-webapp",
        ],
        visibility = visibility,
    )
