def vercel_next_webapp_deployment(
        deployment_target,
        require_shared_policy,
        name,
        component,
        team,
        project,
        environment,
        canonical_url = "",
        smoke = None,
        smoke_exception = None,
        publisher = "vercel-prebuilt",
        publisher_config = "vercel-prebuilt.jsonc",
        provisioner = "",
        provisioner_config = "",
        protection_class = "shared_nonprod",
        lane_policy = None,
        environment_stage = "",
        admission_policy = None,
        prerequisites = [],
        secret_requirements = [],
        runtime_config_requirements = [],
        external_requirement_profiles = [],
        vault_runtime = {},
        provider_target = {},
        release_actions = [],
        target_exceptions = [],
        labels = [],
        visibility = ["PUBLIC"]):
    if protection_class != "local_only":
        require_shared_policy(lane_policy, environment_stage, admission_policy)
    base_provider_target = {
        "team": team,
        "project": project,
        "environment": environment,
        "canonical_url": canonical_url,
    }
    base_provider_target.update(provider_target)
    deployment_target(
        name = name,
        provider = "vercel",
        component = component,
        component_kind = "ssr-webapp",
        publisher = publisher,
        publisher_config = publisher_config,
        provisioner = provisioner,
        provisioner_config = provisioner_config,
        protection_class = protection_class,
        lane_policy = lane_policy,
        environment_stage = environment_stage,
        admission_policy = admission_policy,
        components = [{
            "id": "default",
            "kind": "ssr-webapp",
            "target": component,
        }],
        provider_target = base_provider_target,
        smoke = smoke or {},
        smoke_exception = smoke_exception or {},
        prerequisites = prerequisites,
        secret_requirements = secret_requirements,
        runtime_config_requirements = runtime_config_requirements,
        external_requirement_profiles = external_requirement_profiles,
        vault_runtime = vault_runtime,
        release_actions = release_actions,
        target_exceptions = target_exceptions,
        labels = labels + [
            "kind:deployment",
            "deployment:vercel",
            "deployment-component:ssr-webapp",
        ],
        visibility = visibility,
    )
