import { coverage, proof, recipe, selection } from "./artifact-reproducibility-matrix-helpers";
import {
  configuredRustSystemEvidence,
  rustCase,
  rustCliCase,
  rustWasmCase,
} from "./artifact-reproducibility-rust-case-builders";

export function rustReproducibilityMatrixCases(
  releaseSystems: readonly string[],
): readonly ReproducibilityMatrixCase[] {
  return [
    {
      id: "rust-pr5",
      artifactFamily: "rust",
      systems: releaseSystems,
      systemEvidence: configuredRustSystemEvidence(),
      scaffoldRecipe: recipe("rust", "cli", "repro-rust", "projects/apps/repro-rust"),
      coverage: coverage(["base"]),
      graphSelection: selection(
        ["rust_nix_build"],
        "//projects/apps/repro-rust:repro-rust",
        "executable",
        ["lang:rust", "kind:bin"],
      ),
      languageProofs: [],
    },
    rustCliCase(releaseSystems, "rust-test-pr12", "repro-rust-test", "test", "kind:test"),
    rustCase(releaseSystems, "rust-lib-pr12", "lib", "repro-rust-lib", "library", "kind:lib"),
    rustCase(
      releaseSystems,
      "rust-static-library-pr12",
      "lib",
      "repro-rust-static",
      "static-library",
      "kind:lib",
      ["base"],
      "-static",
    ),
    rustCase(
      releaseSystems,
      "rust-cdylib-pr12",
      "lib",
      "repro-rust-dynamic",
      "dynamic-library",
      "kind:lib",
      ["base"],
      "-dynamic",
    ),
    rustCase(
      releaseSystems,
      "rust-proc-macro-pr12",
      "proc-macro",
      "repro-rust-proc-macro",
      "proc-macro",
      "kind:lib",
    ),
    rustCase(
      releaseSystems,
      "rust-python-extension-pr12",
      "python-extension",
      "repro-rust-python",
      "python-extension",
      "kind:pyext",
      ["base", "addon", "mixed"],
    ),
    {
      id: "rust-pyodide-extension-pr14",
      artifactFamily: "rust",
      systems: releaseSystems,
      systemEvidence: configuredRustSystemEvidence(),
      scaffoldRecipe: recipe(
        "rust",
        "pyodide-extension",
        "repro-rust-pyodide",
        "projects/apps/repro-rust-pyodide",
      ),
      coverage: coverage(["wasm", "addon", "mixed"]),
      graphSelection: selection(
        ["python_nix_wasm_build"],
        "//projects/apps/repro-rust-pyodide:repro-rust-pyodide",
        "python-wasm-consumer",
        ["lang:python", "kind:app", "backend:pyodide"],
      ),
      languageProofs: [
        proof(["rust_nix_build"], "//projects/apps/repro-rust-pyodide:repro-rust-pyodide-ext", [
          "lang:rust",
          "kind:pyext_wasm",
          "backend:pyodide",
        ]),
      ],
    },
    rustCase(
      releaseSystems,
      "rust-node-addon-pr12",
      "node-addon",
      "repro-rust-node",
      "node-addon",
      "kind:addon",
      ["base", "addon", "mixed"],
    ),
    rustCase(
      releaseSystems,
      "rust-c-ffi-pr12",
      "cxx-bridge",
      "repro-rust-c-ffi",
      "c-ffi",
      "kind:lib",
      ["base", "mixed"],
      "-c",
    ),
    rustCase(
      releaseSystems,
      "rust-cxx-bridge-pr12",
      "cxx-bridge",
      "repro-rust-cxx",
      "cxx-bridge",
      "kind:lib",
      ["base", "mixed"],
    ),
    rustWasmCase(releaseSystems, "rust-wasm-pr12", "repro-rust-wasm", "", "wasm-module", [
      "kind:wasm",
      "wasm:module",
    ]),
    rustWasmCase(
      releaseSystems,
      "rust-wasm-static-pr12",
      "repro-rust-wasm-static",
      "-static",
      "wasm-static-library",
      ["kind:wasm", "wasm:static"],
    ),
    rustWasmCase(
      releaseSystems,
      "rust-wasi-static-pr12",
      "repro-rust-wasi-static",
      "-wasi-static",
      "wasi-static-library",
      ["kind:wasi_static", "wasm:wasi"],
      "wasi",
    ),
    rustWasmCase(
      releaseSystems,
      "rust-wasm-browser-pr12",
      "repro-rust-wasm-browser",
      "-browser",
      "browser-package",
      ["kind:wasm", "wasm:browser"],
    ),
    rustWasmCase(
      releaseSystems,
      "rust-wasm-component-pr12",
      "repro-rust-wasm-component",
      "-component",
      "component-module",
      ["kind:wasm", "wasm:component"],
    ),
    rustWasmCase(
      releaseSystems,
      "rust-wasi-pr12",
      "repro-rust-wasi",
      "-wasi",
      "wasi",
      ["kind:wasm", "wasm:wasi"],
      "wasi",
    ),
    {
      id: "rust-cross-root-pr12",
      artifactFamily: "rust",
      systems: releaseSystems,
      systemEvidence: configuredRustSystemEvidence(),
      scaffoldRecipe: recipe("rust", "cross-root", "repro-rust-cross", "projects"),
      coverage: coverage(["base"]),
      graphSelection: selection(
        ["rust_nix_build"],
        "//projects/libs/repro-rust-cross-app:repro-rust-cross-app",
        "cross-root-library",
        ["lang:rust", "kind:lib"],
      ),
      languageProofs: [],
    },
    {
      id: "rust-tauri-darwin-pr12",
      artifactFamily: "rust",
      systems: ["aarch64-darwin"],
      systemEvidence: {
        nativeExecution: [],
        failClosedUntilExternalEvidence: ["aarch64-darwin"],
      },
      scaffoldRecipe: recipe(
        "rust",
        "tauri-app",
        "repro-rust-tauri",
        "projects/apps/repro-rust-tauri",
      ),
      coverage: coverage(["base", "mixed", "desktop"]),
      graphSelection: selection(
        ["rust_nix_build"],
        "//projects/apps/repro-rust-tauri:repro-rust-tauri",
        "desktop-application",
        ["lang:rust", "kind:app", "app:tauri"],
      ),
      languageProofs: [
        proof(["genrule"], "//projects/apps/repro-rust-tauri:frontend_raw", [
          "lang:node",
          "kind:app",
        ]),
        proof(["genrule"], "//projects/apps/repro-rust-tauri:frontend", [
          "lang:node",
          "kind:app",
          "webapp:static",
        ]),
        proof(["rust_nix_build"], "//projects/apps/repro-rust-tauri:frontend_wasm", [
          "lang:rust",
          "kind:wasm",
        ]),
        proof(["cpp_nix_build"], "//projects/apps/repro-rust-tauri:repro-rust-tauri-sidecar", [
          "lang:cpp",
          "kind:bin",
          "sidecar:reviewed",
        ]),
      ],
    },
  ];
}
