import { execFile } from "node:child_process";
import * as fsp from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import {
  initLocalSprinkleRefValues,
  initSprinkleRefConfigs,
} from "../deployments/sprinkleref-templates";
import { BUCK_PROJECT_IGNORE_LINE } from "./buck-project-ignore";
import { createCommandUi } from "./command-ui";
import { direnvStage0, envrc } from "./consumer-direnv";
import { writeIfChanged } from "./fs-helpers";
import { activateWorkspace } from "./workspace-activation";
import { mkdirWithMacosMetadataExclusion } from "./macos-metadata";

const execFileAsync = promisify(execFile);

export type ConsumerSourceMode = "flake" | "submodule";
export type DirenvSetupMode = "auto" | "always" | "never";

export type InitConsumerOptions = {
  workspaceRoot: string;
  viberootsUrl: string;
  workspaceName: string;
  sourceMode?: ConsumerSourceMode;
  sourcePath?: string;
  lock?: boolean;
  allowDirenv?: boolean;
  setupDirenv?: DirenvSetupMode;
  runInstall?: boolean;
};

const generatedMarker = "generated by viberoots/init-consumer";
const gitignoreMarker = "# viberoots local workspace state";
const gitignoreEntries = [
  ".viberoots/",
  "buck-out/",
  ".direnv/",
  ".nix-zsh/",
  ".nix-gcroots/",
  "node_modules",
  "node_modules/",
  "projects/config/local.json",
  ".local/",
];
const bootstrapScaffoldPaths = [
  ".buckconfig",
  ".buckroot",
  ".envrc",
  ".gitignore",
  ".metadata_never_index",
  "flake.nix",
  "flake.lock",
  "README.md",
  "projects/.metadata_never_index",
  "projects/AGENTS.md",
  "projects/README.md",
  "projects/config/README.md",
  "projects/config/shared.json",
];

async function exists(file: string): Promise<boolean> {
  try {
    await fsp.lstat(file);
    return true;
  } catch {
    return false;
  }
}

async function writeGeneratedFile(
  workspaceRoot: string,
  rel: string,
  content: string,
): Promise<void> {
  const file = path.join(workspaceRoot, rel);
  await fsp.mkdir(path.dirname(file), { recursive: true });
  if (await exists(file)) {
    const current = await fsp.readFile(file, "utf8");
    if (current === content) return;
    if (current.includes(generatedMarker)) {
      await writeIfChanged(file, content);
      return;
    }
    const backupDir = path.join(workspaceRoot, ".viberoots", "workspace", "backups");
    await fsp.mkdir(backupDir, { recursive: true });
    const backupName = rel.replaceAll("/", "__");
    const backupFile = path.join(backupDir, `${backupName}.${Date.now()}.${process.pid}.bak`);
    await fsp.copyFile(file, backupFile);
    console.error(
      `repair: ${rel} exists and is not generated by viberoots; backed up to ${backupFile}`,
    );
  }
  await writeIfChanged(file, content);
}

async function writeIfMissing(workspaceRoot: string, rel: string, content: string): Promise<void> {
  const file = path.join(workspaceRoot, rel);
  if (await exists(file)) {
    console.error(`preserve: ${rel} exists`);
    return;
  }
  await fsp.mkdir(path.dirname(file), { recursive: true });
  await fsp.writeFile(file, content, "utf8");
}

async function ensureGitignoreEntries(workspaceRoot: string): Promise<void> {
  const file = path.join(workspaceRoot, ".gitignore");
  let current = "";
  try {
    current = await fsp.readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const existingEntries = new Set(
    current
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean),
  );
  const missing = gitignoreEntries.filter((entry) => !existingEntries.has(entry));
  if (!missing.length) return;
  const prefix = current && !current.endsWith("\n") ? "\n" : "";
  const separator = current.trim() ? "\n" : "";
  const block = `${gitignoreMarker}\n${missing.join("\n")}\n`;
  await fsp.writeFile(file, `${current}${prefix}${separator}${block}`, "utf8");
}

async function writeBuckroot(workspaceRoot: string): Promise<void> {
  const rel = ".buckroot";
  const file = path.join(workspaceRoot, rel);
  if ((await exists(file)) && (await fsp.readFile(file, "utf8")) === ".\n") return;
  if (await exists(file)) {
    const backupDir = path.join(workspaceRoot, ".viberoots", "workspace", "backups");
    await fsp.mkdir(backupDir, { recursive: true });
    const backupFile = path.join(backupDir, `${rel}.${Date.now()}.${process.pid}.bak`);
    await fsp.copyFile(file, backupFile);
    console.error(`repair: ${rel} exists and is not canonical; backed up to ${backupFile}`);
  }
  await fsp.writeFile(file, ".\n", "utf8");
}

function relativeLinkTarget(fromDir: string, target: string): string {
  const rel = path.relative(fromDir, target) || ".";
  return rel.startsWith("..") ? target : `./${rel}`;
}

async function repairCurrentSymlinkForBootstrap(
  workspaceRoot: string,
  sourcePath: string | undefined,
): Promise<void> {
  if (!sourcePath) return;
  const currentPath = path.join(workspaceRoot, ".viberoots", "current");
  const target = relativeLinkTarget(
    path.dirname(currentPath),
    path.resolve(workspaceRoot, sourcePath),
  );
  try {
    const stat = await fsp.lstat(currentPath);
    if (stat.isSymbolicLink()) {
      if ((await fsp.readlink(currentPath)) === target) return;
      await fsp.unlink(currentPath);
      await fsp.symlink(target, currentPath);
      console.error(`repair: .viberoots/current now points to ${target}`);
      return;
    }
    const backupDir = path.join(workspaceRoot, ".viberoots", "workspace", "backups");
    await fsp.mkdir(backupDir, { recursive: true });
    const backupFile = path.join(backupDir, `.viberoots__current.${Date.now()}.${process.pid}.bak`);
    await fsp.rename(currentPath, backupFile);
    console.error(
      `repair: .viberoots/current existed and was not a symlink; moved to ${backupFile}`,
    );
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}

function buckconfig(): string {
  return `# ${generatedMarker}
[buildfile]
name = TARGETS

[repositories]
root = .
viberoots = ./.viberoots/current
prelude = ./.viberoots/current/prelude
toolchains = ./.viberoots/current/toolchains
repo_toolchains = ./.viberoots/current/toolchains
fbsource = ./.viberoots/current/config/fbsource_stub
fbcode = ./.viberoots/current/config/fbcode_stub
config = ./.viberoots/current/config
workspace_providers = ./.viberoots/workspace/providers
workspace_buck = ./.viberoots/workspace/buck

[cells]
root = .
viberoots = ./.viberoots/current
prelude = ./.viberoots/current/prelude
toolchains = ./.viberoots/current/toolchains
repo_toolchains = ./.viberoots/current/toolchains
fbsource = ./.viberoots/current/config/fbsource_stub
fbcode = ./.viberoots/current/config/fbcode_stub
config = ./.viberoots/current/config
workspace_providers = ./.viberoots/workspace/providers
workspace_buck = ./.viberoots/workspace/buck

[build]
prelude = prelude
user_platform = prelude//platforms:default
target_platforms = prelude//platforms:default

[project]
${BUCK_PROJECT_IGNORE_LINE}
`;
}

function flakeNix(opts: InitConsumerOptions): string {
  return `# ${generatedMarker}
{
  description = "viberoots consumer workspace";

  nixConfig.allowed-impure-env-vars = [
    "BUCK_GRAPH_JSON"
    "ROOT_GOMOD2NIX_TOML"
    "BUCK_TEST_SRC"
    "BUCK_TARGET"
    "NIX_GO_DEV_OVERRIDE_JSON"
    "NIX_CPP_DEV_OVERRIDE_JSON"
    "NIX_PY_DEV_OVERRIDE_JSON"
    "NIX_PY_TEST_RESOLVE_JSON"
    "PLANNER_NO_DEV_OVERRIDE_LOG"
    "PLANNER_TRACE"
    "NIX_PNPM_ALLOW_GENERATE"
    "NIX_PNPM_FETCH_TIMEOUT"
    "NIX_NODE_TEST_PATTERNS"
    "COVERAGE"
    "WORKSPACE_ROOT"
    "VIBEROOTS_ROOT"
    "VIBEROOTS_SOURCE_ROOT"
    "VIBEROOTS_FLAKE_INPUT_ROOT"
    "TEST_RSYNC_ROOTS"
    "TEST_PARTIAL_CLONE_GO_ONLY"
    "TEST_EXCLUDE_CPP_REQS"
  ];

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    buck2.url = "github:facebook/buck2/201beb86106fecdc84e30260b0f1abb5bf576988";
    gomod2nix.url = "github:nix-community/gomod2nix";
    gomod2nix.inputs.nixpkgs.follows = "nixpkgs";
    viberoots.url = "${opts.viberootsUrl}";
    viberoots.inputs.nixpkgs.follows = "nixpkgs";
    viberoots.inputs.buck2.follows = "buck2";
    viberoots.inputs.gomod2nix.follows = "gomod2nix";
  };

  outputs = inputs:
    inputs.viberoots.lib.mkWorkspace {
      workspaceSrc =
        let
          root = builtins.getEnv "WORKSPACE_ROOT";
        in
        if root != "" then builtins.toPath root else ../..;
      viberootsInput = inputs.viberoots;
      workspaceName = "${opts.workspaceName}";
    };
}
`;
}

function rootFlakeNix(opts: InitConsumerOptions): string {
  return flakeNix(opts).replace(
    'if root != "" then builtins.toPath root else ../..;',
    'if root != "" then builtins.toPath root else ./.;',
  );
}

function workspaceTargets(): string {
  return `# ${generatedMarker}
filegroup(
    name = "flake.lock",
    srcs = ["flake.lock"],
    visibility = ["PUBLIC"],
)
`;
}

function consumerReadme(mode: ConsumerSourceMode): string {
  const sourceLine =
    mode === "submodule"
      ? "- `viberoots/`: reusable build tooling and development shell support."
      : "- `.viberoots/current`: pinned viberoots tooling source resolved from the workspace flake.";
  const docsLine =
    mode === "submodule"
      ? "See `viberoots/README.md` and `projects/README.md`."
      : "See the pinned viberoots README through `.viberoots/current/README.md` and `projects/README.md`.";
  return `# Workspace

This workspace is split between:

${sourceLine}
- \`projects/\`: application and project source.

${docsLine}
`;
}

function projectsAgentNotes(mode: ConsumerSourceMode): string {
  const docsLine =
    mode === "submodule"
      ? "- \\`../viberoots/README.md\\`"
      : "- \\`../.viberoots/current/README.md\\`";
  return `# Agent Notes

This workspace uses viberoots to provide shared repository tooling, development commands,
workspace conventions, scaffolding, templates, deployment helpers, and verification flow.

Before changing setup, dependency, build, test, scaffold, deployment, or verification behavior,
read:

- \`../README.md\`
${docsLine}
- \`../.viberoots/current/docs/README.md\`
- \`../.viberoots/current/build-tools/docs/README.md\`
- \`../.viberoots/current/docs/handbook/getting-started-on-a-pr.md\`

Use the workspace commands from the repo root:

\`\`\`bash
i && b && v
\`\`\`

Do not install repository tools manually. Add or update tools only through the patterns and
best practices provided and used by viberoots.

Keep application and library code under \`projects/\`. Do not copy viberoots-owned tooling,
documentation, templates, patches, toolchains, or dependency metadata into the consumer root.
`;
}

function projectConfigReadme(): string {
  return `# Project Config

This directory contains the project configuration surfaces used by viberoots-provided setup,
deployment, secret, and runtime-value workflows.

Read these viberoots docs before changing config shape or resolution behavior:

- \`../../.viberoots/current/docs/sprinkleref.md\`
- \`../../.viberoots/current/docs/local-sprinkleref.md\`
- \`../../.viberoots/current/docs/control-plane-guide.md\`
- \`../../.viberoots/current/docs/secrets-usage.md\`
- \`../../.viberoots/current/docs/deployments-usage.md\`

Use \`shared.json\` for checked-in, non-secret values and topology that should be the same for the
repo. Add new shared values under \`values\`, then refer to them with \`config://...\`.

Use \`local.json\` for gitignored, per-operator values and clone-local overrides. Create or refresh
local placeholders with:

\`\`\`bash
sprinkleref --init-local
\`\`\`

Use \`secret://...\` refs for true secrets. Store secret values through SprinkleRef instead of
putting plaintext secrets in \`shared.json\` or \`local.json\`:

\`\`\`bash
sprinkleref --update secret://path/to/secret --create-missing
\`\`\`

Use \`runtime://...\` refs for values supplied by the selected runtime host contract.
`;
}

async function commandExists(command: string): Promise<boolean> {
  try {
    await execFileAsync(command, ["--version"]);
    return true;
  } catch {
    return false;
  }
}

async function nixDirenvReady(): Promise<boolean> {
  if (!(await commandExists("direnv"))) return false;
  for (const candidate of [
    path.join(process.env.HOME || "", ".nix-profile", "share", "nix-direnv", "direnvrc"),
    "/nix/var/nix/profiles/default/share/nix-direnv/direnvrc",
  ]) {
    if (candidate && (await exists(candidate))) return true;
  }
  return false;
}

async function runMacosDirenvBootstrap(sourcePath: string): Promise<void> {
  if (process.platform !== "darwin") {
    console.error("direnv/nix-direnv are not ready; install them before running direnv allow.");
    return;
  }
  const helper = path.join(sourcePath, "build-tools", "tools", "bootstrap", "macos-direnv.sh");
  await execFileAsync(helper, [], { maxBuffer: 1024 * 1024 * 16 });
}

async function setupDirenvIfNeeded(opts: {
  mode: DirenvSetupMode;
  sourcePath: string;
}): Promise<void> {
  if (opts.mode === "never") return;
  if (opts.mode === "auto" && (await nixDirenvReady())) return;
  await runMacosDirenvBootstrap(opts.sourcePath);
}

async function runOptionalDirenvAllow(workspaceRoot: string): Promise<void> {
  const ui = createCommandUi();
  try {
    await execFileAsync("direnv", ["allow", workspaceRoot], { cwd: workspaceRoot });
    ui.ok("direnv allowed", workspaceRoot);
  } catch {
    console.error("direnv is not installed or not on PATH, or direnv allow failed.");
    console.error(`next: cd ${workspaceRoot}`);
    console.error("next: direnv allow && direnv reload");
  }
}

async function runInstall(workspaceRoot: string): Promise<void> {
  await execFileAsync("direnv", ["exec", workspaceRoot, "i"], {
    cwd: workspaceRoot,
    maxBuffer: 1024 * 1024 * 32,
  });
}

async function runNixFlakeLock(workspaceRoot: string): Promise<void> {
  await execFileAsync(
    "nix",
    [
      "flake",
      "lock",
      "--accept-flake-config",
      `path:${path.join(workspaceRoot, ".viberoots", "workspace")}`,
    ],
    { cwd: workspaceRoot, maxBuffer: 1024 * 1024 * 16 },
  );
  const hiddenLock = path.join(workspaceRoot, ".viberoots", "workspace", "flake.lock");
  if (await exists(hiddenLock)) {
    await fsp.copyFile(hiddenLock, path.join(workspaceRoot, "flake.lock"));
  }
}

async function markBootstrapScaffoldVisibleToGit(workspaceRoot: string): Promise<void> {
  try {
    await execFileAsync("git", ["rev-parse", "--is-inside-work-tree"], {
      cwd: workspaceRoot,
    });
    const existing: string[] = [];
    for (const rel of bootstrapScaffoldPaths) {
      if (await exists(path.join(workspaceRoot, rel))) existing.push(rel);
    }
    if (existing.length > 0) {
      await execFileAsync("git", ["add", "--intent-to-add", "--", ...existing], {
        cwd: workspaceRoot,
      });
    }
  } catch {}
}

export async function initConsumer(opts: InitConsumerOptions): Promise<void> {
  const ui = createCommandUi();
  const sourceMode: ConsumerSourceMode =
    opts.sourceMode || (opts.sourcePath ? "submodule" : "flake");
  await mkdirWithMacosMetadataExclusion(opts.workspaceRoot);
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, ".viberoots"));
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, ".viberoots", "workspace"));
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, ".viberoots", "buck"));
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, "projects"));

  await writeBuckroot(opts.workspaceRoot);
  await writeGeneratedFile(opts.workspaceRoot, ".buckconfig", buckconfig());
  await writeGeneratedFile(opts.workspaceRoot, ".envrc", envrc());
  await writeGeneratedFile(
    opts.workspaceRoot,
    ".viberoots/bootstrap/direnv-stage0.sh",
    direnvStage0(),
  );
  await writeGeneratedFile(opts.workspaceRoot, "flake.nix", rootFlakeNix(opts));
  await writeGeneratedFile(opts.workspaceRoot, ".viberoots/workspace/flake.nix", flakeNix(opts));
  await writeGeneratedFile(opts.workspaceRoot, ".viberoots/workspace/TARGETS", workspaceTargets());
  await writeIfMissing(opts.workspaceRoot, "README.md", consumerReadme(sourceMode));
  await writeIfMissing(
    opts.workspaceRoot,
    "projects/README.md",
    `# Projects

Project and application source belongs here.
`,
  );
  await writeIfMissing(opts.workspaceRoot, "projects/AGENTS.md", projectsAgentNotes(sourceMode));
  await writeIfMissing(opts.workspaceRoot, "projects/config/README.md", projectConfigReadme());
  await ensureGitignoreEntries(opts.workspaceRoot);
  await initSprinkleRefConfigs({ dir: path.join(opts.workspaceRoot, "projects", "config") });
  await initLocalSprinkleRefValues(opts.workspaceRoot);

  if (opts.lock !== false) await runNixFlakeLock(opts.workspaceRoot);
  await markBootstrapScaffoldVisibleToGit(opts.workspaceRoot);
  await repairCurrentSymlinkForBootstrap(opts.workspaceRoot, opts.sourcePath);
  const activation = await activateWorkspace({
    start: opts.workspaceRoot,
    env: { ...process.env, WORKSPACE_ROOT: opts.workspaceRoot },
    sourcePath: opts.sourcePath,
  });
  if (opts.allowDirenv !== false) {
    await setupDirenvIfNeeded({
      mode: opts.setupDirenv || "auto",
      sourcePath: activation.sourcePath,
    });
  }
  if (opts.allowDirenv !== false) await runOptionalDirenvAllow(opts.workspaceRoot);
  if (opts.runInstall) await runInstall(opts.workspaceRoot);
  ui.ok("workspace initialized", opts.workspaceRoot);
}
