const generatedMarker = "generated by viberoots/init-consumer";

export function envrc(): string {
  return `# ${generatedMarker}
__vbr_stage0=".viberoots/bootstrap/direnv-stage0.sh"
if [[ ! -f "\${__vbr_stage0}" ]]; then
  echo "error: viberoots direnv stage-0 helper is missing." 1>&2
  echo "run: viberoots bootstrap-check --repair-if-needed" 1>&2
  echo "or rerun the viberoots bootstrap command from README.md." 1>&2
  unset __vbr_stage0
  return 1
fi

source "\${__vbr_stage0}"
unset __vbr_stage0
`;
}

export function direnvStage0(): string {
  return `# ${generatedMarker}
if [[ "\${NIX_CONFIG:-}" != *"builders ="* ]]; then
  export NIX_CONFIG=$'builders = \\nbuild-hook = \\nmax-jobs = auto\\n'"\${NIX_CONFIG:-}"
fi
if [[ "\${NIX_CONFIG:-}" != *"warn-dirty = false"* ]]; then
  export NIX_CONFIG=$'warn-dirty = false\\n'"\${NIX_CONFIG:-}"
fi
export NODE_OPTIONS="--disable-warning=ExperimentalWarning\${NODE_OPTIONS:+ $NODE_OPTIONS}"
if [[ -n "\${IN_NIX_SHELL:-}" ]]; then
  return
fi

__vbr_stage0_strip_nix_cache_overrides() {
  local text="\${NIX_CONFIG:-}"
  [[ -n "\${text}" ]] || return 0
  printf "%s\\n" "\${text}" | awk '
    BEGIN {
      skip["substituters"] = 1
      skip["extra-substituters"] = 1
      skip["connect-timeout"] = 1
      skip["stalled-download-timeout"] = 1
      skip["fallback"] = 1
    }
    {
      line = $0
      key = line
      sub(/[[:space:]]*=.*/, "", key)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (skip[key] != 1) print line
    }
  '
}

__vbr_stage0_apply_nix_cache_health() {
  [[ "\${VBR_NIX_CACHE_HEALTH_APPLIED:-}" != "1" ]] || return 0
  export VBR_NIX_CACHE_HEALTH_APPLIED=1
  [[ "\${VBR_NIX_CACHE_POLICY:-auto}" != "off" ]] || return 0
  command -v nix >/dev/null 2>&1 || return 0

  local config
  config="$(nix config show 2>/dev/null || true)"
  [[ -n "\${config}" ]] || return 0

  local required_substituters optional_substituters
  required_substituters="$(printf "%s\\n" "\${config}" | awk '{
    eq = index($0, "="); if (eq <= 0) next
    key = substr($0, 1, eq - 1); value = substr($0, eq + 1)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    if (key == "substituters") { gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); print value }
  }')"
  optional_substituters="$(printf "%s\\n" "\${config}" | awk '{
    eq = index($0, "="); if (eq <= 0) next
    key = substr($0, 1, eq - 1); value = substr($0, eq + 1)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    if (key == "extra-substituters") { gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); print value }
  }')"
  [[ -n "\${required_substituters}\${optional_substituters}" ]] || return 0

  local available=()
  local removed=()
  local seen=" "
  local substituter
  for substituter in \${required_substituters} \${optional_substituters}; do
    [[ "\${seen}" != *" \${substituter} "* ]] || continue
    seen="\${seen}\${substituter} "
    case "\${substituter}" in
      http://*|https://*)
        local cache_info_url="\${substituter%/}/nix-cache-info"
        local probe_status=0
        if nix store info --store "\${substituter}" --option connect-timeout 3 >/dev/null 2>&1; then
          probe_status=0
        elif command -v curl >/dev/null 2>&1 && curl -fsS --connect-timeout 3 --max-time 5 "\${cache_info_url}" >/dev/null 2>&1; then
          probe_status=0
        else
          probe_status=1
        fi
        if [[ "\${probe_status}" -eq 0 ]]; then
          available+=("\${substituter}")
        else
          removed+=("\${substituter}")
        fi
        ;;
      *) available+=("\${substituter}") ;;
    esac
  done

  [[ "\${#removed[@]}" -gt 0 ]] || return 0
  if [[ "\${VBR_NIX_CACHE_POLICY:-auto}" == "strict" ]]; then
    echo "error: configured Nix substituter(s) unavailable: \${removed[*]}" 1>&2
    return 1
  fi

  local optional_kept=()
  local required_kept=()
  for substituter in \${optional_substituters}; do
    [[ " \${available[*]} " == *" \${substituter} "* ]] && optional_kept+=("\${substituter}")
  done
  for substituter in \${required_substituters}; do
    [[ " \${available[*]} " == *" \${substituter} "* ]] && required_kept+=("\${substituter}")
  done

  local retained required_joined optional_kept_joined
  retained="$(__vbr_stage0_strip_nix_cache_overrides)"
  required_joined="\${required_kept[*]-}"
  optional_kept_joined="\${optional_kept[*]-}"
  export NIX_CONFIG="\${retained}"$'\\n'"substituters = \${required_joined}"$'\\n'"extra-substituters = \${optional_kept_joined}"$'\\n''connect-timeout = 3'$'\\n''stalled-download-timeout = 10'$'\\n''fallback = true'
  echo "[env] nix cache health: disabled unreachable substituter(s): \${removed[*]}" 1>&2
  echo "[env] nix cache health: using optional substituter(s): \${optional_kept_joined:-<none>}" 1>&2
}

__vbr_stage0_filtered_viberoots_input() {
  local src="\${1:-}"
  [[ -n "\${src}" && -f "\${src}/flake.nix" ]] || return 1
  local src_real
  src_real="$(cd "\${src}" && pwd -P 2>/dev/null || true)"
  [[ -n "\${src_real}" ]] || return 1
  local local_real=""
  [[ -d "\${PWD}/viberoots" ]] && local_real="$(cd "\${PWD}/viberoots" && pwd -P 2>/dev/null || true)"
  [[ -n "\${local_real}" && "\${src_real}" == "\${local_real}" ]] || return 1
  command -v rsync >/dev/null 2>&1 || return 1

  local dst="\${PWD}/.viberoots/workspace/viberoots-flake-input"
  mkdir -p "\${dst}" || return 1
  : > "\${PWD}/.viberoots/workspace/.metadata_never_index" 2>/dev/null || true
  : > "\${dst}/.metadata_never_index" 2>/dev/null || true
  rsync -a --delete \\
    --exclude /.git --exclude /node_modules --exclude /buck-out --exclude /.viberoots \\
    --exclude /.direnv --exclude /.pnpm-store --exclude /.pnpm-home --exclude /coverage \\
    --exclude /.clinic --exclude /.turbo --exclude /.cache --exclude /dist --exclude /build \\
    --exclude /.vite --exclude /.next --exclude /.wasm-producer \\
    --exclude '.node_modules.lockfile-guard.*' --exclude '.*.tmp' \\
    --exclude '.*.ts.??????' --exclude '.*.tsx.??????' \\
    --exclude '.*.js.??????' --exclude '.*.mjs.??????' \\
    --exclude result --exclude 'result-*' \\
    "\${src_real}/" "\${dst}/" >/dev/null 2>&1 || return 1
  [[ -f "\${dst}/flake.nix" ]] || return 1; : > "\${dst}/.source-fingerprint" 2>/dev/null || true
  printf '%s\\n' "\${dst}"
}

__vbr_flake_args=()
__vbr_flake_input_root="\${VIBEROOTS_FLAKE_INPUT_ROOT:-}"
if [[ -n "\${__vbr_flake_input_root}" && -d "\${PWD}/viberoots" ]]; then
  __vbr_input_real="$(cd "\${__vbr_flake_input_root}" && pwd -P 2>/dev/null || true)"
  __vbr_filtered_real="$(cd "\${PWD}/.viberoots/workspace/viberoots-flake-input" 2>/dev/null && pwd -P || true)"
  [[ -n "\${__vbr_filtered_real}" && "\${__vbr_input_real}" == "\${__vbr_filtered_real}" ]] && __vbr_flake_input_root="\${PWD}/viberoots"
fi
unset __vbr_input_real __vbr_filtered_real
if [[ -z "\${__vbr_flake_input_root}" || ! -f "\${__vbr_flake_input_root}/flake.nix" ]]; then
  __vbr_flake_input_root="\${VIBEROOTS_SOURCE_ROOT:-}"
fi
if [[ -z "\${__vbr_flake_input_root}" || ! -f "\${__vbr_flake_input_root}/flake.nix" ]]; then
  __vbr_current_real=""; __vbr_local_real=""; __vbr_filtered_real=""
  [[ -e "\${PWD}/.viberoots/current" ]] && __vbr_current_real="$(cd "\${PWD}/.viberoots/current" && pwd -P 2>/dev/null || true)"
  [[ -d "\${PWD}/viberoots" ]] && __vbr_local_real="$(cd "\${PWD}/viberoots" && pwd -P 2>/dev/null || true)"
  [[ -d "\${PWD}/.viberoots/workspace/viberoots-flake-input" ]] && __vbr_filtered_real="$(cd "\${PWD}/.viberoots/workspace/viberoots-flake-input" && pwd -P 2>/dev/null || true)"
  if [[ -n "\${__vbr_local_real}" && ( "\${__vbr_current_real}" == "\${__vbr_local_real}" || "\${__vbr_current_real}" == "\${__vbr_filtered_real}" ) ]]; then
    __vbr_flake_input_root="\${PWD}/viberoots"
  fi
  unset __vbr_current_real __vbr_local_real __vbr_filtered_real
fi
if [[ -f "\${__vbr_flake_input_root}/flake.nix" ]]; then
  __vbr_source_root="\${__vbr_flake_input_root}"
  __vbr_filtered_flake_input_root="$(__vbr_stage0_filtered_viberoots_input "\${__vbr_flake_input_root}" || true)"
  if [[ -n "\${__vbr_filtered_flake_input_root}" && -f "\${__vbr_filtered_flake_input_root}/flake.nix" ]]; then
    __vbr_flake_input_root="\${__vbr_filtered_flake_input_root}"
  fi
  unset __vbr_filtered_flake_input_root
  export VIBEROOTS_SOURCE_ROOT="\${__vbr_source_root}"
  export VIBEROOTS_FLAKE_INPUT_ROOT="\${__vbr_flake_input_root}"
  __vbr_flake_args=(--override-input viberoots "path:\${__vbr_flake_input_root}")
  [[ "\${__vbr_source_root}" == "\${PWD}/viberoots" && ( -L "\${PWD}/.viberoots/current" || ! -e "\${PWD}/.viberoots/current" ) ]] && ln -sfn ../viberoots "\${PWD}/.viberoots/current"
else
  unset VIBEROOTS_SOURCE_ROOT
  unset VIBEROOTS_FLAKE_INPUT_ROOT
fi

__nix_direnv_direnvrc=""
for __candidate in \\
  "\${HOME}/.nix-profile/share/nix-direnv/direnvrc" \\
  "/nix/var/nix/profiles/default/share/nix-direnv/direnvrc"
do
  if [[ -f "\${__candidate}" ]]; then
    __nix_direnv_direnvrc="\${__candidate}"
    break
  fi
done

if [[ -z "\${__nix_direnv_direnvrc}" ]]; then
  echo "error: nix-direnv is required for this repository shell cache path." 1>&2
  echo "install: nix profile install nixpkgs#nix-direnv" 1>&2
  echo "then run: direnv reload" 1>&2
  return 1
fi

source "\${__nix_direnv_direnvrc}"
unset __nix_direnv_direnvrc
unset __candidate

if [[ "\${NIX_CONFIG:-}" != *"experimental-features ="* ]]; then
  export NIX_CONFIG=$'experimental-features = nix-command flakes\\n'"\${NIX_CONFIG:-}"
fi
export WORKSPACE_ROOT="\${PWD}"

__vbr_stage0_apply_nix_cache_health || return 1

if [[ ! -f .viberoots/workspace/flake.nix ]]; then
  echo "error: viberoots workspace flake is missing." 1>&2
  echo "run: viberoots bootstrap-check --repair-if-needed" 1>&2
  echo "or rerun the viberoots bootstrap command from README.md." 1>&2
  return 1
fi

watch_file .viberoots/workspace/flake.nix
watch_file .viberoots/workspace/flake.lock
[[ -f viberoots/flake.nix ]] && watch_file viberoots/flake.nix

use flake "path:\${PWD}/.viberoots/workspace#default" --accept-flake-config "\${__vbr_flake_args[@]}"
if [[ -n "\${__vbr_source_root:-}" && -d "\${PWD}/viberoots" ]]; then
  __vbr_source_real="$(cd "\${__vbr_source_root}" && pwd -P 2>/dev/null || true)"
  __vbr_local_real="$(cd "\${PWD}/viberoots" && pwd -P 2>/dev/null || true)"
  if [[ -n "\${__vbr_source_real}" && "\${__vbr_source_real}" == "\${__vbr_local_real}" ]]; then
    [[ -L "\${PWD}/.viberoots/current" || ! -e "\${PWD}/.viberoots/current" ]] && ln -sfn ../viberoots "\${PWD}/.viberoots/current"
    export VIBEROOTS_ROOT="\${__vbr_source_root}"
    export VIBEROOTS_SOURCE_ROOT="\${__vbr_source_root}"
  fi
  unset __vbr_source_real __vbr_local_real
fi
unset __vbr_flake_input_root __vbr_source_root __vbr_flake_args
unset -f __vbr_stage0_strip_nix_cache_overrides __vbr_stage0_apply_nix_cache_health __vbr_stage0_filtered_viberoots_input
`;
}
