import fs from "node:fs";
import path from "node:path";
import { GENERATED_REPO_STATE_PATHS, normalizeGeneratedRelPath } from "./generated-repo-state";

const generatedMarker = "generated by viberoots/init-consumer";

function generatedRepoStateRsyncExcludes(): string {
  return [...new Set(GENERATED_REPO_STATE_PATHS.map(normalizeGeneratedRelPath))]
    .filter(Boolean)
    .map((rel) => `    --exclude /${rel} \\\n`)
    .join("");
}

function realpathOrOriginal(value: string): string {
  try {
    return fs.realpathSync.native(value);
  } catch {
    return path.resolve(value);
  }
}

export function isTransientCodexArg0Path(dir: string, homeDir = process.env.HOME || ""): boolean {
  if (!dir || !homeDir) return false;
  const home = realpathOrOriginal(homeDir);
  const resolvedDir = realpathOrOriginal(dir);
  const arg0Root = path.join(home, ".codex", "tmp", "arg0");
  return resolvedDir === arg0Root || resolvedDir.startsWith(`${arg0Root}${path.sep}`);
}

export function filterCapturedHostPath(hostPath: string, homeDir = process.env.HOME || ""): string {
  return hostPath
    .split(path.delimiter)
    .filter((dir) => dir && !isTransientCodexArg0Path(dir, homeDir))
    .join(path.delimiter);
}

export function envrc(): string {
  return `# ${generatedMarker}
__vbr_stage0=".viberoots/bootstrap/direnv-stage0.sh"
if [[ ! -f "\${__vbr_stage0}" ]]; then
  echo "error: viberoots direnv stage-0 helper is missing." 1>&2
  echo "run: viberoots bootstrap-check --repair-if-needed" 1>&2
  echo "or rerun the viberoots bootstrap command from README.md." 1>&2
  unset __vbr_stage0
  return 1
fi

source "\${__vbr_stage0}"
unset __vbr_stage0
`;
}

export function direnvStage0(): string {
  return `# ${generatedMarker}
if [[ "\${NIX_CONFIG:-}" != *"builders ="* ]]; then
  export NIX_CONFIG=$'builders = \\nbuild-hook = \\nmax-jobs = auto\\n'"\${NIX_CONFIG:-}"
fi
if [[ "\${NIX_CONFIG:-}" != *"warn-dirty = false"* ]]; then
  export NIX_CONFIG=$'warn-dirty = false\\n'"\${NIX_CONFIG:-}"
fi
export NODE_OPTIONS="--disable-warning=ExperimentalWarning\${NODE_OPTIONS:+ $NODE_OPTIONS}"
if [[ -z "\${IN_NIX_SHELL:-}" ]]; then
  __vbr_stage0_filter_host_path() {
    local path_list="\${1:-}"
    local old_ifs="\${IFS}"
    local dir dir_real home_real result
    result=""
    home_real=""
    [[ -n "\${HOME:-}" ]] && home_real="$(cd "\${HOME}" 2>/dev/null && pwd -P || printf '%s' "\${HOME}")"
    IFS=':'
    for dir in \${path_list}; do
      [[ -n "\${dir}" ]] || continue
      dir_real="$(cd "\${dir}" 2>/dev/null && pwd -P || printf '%s' "\${dir}")"
      if [[ -n "\${home_real}" ]]; then
        case "\${dir_real}" in
          "\${home_real}/.codex/tmp/arg0"|"\${home_real}/.codex/tmp/arg0"/*) continue ;;
        esac
      fi
      result="\${result:+\${result}:}\${dir}"
    done
    IFS="\${old_ifs}"
    printf '%s\\n' "\${result}"
  }
  __vbr_host_path="$(__vbr_stage0_filter_host_path "\${VBR_HOST_PATH:-\${PATH:-}}")"
  __vbr_should_write_host_path=0
  if [[ -n "\${VBR_HOST_PATH:-}" ]]; then
    __vbr_should_write_host_path=1
  else
    __vbr_old_ifs="\${IFS}"
    IFS=':'
    for __vbr_host_path_dir in \${__vbr_host_path}; do
      [[ -n "\${__vbr_host_path_dir}" ]] || continue
      __vbr_host_path_dir_real="$(cd "\${__vbr_host_path_dir}" 2>/dev/null && pwd -P || printf '%s' "\${__vbr_host_path_dir}")"
      case "\${__vbr_host_path_dir_real}" in
        "\${PWD}/.viberoots/current/build-tools/tools/bin"|"\${PWD}/viberoots/build-tools/tools/bin") continue ;;
      esac
      if [[ -x "\${__vbr_host_path_dir}/codex" || -x "\${__vbr_host_path_dir}/claude" ]]; then
        __vbr_should_write_host_path=1
        break
      fi
    done
    IFS="\${__vbr_old_ifs}"
  fi
  unset __vbr_old_ifs __vbr_host_path_dir __vbr_host_path_dir_real
  unset -f __vbr_stage0_filter_host_path
fi
if [[ -n "\${IN_NIX_SHELL:-}" ]]; then
  return
fi

__vbr_stage0_strip_nix_cache_overrides() {
  local text="\${NIX_CONFIG:-}"
  [[ -n "\${text}" ]] || return 0
  printf "%s\\n" "\${text}" | awk '
    BEGIN {
      skip["substituters"] = 1
      skip["extra-substituters"] = 1
      skip["connect-timeout"] = 1
      skip["stalled-download-timeout"] = 1
      skip["fallback"] = 1
    }
    {
      line = $0
      key = line
      sub(/[[:space:]]*=.*/, "", key)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (skip[key] != 1) print line
    }
  '
}

__vbr_stage0_reviewed_config_with_netrc() {
  local reviewed_netrc="\${1:-}"
  [[ -n "\${reviewed_netrc}" && -f "\${reviewed_netrc}" && -r "\${reviewed_netrc}" ]] || reviewed_netrc=""
  printf "%s\\n" "\${NIX_CONFIG:-}" | awk -v netrc="\${reviewed_netrc}" '
    {
      line = $0
      key = line
      sub(/[[:space:]]*=.*/, "", key)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key != "netrc-file" && line != "") print line
    }
    END { if (netrc != "") print "netrc-file = " netrc }
  '
}

__vbr_stage0_resolve_nix_cache_roles() {
  local source_root="\${1:-}"
  local nix_bin=""
  local node_bin=""
  nix_bin="$(command -v nix 2>/dev/null || true)"
  node_bin="$(command -v node 2>/dev/null || true)"
  if [[ -z "\${node_bin}" ]]; then
    local toolchain_paths="\${PWD}/.viberoots/workspace/toolchains/toolchain_paths.bzl"
    local artifact_tools_root=""
    if [[ -f "\${toolchain_paths}" ]]; then
      artifact_tools_root="$(awk -F '"' '/^NIX_ARTIFACT_TOOLS_ROOT = "/ { print $2; exit }' "\${toolchain_paths}")"
    fi
    if [[ "\${artifact_tools_root}" == /nix/store/* && -x "\${artifact_tools_root}/bin/node" ]]; then
      node_bin="\${artifact_tools_root}/bin/node"
    fi
  fi
  local helper=""
  local candidate
  for candidate in \
    "\${source_root}" \
    "\${VIBEROOTS_SOURCE_ROOT:-}" \
    "\${VIBEROOTS_ROOT:-}" \
    "\${PWD}/.viberoots/workspace/viberoots-flake-input" \
    "\${PWD}/viberoots"
  do
    if [[ -n "\${candidate}" && -f "\${candidate}/build-tools/tools/dev/nix-cache-role-provenance.ts" ]]; then
      helper="\${candidate}/build-tools/tools/dev/nix-cache-role-provenance.ts"
      break
    fi
  done
  [[ -n "\${nix_bin}" && -x "\${nix_bin}" && -n "\${node_bin}" && -f "\${helper}" ]] || return 1
  local output key value
  output="$(NODE_DISABLE_COMPILE_CACHE=1 "\${node_bin}" --experimental-strip-types "\${helper}" "\${nix_bin}" 2>/dev/null)" || return 1
  local resolved_required=""
  local resolved_optional=""
  while IFS=$'\\t' read -r key value; do
    case "\${key}" in
      required) resolved_required="\${value:-}" ;;
      optional) resolved_optional="\${value:-}" ;;
      *) return 1 ;;
    esac
  done <<<"\${output}"
  printf '%s\\n%s\\n' "\${resolved_required}" "\${resolved_optional}"
}

__vbr_stage0_nix_cache_role_sets_match() {
  local effective_required="\${1:-}" effective_optional="\${2:-}"
  local candidate_required="\${3:-}" candidate_optional="\${4:-}"
  local entry
  for entry in \${effective_required} \${effective_optional}; do
    [[ " \${candidate_required} \${candidate_optional} " == *" \${entry} "* ]] || return 1
  done
  for entry in \${candidate_required} \${candidate_optional}; do
    [[ " \${effective_required} \${effective_optional} " == *" \${entry} "* ]] || return 1
  done
  return 0
}

__vbr_stage0_apply_nix_cache_health() {
  __vbr_stage0_cache_nix_args=()
  local current_policy="\${VBR_NIX_CACHE_POLICY:-auto}"
  if [[ "\${current_policy}" == "off" ]]; then
    if [[ "\${VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG+x}" == "x" ]]; then
      export NIX_CONFIG="\${VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG}"
    fi
    unset VBR_NIX_CACHE_HEALTH_APPLIED VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY
    unset VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG
    return 0
  fi
  if [[ "\${VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG+x}" == "x" ]]; then
    export NIX_CONFIG="\${VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG}"
  fi
  unset VBR_NIX_CACHE_HEALTH_APPLIED VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY
  unset VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG
  command -v nix >/dev/null 2>&1 || return 0

  local config
  if ! config="$(nix config show 2>/dev/null)"; then
    echo "error: nix config show failed during cache health evaluation" 1>&2
    unset VBR_NIX_CACHE_HEALTH_APPLIED VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY
    return 1
  fi
  export VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG="\${config}"

  local required_substituters optional_substituters netrc_file
  required_substituters="$(printf "%s\\n" "\${config}" | awk '{
    eq = index($0, "="); if (eq <= 0) next
    key = substr($0, 1, eq - 1); value = substr($0, eq + 1)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    if (key == "substituters") { gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); print value }
  }')"
  optional_substituters="$(printf "%s\\n" "\${config}" | awk '{
    eq = index($0, "="); if (eq <= 0) next
    key = substr($0, 1, eq - 1); value = substr($0, eq + 1)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    if (key == "extra-substituters") { gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); print value }
  }')"
  local resolved_roles
  if [[ -n "\${required_substituters}" && -z "\${optional_substituters}" ]]; then
    if ! resolved_roles="$(__vbr_stage0_resolve_nix_cache_roles "\${__vbr_flake_input_root:-\${VIBEROOTS_SOURCE_ROOT:-\${VIBEROOTS_ROOT:-}}}")"; then
      echo "error: flattened Nix substituters require reviewed source-role provenance" 1>&2
      return 1
    fi
    local resolved_required="\${resolved_roles%%$'\\n'*}"
    local resolved_optional="\${resolved_roles#*$'\\n'}"
    if ! __vbr_stage0_nix_cache_role_sets_match "\${required_substituters}" "\${optional_substituters}" "\${resolved_required}" "\${resolved_optional}"; then
      echo "error: reviewed Nix cache roles do not match effective substituters" 1>&2
      return 1
    fi
    required_substituters="\${resolved_required}"
    optional_substituters="\${resolved_optional}"
  fi
  netrc_file="$(printf "%s\\n" "\${config}" | awk '{
    eq = index($0, "="); if (eq <= 0) next
    key = substr($0, 1, eq - 1); value = substr($0, eq + 1)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    if (key == "netrc-file") { gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); print value }
  }')"
  local reviewed_config
  reviewed_config="$(__vbr_stage0_reviewed_config_with_netrc "\${netrc_file}")"
  __vbr_stage0_cache_nix_args=(--option substituters "\${required_substituters}" --option extra-substituters "\${optional_substituters}" --option connect-timeout 3 --option stalled-download-timeout 10 --option fallback true)
  if [[ -z "\${required_substituters}\${optional_substituters}" ]]; then
    export NIX_CONFIG="\${reviewed_config}"
    export VBR_NIX_CACHE_HEALTH_APPLIED=1
    export VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG="\${NIX_CONFIG}"
    export VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS="\${required_substituters}"
    export VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS="\${optional_substituters}"
    export VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY="\${current_policy}"
    return 0
  fi

  local available=()
  local removed=()
  local removed_identities=()
  local seen=" "
  local substituter
  for substituter in \${required_substituters} \${optional_substituters}; do
    [[ "\${seen}" != *" \${substituter} "* ]] || continue
    seen="\${seen}\${substituter} "
    case "\${substituter}" in
      http://*|https://*)
        local cache_identity="\${substituter%%\\?*}"
        cache_identity="\${cache_identity%%\\#*}"
        local cache_scheme="\${cache_identity%%://*}://"
        local cache_location="\${cache_identity#*://}"
        [[ "\${cache_location%%/*}" != *@* ]] || cache_identity="\${cache_scheme}<redacted>@\${cache_location#*@}"
        local credential_url
        credential_url="$(printf '%s' "\${substituter}" | tr '[:upper:]' '[:lower:]')"
        if [[ "\${cache_location%%/*}" == *@* || "\${credential_url}" =~ [?\\&\\#](access[_-]?token|api[_-]?key|apikey|auth|authorization|credential|credentials|password|passwd|secret|sig|signature|token)= || "\${credential_url}" =~ [?\\&\\#][^?\\&\\#=]*%[0-9a-f][0-9a-f][^?\\&\\#=]*= ]]; then
          echo "error: configured Nix substituter embeds credentials in its URL; use netrc-file authentication: \${cache_identity}" 1>&2
          unset NIX_CONFIG
          unset VBR_NIX_CACHE_HEALTH_APPLIED VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY
          unset VBR_NIX_CACHE_HEALTH_SOURCE_CONFIG
          __vbr_stage0_cache_nix_args=()
          return 1
        fi
        local cache_base="\${substituter%%\\?*}"
        local cache_query=""
        [[ "\${substituter}" != *\\?* ]] || cache_query="?\${substituter#*\\?}"
        local cache_info_url="\${cache_base%/}/nix-cache-info\${cache_query}"
        local probe_status=1
        if command -v curl >/dev/null 2>&1; then
          local curl_args=(-fsS --connect-timeout 3 --max-time 5)
          [[ -z "\${netrc_file}" || ! -f "\${netrc_file}" || ! -r "\${netrc_file}" ]] || curl_args+=(--netrc-file "\${netrc_file}")
          if curl "\${curl_args[@]}" "\${cache_info_url}" >/dev/null 2>&1; then
            probe_status=0
          else
            probe_status="$?"
          fi
        fi
        case "\${probe_status}" in
          0|5|6|7|16|28|35|52|55|56|92) ;;
          *)
            if [[ "\${current_policy}" == "auto" && " \${optional_substituters} " == *" \${substituter} "* && " \${required_substituters} " != *" \${substituter} "* ]]; then
              removed+=("\${substituter}")
              removed_identities+=("\${cache_identity}")
              continue
            fi
            echo "error: Nix cache probe rejected non-transport failure for \${cache_identity}: curl exit \${probe_status}" 1>&2
            unset VBR_NIX_CACHE_HEALTH_APPLIED VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY
            __vbr_stage0_cache_nix_args=()
            return 1
            ;;
        esac
        if [[ "\${probe_status}" -eq 0 ]]; then
          available+=("\${substituter}")
        else
          if [[ " \${required_substituters} " == *" \${substituter} "* ]]; then
            echo "error: required Nix substituter unavailable: \${cache_identity}" 1>&2
            unset VBR_NIX_CACHE_HEALTH_APPLIED VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG
            unset VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY
            return 1
          fi
          removed+=("\${substituter}")
          removed_identities+=("\${cache_identity}")
        fi
        ;;
      *) available+=("\${substituter}") ;;
    esac
  done

  if [[ "\${#removed[@]}" -eq 0 ]]; then
    export NIX_CONFIG="\${reviewed_config}"
    export VBR_NIX_CACHE_HEALTH_APPLIED=1
    export VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG="\${NIX_CONFIG}"
    export VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS="\${required_substituters}"
    export VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS="\${optional_substituters}"
    export VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY="\${current_policy}"
    return 0
  fi
  if [[ "\${current_policy}" == "strict" ]]; then
    echo "error: configured Nix substituter(s) unavailable: \${removed_identities[*]}" 1>&2
    unset VBR_NIX_CACHE_HEALTH_APPLIED VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY
    __vbr_stage0_cache_nix_args=()
    return 1
  fi

  local optional_kept=()
  local optional_kept_identities=()
  local required_kept=()
  for substituter in \${optional_substituters}; do
    if [[ " \${available[*]-} " == *" \${substituter} "* ]]; then
      optional_kept+=("\${substituter}")
      local kept_identity="\${substituter%%\\?*}"
      kept_identity="\${kept_identity%%\\#*}"
      local kept_scheme="\${kept_identity%%://*}://"
      local kept_location="\${kept_identity#*://}"
      [[ "\${kept_location%%/*}" != *@* ]] || kept_identity="\${kept_scheme}<redacted>@\${kept_location#*@}"
      optional_kept_identities+=("\${kept_identity}")
    fi
  done
  for substituter in \${required_substituters}; do
    [[ " \${available[*]-} " == *" \${substituter} "* ]] && required_kept+=("\${substituter}")
  done

  local retained required_joined optional_kept_joined
  export NIX_CONFIG="\${reviewed_config}"
  retained="$(__vbr_stage0_strip_nix_cache_overrides)"
  required_joined="\${required_kept[*]-}"
  optional_kept_joined="\${optional_kept[*]-}"
  __vbr_stage0_cache_nix_args=(--option substituters "\${required_joined}" --option extra-substituters "\${optional_kept_joined}" --option connect-timeout 3 --option stalled-download-timeout 10 --option fallback true)
  export NIX_CONFIG="\${retained}"$'\\n'"substituters = \${required_joined}"$'\\n'"extra-substituters = \${optional_kept_joined}"$'\\n''connect-timeout = 3'$'\\n''stalled-download-timeout = 10'$'\\n''fallback = true'
  export VBR_NIX_CACHE_HEALTH_APPLIED=1
  export VBR_NIX_CACHE_HEALTH_REVIEWED_CONFIG="\${NIX_CONFIG}"
  export VBR_NIX_CACHE_HEALTH_REVIEWED_REQUIRED_SUBSTITUTERS="\${required_joined}"
  export VBR_NIX_CACHE_HEALTH_REVIEWED_OPTIONAL_SUBSTITUTERS="\${optional_kept_joined}"
  export VBR_NIX_CACHE_HEALTH_REVIEWED_POLICY="\${current_policy}"
  echo "[env] nix cache health: disabled unreachable substituter(s): \${removed_identities[*]}" 1>&2
  echo "[env] nix cache health: using optional substituter(s): \${optional_kept_identities[*]:-<none>}" 1>&2
}

__vbr_stage0_filtered_viberoots_input() {
  local src="\${1:-}"
  [[ -n "\${src}" && -f "\${src}/flake.nix" ]] || return 1
  local src_real
  src_real="$(cd "\${src}" && pwd -P 2>/dev/null || true)"
  [[ -n "\${src_real}" ]] || return 1
  local local_real=""
  [[ -d "\${PWD}/viberoots" ]] && local_real="$(cd "\${PWD}/viberoots" && pwd -P 2>/dev/null || true)"
  [[ -n "\${local_real}" && "\${src_real}" == "\${local_real}" ]] || return 1
  command -v rsync >/dev/null 2>&1 || return 1

  local dst="\${PWD}/.viberoots/workspace/viberoots-flake-input"
  mkdir -p "\${dst}" || return 1
  : > "\${PWD}/.viberoots/workspace/.metadata_never_index" 2>/dev/null || true
  : > "\${dst}/.metadata_never_index" 2>/dev/null || true
  rsync -a --delete --delete-excluded \\
${generatedRepoStateRsyncExcludes()}\
    --exclude /.git --exclude /node_modules --exclude /.viberoots \\
    --exclude /.pnpm-store --exclude /.pnpm-home --exclude /coverage \\
    --exclude /.clinic --exclude /.turbo --exclude /.cache --exclude /dist --exclude /build/ \\
    --exclude /.vite --exclude /.next --exclude /.wasm-producer \\
    --exclude '.node_modules.lockfile-guard.*' --exclude '.*.tmp' \\
    --exclude '.*.ts.??????' --exclude '.*.tsx.??????' \\
    --exclude '.*.js.??????' --exclude '.*.mjs.??????' \\
    --exclude result --exclude 'result-*' \\
    "\${src_real}/" "\${dst}/" >/dev/null 2>&1 || return 1
  [[ -f "\${dst}/flake.nix" ]] || return 1; : > "\${dst}/.source-fingerprint" 2>/dev/null || true
  printf '%s\\n' "\${dst}"
}

__vbr_stage0_align_workspace_flake_input() {
  local flake="\${PWD}/.viberoots/workspace/flake.nix"
  local desired='    viberoots.url = "path:./viberoots-flake-input";'
  [[ -f "\${flake}" && -f "\${PWD}/.viberoots/workspace/viberoots-flake-input/flake.nix" ]] || return 0
  grep -Fq '# ${generatedMarker}' "\${flake}" 2>/dev/null || return 0
  grep -Fq "\${desired}" "\${flake}" 2>/dev/null && return 0
  local tmp="\${flake}.$$.$RANDOM.tmp"
  awk -v desired="\${desired}" '
    /^[[:space:]]*viberoots\\.url[[:space:]]*=/ { print desired; next }
    { print }
  ' "\${flake}" > "\${tmp}" && mv "\${tmp}" "\${flake}" && : > "\${PWD}/.viberoots/workspace/viberoots-flake-input/.source-fingerprint" 2>/dev/null || rm -f "\${tmp}"
}

__vbr_stage0_prune_workspace_flake_generated_roots() {
  local root="\${PWD}/.viberoots/workspace"
  [[ -d "\${root}" ]] || return 0
  local rel
  for rel in backups cache codex-test-logs install-cache nix-xdg-cache pr-logs xdg-cache; do
    rm -rf -- "\${root}/\${rel}" 2>/dev/null || true
  done
  rm -f -- "\${root}/exact-env-smoke.out" "\${root}/host-path" 2>/dev/null || true
}

__vbr_flake_args=()
__vbr_flake_input_is_generated_filtered=0
__vbr_flake_input_root="\${VIBEROOTS_FLAKE_INPUT_ROOT:-}"
if [[ "\${VBR_DEVSHELL_RECONCILE:-}" != "1" || "\${VBR_DEVSHELL_USE_GENERATED_AUTHORITY:-}" == "1" ]]; then
  # Ordinary devshell entry is read-only and consumes the generated immutable
  # flake/lock authority as-is. Only explicit u may refresh from the live source.
  __vbr_flake_input_root=""
  unset VIBEROOTS_FLAKE_INPUT_ROOT
elif [[ -z "\${__vbr_flake_input_root}" || ! -f "\${__vbr_flake_input_root}/flake.nix" ]]; then
  __vbr_flake_input_root="\${VIBEROOTS_SOURCE_ROOT:-}"
fi
if [[ "\${VBR_DEVSHELL_RECONCILE:-}" == "1" && "\${VBR_DEVSHELL_USE_GENERATED_AUTHORITY:-}" != "1" && ( -z "\${__vbr_flake_input_root}" || ! -f "\${__vbr_flake_input_root}/flake.nix" ) ]]; then
  __vbr_current_real=""; __vbr_local_real=""; __vbr_filtered_real=""; __vbr_local_source_root="\${PWD}/viberoots"
  [[ -e "\${PWD}/.viberoots/current" ]] && __vbr_current_real="$(cd "\${PWD}/.viberoots/current" && pwd -P 2>/dev/null || true)"
  [[ -d "\${__vbr_local_source_root}" ]] && __vbr_local_real="$(cd "\${__vbr_local_source_root}" && pwd -P 2>/dev/null || true)"
  [[ -d "\${PWD}/.viberoots/workspace/viberoots-flake-input" ]] && __vbr_filtered_real="$(cd "\${PWD}/.viberoots/workspace/viberoots-flake-input" && pwd -P 2>/dev/null || true)"
  if [[ -n "\${__vbr_local_real}" && ( "\${__vbr_current_real}" == "\${__vbr_local_real}" || "\${__vbr_current_real}" == "\${__vbr_filtered_real}" ) ]]; then
    __vbr_flake_input_root="\${__vbr_local_source_root}"
  fi
  unset __vbr_current_real __vbr_local_real __vbr_filtered_real __vbr_local_source_root
fi
__vbr_filtered_real=""; __vbr_input_real=""; __vbr_local_real=""
[[ -d "\${PWD}/.viberoots/workspace/viberoots-flake-input" ]] && __vbr_filtered_real="$(cd "\${PWD}/.viberoots/workspace/viberoots-flake-input" && pwd -P 2>/dev/null || true)"
[[ -n "\${__vbr_flake_input_root}" && -d "\${__vbr_flake_input_root}" ]] && __vbr_input_real="$(cd "\${__vbr_flake_input_root}" && pwd -P 2>/dev/null || true)"
[[ -d "\${PWD}/viberoots" ]] && __vbr_local_real="$(cd "\${PWD}/viberoots" && pwd -P 2>/dev/null || true)"
if [[ -n "\${__vbr_filtered_real}" && "\${__vbr_input_real}" == "\${__vbr_filtered_real}" && -n "\${__vbr_local_real}" ]]; then
  __vbr_flake_input_root="\${PWD}/viberoots"
fi
unset __vbr_filtered_real __vbr_input_real __vbr_local_real
if [[ "\${VBR_DEVSHELL_RECONCILE:-}" == "1" && "\${VBR_DEVSHELL_USE_GENERATED_AUTHORITY:-}" != "1" && -f "\${__vbr_flake_input_root}/flake.nix" ]]; then
  __vbr_source_root="\${__vbr_flake_input_root}"
  __vbr_filtered_flake_input_root="$(__vbr_stage0_filtered_viberoots_input "\${__vbr_flake_input_root}" || true)"
  if [[ -n "\${__vbr_filtered_flake_input_root}" && -f "\${__vbr_filtered_flake_input_root}/flake.nix" ]]; then
    __vbr_flake_input_root="\${__vbr_filtered_flake_input_root}"
    __vbr_flake_input_is_generated_filtered=1
    __vbr_stage0_align_workspace_flake_input
  fi
  unset __vbr_filtered_flake_input_root
  export VIBEROOTS_SOURCE_ROOT="\${__vbr_source_root}"
  export VIBEROOTS_FLAKE_INPUT_ROOT="\${__vbr_flake_input_root}"
  if [[ "\${__vbr_flake_input_is_generated_filtered}" == "1" ]]; then
    __vbr_flake_args=()
  else
    __vbr_flake_args=(--override-input viberoots "path:\${__vbr_flake_input_root}")
  fi
  if [[ "\${__vbr_source_root}" == "\${PWD}/viberoots" && ( -L "\${PWD}/.viberoots/current" || ! -e "\${PWD}/.viberoots/current" ) ]]; then
    if [[ ! -L "\${PWD}/.viberoots/current" || "$(readlink "\${PWD}/.viberoots/current" 2>/dev/null || true)" != "../viberoots" ]]; then
      rm -f "\${PWD}/.viberoots/current" && ln -s ../viberoots "\${PWD}/.viberoots/current"
    fi
  fi
elif [[ "\${VBR_DEVSHELL_RECONCILE:-}" == "1" && "\${VBR_DEVSHELL_USE_GENERATED_AUTHORITY:-}" != "1" ]]; then
  unset VIBEROOTS_SOURCE_ROOT
  unset VIBEROOTS_FLAKE_INPUT_ROOT
fi
unset __vbr_flake_input_is_generated_filtered

__nix_direnv_direnvrc=""
for __candidate in \\
  "\${HOME}/.nix-profile/share/nix-direnv/direnvrc" \\
  "/nix/var/nix/profiles/default/share/nix-direnv/direnvrc"
do
  if [[ -f "\${__candidate}" ]]; then
    __nix_direnv_direnvrc="\${__candidate}"
    break
  fi
done

if [[ -z "\${__nix_direnv_direnvrc}" ]]; then
  echo "error: nix-direnv is required for this repository shell cache path." 1>&2
  echo "install: nix profile install nixpkgs#nix-direnv" 1>&2
  echo "then run: direnv reload" 1>&2
  return 1
fi

source "\${__nix_direnv_direnvrc}"
unset __nix_direnv_direnvrc
unset __candidate

if [[ "\${NIX_CONFIG:-}" != *"experimental-features ="* ]]; then
  export NIX_CONFIG=$'experimental-features = nix-command flakes\\n'"\${NIX_CONFIG:-}"
fi
export WORKSPACE_ROOT="\${PWD}"

__vbr_stage0_apply_nix_cache_health || return 1
__vbr_flake_args+=("\${__vbr_stage0_cache_nix_args[@]}")

if [[ ! -f .viberoots/workspace/flake.nix ]]; then
  echo "error: viberoots workspace flake is missing." 1>&2
  echo "run: viberoots bootstrap-check --repair-if-needed" 1>&2
  echo "or rerun the viberoots bootstrap command from README.md." 1>&2
  return 1
fi

__vbr_stage0_prune_workspace_flake_generated_roots

watch_file .viberoots/workspace/flake.nix
watch_file .viberoots/workspace/flake.lock
[[ -f viberoots/flake.nix ]] && watch_file viberoots/flake.nix

if [[ "\${NIX_PNPM_ALLOW_GENERATE:-}" == "1" ]]; then
  __vbr_flake_args+=(--impure)
fi
use flake "path:\${PWD}/.viberoots/workspace#default" --accept-flake-config --no-write-lock-file "\${__vbr_flake_args[@]}" || return 1
if [[ -n "\${__vbr_host_path:-}" && "\${__vbr_should_write_host_path}" == "1" ]]; then
  printf '%s\\n' "\${__vbr_host_path}" > "\${PWD}/.viberoots/workspace/host-path" 2>/dev/null || true
fi
unset __vbr_host_path __vbr_should_write_host_path
if [[ -n "\${__vbr_source_root:-}" && -d "\${PWD}/viberoots" ]]; then
  __vbr_source_real="$(cd "\${__vbr_source_root}" && pwd -P 2>/dev/null || true)"
  __vbr_local_real="$(cd "\${PWD}/viberoots" && pwd -P 2>/dev/null || true)"
  if [[ -n "\${__vbr_source_real}" && "\${__vbr_source_real}" == "\${__vbr_local_real}" ]]; then
    if [[ -L "\${PWD}/.viberoots/current" || ! -e "\${PWD}/.viberoots/current" ]]; then
      if [[ ! -L "\${PWD}/.viberoots/current" || "$(readlink "\${PWD}/.viberoots/current" 2>/dev/null || true)" != "../viberoots" ]]; then
        rm -f "\${PWD}/.viberoots/current" && ln -s ../viberoots "\${PWD}/.viberoots/current"
      fi
    fi
    export VIBEROOTS_ROOT="\${__vbr_source_root}"
    export VIBEROOTS_SOURCE_ROOT="\${__vbr_source_root}"
  fi
  unset __vbr_source_real __vbr_local_real
fi
unset __vbr_flake_input_root __vbr_source_root __vbr_flake_args __vbr_stage0_cache_nix_args
unset -f __vbr_stage0_strip_nix_cache_overrides __vbr_stage0_resolve_nix_cache_roles __vbr_stage0_nix_cache_role_sets_match __vbr_stage0_apply_nix_cache_health __vbr_stage0_filtered_viberoots_input __vbr_stage0_align_workspace_flake_input __vbr_stage0_prune_workspace_flake_generated_roots
`;
}
