import { execFile, spawn } from "node:child_process";
import fs from "node:fs";
import * as fsp from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import {
  initLocalSprinkleRefValues,
  initSprinkleRefConfigs,
} from "../deployments/sprinkleref-templates";
import { BUCK_PROJECT_IGNORE_LINE } from "./buck-project-ignore";
import { createCommandUi } from "./command-ui";
import { direnvStage0, envrc, filterCapturedHostPath } from "./consumer-direnv";
import {
  consumerGitignoreEntries,
  guardedConsumerTrackedPaths,
  missingConsumerGitignoreEntries,
  staleConsumerTrackedInput,
  type GuardedConsumerTrackedPath,
} from "./consumer-tracked-inputs";
import { writeIfChanged } from "./fs-helpers";
import { mkdirWithMacosMetadataExclusion } from "./macos-metadata";
import { withSanitizedInheritedNixConfig } from "./nix-config-env";
import { envWithResolvedNixBin, resolveToolPathSync } from "./tool-paths";
import { activateWorkspace } from "./workspace-activation";
import {
  mergeViberootsLockNode,
  repairGeneratedWorkspaceLock,
  type FlakeLock,
} from "./workspace-lock-repair";

const execFileAsync = promisify(execFile);

export type ConsumerSourceMode = "flake" | "submodule";
export type DirenvSetupMode = "auto" | "always" | "never";

export type InitConsumerOptions = {
  workspaceRoot: string;
  viberootsUrl: string;
  workspaceName: string;
  sourceMode?: ConsumerSourceMode;
  sourcePath?: string;
  lock?: boolean;
  allowDirenv?: boolean;
  setupDirenv?: DirenvSetupMode;
  runInstall?: boolean;
  allowPnpmGenerateDuringBootstrap?: boolean;
  postClone?: boolean;
};

const generatedMarker = "generated by viberoots/init-consumer";
const gitignoreMarker = "# viberoots local workspace state";
const bootstrapScaffoldPaths = [
  ".buckconfig",
  ".buckroot",
  ".envrc",
  ".gitignore",
  ".metadata_never_index",
  "flake.nix",
  "flake.lock",
  "README.md",
  "projects/.metadata_never_index",
  "projects/AGENTS.md",
  "projects/README.md",
  "projects/config/README.md",
  "projects/config/shared.json",
];
const viberootsInputExcludes = new Set([
  ".git",
  ".direnv",
  "node_modules",
  "buck-out",
  ".viberoots",
  ".pnpm-store",
  ".pnpm-home",
  "coverage",
  ".clinic",
  ".turbo",
  ".cache",
  "dist",
  "build",
  ".vite",
  ".next",
  ".wasm-producer",
  "result",
]);

async function exists(file: string): Promise<boolean> {
  try {
    await fsp.lstat(file);
    return true;
  } catch {
    return false;
  }
}

async function isTracked(workspaceRoot: string, rel: string): Promise<boolean> {
  try {
    await execFileAsync("git", ["ls-files", "--error-unmatch", "--", rel], {
      cwd: workspaceRoot,
    });
    return true;
  } catch {
    return false;
  }
}

async function assertPostCloneTrackedInputsReady(
  opts: InitConsumerOptions,
  sourceMode: ConsumerSourceMode,
): Promise<void> {
  if (!isPostCloneBootstrap(opts)) return;
  const tracked: Partial<Record<GuardedConsumerTrackedPath, string>> = {};
  for (const rel of guardedConsumerTrackedPaths) {
    if (await isTracked(opts.workspaceRoot, rel)) {
      tracked[rel] = await fsp.readFile(path.join(opts.workspaceRoot, rel), "utf8").catch(() => "");
    }
  }
  const stale = staleConsumerTrackedInput({
    tracked,
    expectedBuckconfig: buckconfig(sourceMode),
    expectedEnvrc: envrc(),
  });
  if (stale) {
    throw new Error(
      `error: post-clone found stale tracked generated file ${stale}\nno tracked files were modified\n\nrepair: run viberoots update`,
    );
  }
}

async function writeGeneratedFile(
  workspaceRoot: string,
  rel: string,
  content: string,
): Promise<void> {
  const file = path.join(workspaceRoot, rel);
  await fsp.mkdir(path.dirname(file), { recursive: true });
  if (await exists(file)) {
    const current = await fsp.readFile(file, "utf8");
    if (current === content) return;
    if (current.includes(generatedMarker)) {
      await writeIfChanged(file, content);
      return;
    }
    if (withoutGeneratedMarker(current) === withoutGeneratedMarker(content)) {
      await writeIfChanged(file, content);
      return;
    }
    const backupDir = path.join(workspaceRoot, ".viberoots", "workspace", "backups");
    await fsp.mkdir(backupDir, { recursive: true });
    const backupName = rel.replaceAll("/", "__");
    const backupFile = path.join(backupDir, `${backupName}.${Date.now()}.${process.pid}.bak`);
    await fsp.copyFile(file, backupFile);
    console.error(
      `repair: ${rel} exists and is not generated by viberoots; backed up to ${backupFile}`,
    );
  }
  await writeIfChanged(file, content);
}

function withoutGeneratedMarker(content: string) {
  return content.replace(new RegExp(`^# ${escapeRegExp(generatedMarker)}\\n`), "");
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

async function writeIfMissing(workspaceRoot: string, rel: string, content: string): Promise<void> {
  const file = path.join(workspaceRoot, rel);
  if (await exists(file)) {
    console.error(`preserve: ${rel} exists`);
    return;
  }
  await fsp.mkdir(path.dirname(file), { recursive: true });
  await fsp.writeFile(file, content, "utf8");
}

function pathHasExternalAgentTool(hostPath: string, workspaceRoot: string): boolean {
  const wrapperDirs = new Set(
    [".viberoots/current/build-tools/tools/bin", "viberoots/build-tools/tools/bin"].map((rel) =>
      path.resolve(workspaceRoot, rel),
    ),
  );
  for (const dir of hostPath.split(path.delimiter)) {
    if (!dir) continue;
    const resolved = path.resolve(dir);
    if (wrapperDirs.has(resolved)) continue;
    if (["codex", "claude"].some((tool) => fs.existsSync(path.join(dir, tool)))) return true;
  }
  return false;
}

async function writeHostPathIfUseful(workspaceRoot: string): Promise<void> {
  const hostPath = filterCapturedHostPath(process.env.VBR_HOST_PATH || process.env.PATH || "");
  if (!hostPath) return;
  const file = path.join(workspaceRoot, ".viberoots", "workspace", "host-path");
  if (process.env.VBR_HOST_PATH || pathHasExternalAgentTool(hostPath, workspaceRoot)) {
    await writeIfChanged(file, `${hostPath}\n`);
  }
}

function shouldExcludeViberootsInputRel(rel: string): boolean {
  const parts = rel.split(path.sep).filter(Boolean);
  if (parts.some((part) => viberootsInputExcludes.has(part))) return true;
  const base = parts.at(-1) || "";
  return (
    base === ".metadata_never_index" ||
    base === ".source-fingerprint" ||
    base === ".node_modules.lockfile-guard" ||
    base.startsWith(".node_modules.lockfile-guard.") ||
    base.endsWith(".tmp") ||
    /^.*\.(ts|tsx|js|mjs)\.[A-Za-z0-9]{6}$/.test(base) ||
    base.startsWith("result-")
  );
}

async function copyViberootsInputTree(src: string, dst: string): Promise<void> {
  await fsp.rm(dst, { recursive: true, force: true });
  await fsp.mkdir(dst, { recursive: true });
  async function visit(dir: string): Promise<void> {
    for (const entry of await fsp.readdir(dir, { withFileTypes: true })) {
      const source = path.join(dir, entry.name);
      const rel = path.relative(src, source);
      if (shouldExcludeViberootsInputRel(rel)) continue;
      const target = path.join(dst, rel);
      if (entry.isDirectory()) {
        await fsp.mkdir(target, { recursive: true });
        await visit(source);
      } else if (entry.isSymbolicLink()) {
        await fsp.mkdir(path.dirname(target), { recursive: true });
        await fsp.symlink(await fsp.readlink(source), target);
      } else if (entry.isFile()) {
        await fsp.mkdir(path.dirname(target), { recursive: true });
        await fsp.copyFile(source, target);
      }
    }
  }
  await visit(src);
  await fsp.writeFile(path.join(dst, ".metadata_never_index"), "", "utf8");
  await fsp.writeFile(path.join(dst, ".source-fingerprint"), "", "utf8");
}

async function prepareFilteredViberootsInput(
  workspaceRoot: string,
  opts: InitConsumerOptions,
): Promise<string | undefined> {
  const sourcePath = opts.sourcePath ? path.resolve(workspaceRoot, opts.sourcePath) : "";
  const localSourcePath = path.resolve(workspaceRoot, "viberoots");
  if (!sourcePath || sourcePath !== localSourcePath) return undefined;
  if (!(await exists(path.join(sourcePath, "flake.nix")))) return undefined;
  const filtered = path.join(workspaceRoot, ".viberoots", "workspace", "viberoots-flake-input");
  await copyViberootsInputTree(sourcePath, filtered);
  return filtered;
}

async function gitOutput(args: string[], cwd: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync("git", args, { cwd });
    return String(stdout || "").trim();
  } catch {
    return "";
  }
}

async function localViberootsRevision(opts: InitConsumerOptions): Promise<string> {
  const sourcePath = opts.sourcePath ? path.resolve(opts.workspaceRoot, opts.sourcePath) : "";
  if (!sourcePath) return "";
  return gitOutput(["rev-parse", "HEAD"], sourcePath);
}

async function submoduleRemoteUrl(opts: InitConsumerOptions): Promise<string> {
  return (
    (await gitOutput(
      ["config", "-f", ".gitmodules", "--get", "submodule.viberoots.url"],
      opts.workspaceRoot,
    )) ||
    (opts.sourcePath
      ? await gitOutput(
          ["remote", "get-url", "origin"],
          path.resolve(opts.workspaceRoot, opts.sourcePath),
        )
      : "") ||
    "https://github.com/viberoots/viberoots.git"
  );
}

function gitFlakeUrl(url: string, rev: string): string {
  const base = url.startsWith("git+") ? url : `git+${url}`;
  const sep = base.includes("?") ? "&" : "?";
  return `${base}${sep}rev=${rev}`;
}

function gitLockUrl(url: string): string {
  return url.startsWith("git+") ? url.slice("git+".length) : url;
}

function normalizeHiddenSubmoduleWorkspaceLockText(
  opts: InitConsumerOptions,
  text: string,
): string {
  const lock = JSON.parse(text) as {
    nodes?: Record<
      string,
      {
        locked?: {
          lastModified?: number;
          lastModifiedDate?: string;
          narHash?: string;
          path?: string;
          type?: string;
        };
        original?: { path?: string; type?: string };
        parent?: unknown;
      }
    >;
  };
  const node = lock.nodes?.viberoots;
  const filteredInput = path.join(
    opts.workspaceRoot,
    ".viberoots",
    "workspace",
    "viberoots-flake-input",
  );
  if (node?.locked?.type === "path" && node.locked.path) {
    const lockedPath = path.resolve(
      opts.workspaceRoot,
      ".viberoots",
      "workspace",
      node.locked.path,
    );
    if (path.resolve(lockedPath) === path.resolve(filteredInput)) {
      node.locked.path = "./viberoots-flake-input";
      delete node.locked.lastModified;
      delete node.locked.lastModifiedDate;
      delete node.locked.narHash;
      node.original = { path: "./viberoots-flake-input", type: "path" };
      node.parent = [];
      return `${JSON.stringify(lock, null, 2)}\n`;
    }
  }
  return text;
}

async function writePortableRootLockForSubmodule(opts: InitConsumerOptions): Promise<boolean> {
  const hiddenLock = path.join(opts.workspaceRoot, ".viberoots", "workspace", "flake.lock");
  if (!(await exists(hiddenLock))) return false;
  const hiddenLockText = await fsp.readFile(hiddenLock, "utf8");
  const rootLockPath = path.join(opts.workspaceRoot, "flake.lock");
  let existingRootLock: FlakeLock | null = null;
  try {
    existingRootLock = JSON.parse(await fsp.readFile(rootLockPath, "utf8")) as FlakeLock;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const rev = await localViberootsRevision(opts);
  if (!/^[0-9a-f]{40}$/i.test(rev)) return false;
  const remoteUrl = await submoduleRemoteUrl(opts);
  const workspaceFlake = `path:${path.join(opts.workspaceRoot, ".viberoots", "workspace")}`;
  const { nixBin, nixEnv } = selectedNixCommand();
  await execFileAsync(
    nixBin,
    [
      "flake",
      "lock",
      "--accept-flake-config",
      "--override-input",
      "viberoots",
      gitFlakeUrl(remoteUrl, rev),
      workspaceFlake,
    ],
    { cwd: opts.workspaceRoot, env: nixEnv, maxBuffer: 1024 * 1024 * 16 },
  );
  try {
    const candidateLock = JSON.parse(await fsp.readFile(hiddenLock, "utf8")) as FlakeLock;
    const portableLock = existingRootLock
      ? mergeViberootsLockNode(existingRootLock, candidateLock)
      : candidateLock;
    const node = portableLock.nodes?.viberoots as
      | { original?: Record<string, unknown> }
      | undefined;
    if (!node) return false;
    node.original = {
      rev,
      type: "git",
      url: gitLockUrl(remoteUrl),
    };
    await fsp.writeFile(rootLockPath, `${JSON.stringify(portableLock, null, 2)}\n`, "utf8");
  } finally {
    await fsp.writeFile(
      hiddenLock,
      normalizeHiddenSubmoduleWorkspaceLockText(opts, hiddenLockText),
      "utf8",
    );
  }
  return true;
}

async function ensureGitignoreEntries(workspaceRoot: string): Promise<void> {
  const file = path.join(workspaceRoot, ".gitignore");
  let current = "";
  try {
    current = await fsp.readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const missing = missingConsumerGitignoreEntries(current);
  if (!missing.length) return;
  const prefix = current && !current.endsWith("\n") ? "\n" : "";
  const separator = current.trim() ? "\n" : "";
  const block = `${gitignoreMarker}\n${missing.join("\n")}\n`;
  await fsp.writeFile(file, `${current}${prefix}${separator}${block}`, "utf8");
}

async function writeBuckroot(workspaceRoot: string): Promise<void> {
  const rel = ".buckroot";
  const file = path.join(workspaceRoot, rel);
  if ((await exists(file)) && (await fsp.readFile(file, "utf8")) === ".\n") return;
  if (await exists(file)) {
    const backupDir = path.join(workspaceRoot, ".viberoots", "workspace", "backups");
    await fsp.mkdir(backupDir, { recursive: true });
    const backupFile = path.join(backupDir, `${rel}.${Date.now()}.${process.pid}.bak`);
    await fsp.copyFile(file, backupFile);
    console.error(`repair: ${rel} exists and is not canonical; backed up to ${backupFile}`);
  }
  await fsp.writeFile(file, ".\n", "utf8");
}

function relativeLinkTarget(workspaceRoot: string, fromDir: string, target: string): string {
  const workspaceRel = path.relative(workspaceRoot, target);
  if (workspaceRel.startsWith("..") || path.isAbsolute(workspaceRel)) return target;
  const rel = path.relative(fromDir, target) || ".";
  return rel.startsWith(".") ? rel : `./${rel}`;
}

async function repairCurrentSymlinkForBootstrap(
  workspaceRoot: string,
  sourcePath: string | undefined,
): Promise<void> {
  if (!sourcePath) return;
  const currentPath = path.join(workspaceRoot, ".viberoots", "current");
  const target = relativeLinkTarget(
    workspaceRoot,
    path.dirname(currentPath),
    path.resolve(workspaceRoot, sourcePath),
  );
  let shouldReportRepair = false;
  try {
    const stat = await fsp.lstat(currentPath);
    if (stat.isSymbolicLink()) {
      if ((await fsp.readlink(currentPath)) === target) return;
      await fsp.unlink(currentPath);
      shouldReportRepair = true;
    } else {
      const backupDir = path.join(workspaceRoot, ".viberoots", "workspace", "backups");
      await fsp.mkdir(backupDir, { recursive: true });
      const backupFile = path.join(
        backupDir,
        `.viberoots__current.${Date.now()}.${process.pid}.bak`,
      );
      await fsp.rename(currentPath, backupFile);
      console.error(
        `repair: .viberoots/current existed and was not a symlink; moved to ${backupFile}`,
      );
      shouldReportRepair = true;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  await fsp.symlink(target, currentPath);
  if (shouldReportRepair) console.error(`repair: .viberoots/current now points to ${target}`);
}

export function buckconfig(mode: ConsumerSourceMode): string {
  const preludePath = "./.viberoots/workspace/prelude";
  return `# ${generatedMarker}
[buildfile]
name = TARGETS

[repositories]
root = .
viberoots = ./.viberoots/current
prelude = ${preludePath}
toolchains = ./.viberoots/current/toolchains
repo_toolchains = ./.viberoots/workspace/toolchains
fbsource = ./.viberoots/current/config/fbsource_stub
fbcode = ./.viberoots/current/config/fbcode_stub
config = ./.viberoots/current/config
workspace_providers = ./.viberoots/workspace/providers
workspace_buck = ./.viberoots/workspace/buck

[cells]
root = .
viberoots = ./.viberoots/current
prelude = ${preludePath}
toolchains = ./.viberoots/current/toolchains
repo_toolchains = ./.viberoots/workspace/toolchains
fbsource = ./.viberoots/current/config/fbsource_stub
fbcode = ./.viberoots/current/config/fbcode_stub
config = ./.viberoots/current/config
workspace_providers = ./.viberoots/workspace/providers
workspace_buck = ./.viberoots/workspace/buck

[build]
prelude = prelude
user_platform = prelude//platforms:default
target_platforms = prelude//platforms:default

[project]
${BUCK_PROJECT_IGNORE_LINE}
`;
}

function usesLocalSubmoduleSource(opts: InitConsumerOptions): boolean {
  if (!opts.sourcePath || !opts.viberootsUrl.startsWith("path:")) return false;
  return (
    path.resolve(opts.workspaceRoot, opts.sourcePath) ===
    path.resolve(opts.workspaceRoot, "viberoots")
  );
}

function assertSupportedLocalPathSource(opts: InitConsumerOptions): void {
  if (!opts.sourcePath || !opts.viberootsUrl.startsWith("path:")) return;
  const sourcePath = path.resolve(opts.workspaceRoot, opts.sourcePath);
  const localSourcePath = path.resolve(opts.workspaceRoot, "viberoots");
  if (sourcePath === localSourcePath) return;
  const pathRef = opts.viberootsUrl.slice("path:".length);
  const resolvedRef = path.isAbsolute(pathRef)
    ? path.normalize(pathRef)
    : path.resolve(opts.workspaceRoot, pathRef);
  if (resolvedRef === localSourcePath) return;
  if (/^\/nix\/store\/[a-z0-9]{32}-source$/.test(resolvedRef)) return;
  throw new Error(
    `error: init-consumer refuses mutable external path input ${opts.viberootsUrl}\n` +
      `local viberoots path inputs must use ${localSourcePath}\n\n` +
      `repair: place the checkout at ${localSourcePath} or use an immutable /nix/store/*-source input`,
  );
}

function workspaceViberootsUrl(opts: InitConsumerOptions): string {
  if (usesLocalSubmoduleSource(opts)) return "path:./viberoots-flake-input";
  return opts.viberootsUrl;
}

function rootViberootsUrl(opts: InitConsumerOptions): string {
  if (usesLocalSubmoduleSource(opts)) return "path:./.viberoots/workspace/viberoots-flake-input";
  return opts.viberootsUrl;
}

function flakeNix(opts: InitConsumerOptions, viberootsUrl = opts.viberootsUrl): string {
  return `# ${generatedMarker}
{
  description = "viberoots consumer workspace";

  nixConfig.allowed-impure-env-vars = [
    "BUCK_GRAPH_JSON"
    "ROOT_GOMOD2NIX_TOML"
    "BUCK_TEST_SRC"
    "BUCK_TARGET"
    "NIX_GO_DEV_OVERRIDE_JSON"
    "NIX_CPP_DEV_OVERRIDE_JSON"
    "NIX_PY_DEV_OVERRIDE_JSON"
    "NIX_PY_TEST_RESOLVE_JSON"
    "PLANNER_NO_DEV_OVERRIDE_LOG"
    "PLANNER_TRACE"
    "NIX_PNPM_ALLOW_GENERATE"
    "NIX_PNPM_FETCH_TIMEOUT"
    "NIX_PNPM_INSTALL_TIMEOUT"
    "NIX_NODE_TEST_PATTERNS"
    "COVERAGE"
    "VBR_VERIFY_LOCK_DIR"
    "WORKSPACE_ROOT"
    "VIBEROOTS_ROOT"
    "VIBEROOTS_SOURCE_ROOT"
    "VIBEROOTS_FLAKE_INPUT_ROOT"
    "TEST_RSYNC_ROOTS"
    "TEST_PARTIAL_CLONE_GO_ONLY"
    "TEST_EXCLUDE_CPP_REQS"
  ];

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixpkgs_23_11.url = "github:NixOS/nixpkgs/nixos-23.11";
    buck2.url = "github:facebook/buck2/201beb86106fecdc84e30260b0f1abb5bf576988";
    gomod2nix.url = "github:nix-community/gomod2nix";
    gomod2nix.inputs.nixpkgs.follows = "nixpkgs";
    viberoots.url = "${viberootsUrl}";
    viberoots.inputs.nixpkgs.follows = "nixpkgs";
    viberoots.inputs.buck2.follows = "buck2";
    viberoots.inputs.gomod2nix.follows = "gomod2nix";
  };

  outputs = inputs:
    let
      registryExtensionPath = ./nixpkgs-source-registry-extension.nix;
      nixpkgsRegistryExtension =
        if builtins.pathExists registryExtensionPath
        then import registryExtensionPath { inherit inputs; }
        else { profiles = { }; };
    in
    inputs.viberoots.lib.mkWorkspace {
      workspaceSrc =
        let
          root = builtins.getEnv "WORKSPACE_ROOT";
        in
        if root != "" then root else ../..;
      viberootsInput = inputs.viberoots;
      workspaceName = "${opts.workspaceName}";
      inherit nixpkgsRegistryExtension;
    };
}
`;
}

function rootFlakeNix(opts: InitConsumerOptions): string {
  return flakeNix(opts, rootViberootsUrl(opts))
    .replace('if root != "" then root else ../..;', 'if root != "" then root else ./.;')
    .replace(
      "registryExtensionPath = ./nixpkgs-source-registry-extension.nix;",
      "registryExtensionPath = ./.viberoots/workspace/nixpkgs-source-registry-extension.nix;",
    );
}

function workspaceTargets(): string {
  return `# ${generatedMarker}
filegroup(
    name = "flake.lock",
    srcs = ["flake.lock"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "nixpkgs-source-registry-extension",
    srcs = ["nixpkgs-source-registry-extension.nix"],
    visibility = ["PUBLIC"],
)
`;
}

function emptyRegistryExtension(): string {
  return "{ inputs }: { profiles = { }; }\n";
}

function consumerReadme(mode: ConsumerSourceMode): string {
  const sourceLine =
    mode === "submodule"
      ? "- `viberoots/`: reusable build tooling and development shell support."
      : "- `.viberoots/current`: pinned viberoots tooling source resolved from the workspace flake.";
  const docsLine =
    mode === "submodule"
      ? "See `viberoots/README.md` and `projects/README.md`."
      : "See the pinned viberoots README through `.viberoots/current/README.md` and `projects/README.md`.";
  return `# Workspace

This workspace is split between:

${sourceLine}
- \`projects/\`: application and project source.

${docsLine}

## Existing Checkout / New Workstation

Use viberoots' post-clone script after cloning this already-initialized workspace on a new
machine. It repairs local ignored workspace state from the checked-in lock, runs the initial
install step, and does not advance the pinned viberoots input.

\`\`\`bash
curl -fsSL https://viberoots.dev/post-clone | bash
b && v
\`\`\`
`;
}

function projectsAgentNotes(mode: ConsumerSourceMode): string {
  const docsLine =
    mode === "submodule"
      ? "- \\`../viberoots/README.md\\`"
      : "- \\`../.viberoots/current/README.md\\`";
  return `# Agent Notes

This workspace uses viberoots to provide shared repository tooling, development commands,
workspace conventions, scaffolding, templates, deployment helpers, and verification flow.

Before changing setup, dependency, build, test, scaffold, deployment, or verification behavior,
read:

- \`../README.md\`
${docsLine}
- \`../.viberoots/current/docs/README.md\`
- \`../.viberoots/current/build-tools/docs/README.md\`
- \`../.viberoots/current/docs/handbook/getting-started-on-a-pr.md\`

Use the workspace commands from the repo root:

\`\`\`bash
i && b && v
\`\`\`

Do not install repository tools manually. Add or update tools only through the patterns and
best practices provided and used by viberoots.

Keep application and library code under \`projects/\`. Do not copy viberoots-owned tooling,
documentation, templates, patches, toolchains, or dependency metadata into the consumer root.
`;
}

function projectConfigReadme(): string {
  return `# Project Config

This directory contains the project configuration surfaces used by viberoots-provided setup,
deployment, secret, and runtime-value workflows.

Read these viberoots docs before changing config shape or resolution behavior:

- \`../../.viberoots/current/docs/sprinkleref.md\`
- \`../../.viberoots/current/docs/local-sprinkleref.md\`
- \`../../.viberoots/current/docs/control-plane-guide.md\`
- \`../../.viberoots/current/docs/secrets-usage.md\`
- \`../../.viberoots/current/docs/deployments-usage.md\`

Use \`shared.json\` for checked-in, non-secret values and topology that should be the same for the
repo. Add new shared values under \`values\`, then refer to them with \`config://...\`.

Use \`local.json\` for gitignored, per-operator values and clone-local overrides. Create or refresh
local placeholders with:

\`\`\`bash
sprinkleref --init-local
\`\`\`

Use \`secret://...\` refs for true secrets. Store secret values through SprinkleRef instead of
putting plaintext secrets in \`shared.json\` or \`local.json\`:

\`\`\`bash
sprinkleref --update secret://path/to/secret --create-missing
\`\`\`

Use \`runtime://...\` refs for values supplied by the selected runtime host contract.
`;
}

async function commandExists(command: string): Promise<boolean> {
  try {
    await execFileAsync(command, ["--version"]);
    return true;
  } catch {
    return false;
  }
}

async function nixDirenvReady(): Promise<boolean> {
  if (!(await commandExists("direnv"))) return false;
  for (const candidate of [
    path.join(process.env.HOME || "", ".nix-profile", "share", "nix-direnv", "direnvrc"),
    "/nix/var/nix/profiles/default/share/nix-direnv/direnvrc",
  ]) {
    if (candidate && (await exists(candidate))) return true;
  }
  return false;
}

async function runMacosDirenvBootstrap(sourcePath: string): Promise<void> {
  if (process.platform !== "darwin") {
    console.error("direnv/nix-direnv are not ready; install them before running direnv allow.");
    return;
  }
  const helper = path.join(sourcePath, "build-tools", "tools", "bootstrap", "macos-direnv.sh");
  await execFileAsync(helper, [], { maxBuffer: 1024 * 1024 * 16 });
  process.env.PATH = [
    path.join(process.env.HOME || "", ".nix-profile", "bin"),
    "/nix/var/nix/profiles/default/bin",
    process.env.PATH || "",
  ]
    .filter(Boolean)
    .join(path.delimiter);
}

async function setupDirenvIfNeeded(opts: {
  mode: DirenvSetupMode;
  sourcePath: string;
}): Promise<void> {
  if (opts.mode === "never") return;
  if (opts.mode === "auto" && (await nixDirenvReady())) return;
  await runMacosDirenvBootstrap(opts.sourcePath);
}

async function shouldAllowPnpmGenerateDuringBootstrap(opts: InitConsumerOptions): Promise<boolean> {
  if (opts.allowPnpmGenerateDuringBootstrap) return true;
  if (process.env.VBR_BOOTSTRAP_PNPM_GENERATE === "1") return true;
  if (process.env.VBR_POST_CLONE === "1" || process.env.VIBEROOTS_POST_CLONE === "1") {
    return false;
  }
  if (!(await exists(path.join(opts.workspaceRoot, ".envrc")))) return true;
  if (!(await exists(path.join(opts.workspaceRoot, ".viberoots", "workspace", "flake.nix")))) {
    return true;
  }
  return false;
}

function maybePnpmGenerateEnv(allowGenerate: boolean): NodeJS.ProcessEnv {
  if (!allowGenerate) return process.env;
  return {
    ...process.env,
    NIX_PNPM_ALLOW_GENERATE: "1",
    VBR_INSTALL_REFRESH_PNPM_HASHES: "1",
  };
}

function isPostCloneBootstrap(opts?: InitConsumerOptions): boolean {
  return (
    opts?.postClone === true ||
    process.env.VBR_POST_CLONE === "1" ||
    process.env.VIBEROOTS_POST_CLONE === "1"
  );
}

async function runOptionalDirenvAllow(
  workspaceRoot: string,
  allowPnpmGenerate: boolean,
): Promise<void> {
  const ui = createCommandUi();
  try {
    await execFileAsync("direnv", ["allow", workspaceRoot], {
      cwd: workspaceRoot,
      env: maybePnpmGenerateEnv(allowPnpmGenerate),
    });
    ui.ok("direnv allowed", workspaceRoot);
  } catch {
    console.error("direnv is not installed or not on PATH, or direnv allow failed.");
    console.error(`next: cd ${workspaceRoot}`);
    console.error("next: direnv allow && direnv reload");
  }
}

async function runInstall(workspaceRoot: string, allowPnpmGenerate: boolean): Promise<void> {
  await runInherited(
    "direnv",
    ["exec", workspaceRoot, "i"],
    workspaceRoot,
    maybePnpmGenerateEnv(allowPnpmGenerate),
  );
}

async function runInherited(
  command: string,
  args: string[],
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command, args, { cwd, env, stdio: "inherit" });
    child.on("error", reject);
    child.on("exit", (code, signal) => {
      if (code === 0) {
        resolve();
        return;
      }
      const suffix = signal ? ` (signal ${signal})` : "";
      reject(
        new Error(
          `install command failed: ${command} ${args.map(shellish).join(" ")} exited ${code ?? "null"}${suffix}`,
        ),
      );
    });
  });
}

function shellish(value: string) {
  return /^[A-Za-z0-9_./:=@+-]+$/.test(value) ? value : JSON.stringify(value);
}

function selectedNixCommand(): { nixBin: string; nixEnv: NodeJS.ProcessEnv } {
  const nixEnv = withSanitizedInheritedNixConfig(envWithResolvedNixBin({ ...process.env }));
  return {
    nixBin: resolveToolPathSync("nix", nixEnv),
    nixEnv,
  };
}

async function runNixFlakeLock(opts: InitConsumerOptions): Promise<void> {
  const filteredViberootsInput = await prepareFilteredViberootsInput(opts.workspaceRoot, opts);
  const workspaceFlake = `path:${path.join(opts.workspaceRoot, ".viberoots", "workspace")}`;
  const { nixBin, nixEnv } = selectedNixCommand();
  if (filteredViberootsInput) {
    await execFileAsync(
      nixBin,
      [
        "flake",
        "lock",
        "--accept-flake-config",
        "--override-input",
        "viberoots",
        `path:${filteredViberootsInput}`,
        workspaceFlake,
      ],
      { cwd: opts.workspaceRoot, env: nixEnv, maxBuffer: 1024 * 1024 * 16 },
    );
  } else {
    await execFileAsync(
      nixBin,
      [
        "flake",
        "update",
        "viberoots",
        "--refresh",
        "--accept-flake-config",
        "--flake",
        workspaceFlake,
      ],
      { cwd: opts.workspaceRoot, env: nixEnv, maxBuffer: 1024 * 1024 * 16 },
    );
  }
  const hiddenLock = path.join(opts.workspaceRoot, ".viberoots", "workspace", "flake.lock");
  if (!isPostCloneBootstrap(opts) && (await exists(hiddenLock))) {
    if (usesLocalSubmoduleSource(opts)) {
      if (await writePortableRootLockForSubmodule(opts)) return;
    }
    await fsp.copyFile(hiddenLock, path.join(opts.workspaceRoot, "flake.lock"));
  }
}

async function markBootstrapScaffoldVisibleToGit(workspaceRoot: string): Promise<void> {
  try {
    await execFileAsync("git", ["rev-parse", "--is-inside-work-tree"], {
      cwd: workspaceRoot,
    });
    const existing: string[] = [];
    for (const rel of bootstrapScaffoldPaths) {
      if (await exists(path.join(workspaceRoot, rel))) existing.push(rel);
    }
    if (existing.length > 0) {
      await execFileAsync("git", ["add", "--intent-to-add", "--", ...existing], {
        cwd: workspaceRoot,
      });
    }
  } catch {}
}

export async function initConsumer(opts: InitConsumerOptions): Promise<void> {
  const ui = createCommandUi();
  assertSupportedLocalPathSource(opts);
  const sourceMode: ConsumerSourceMode =
    opts.sourceMode || (opts.sourcePath ? "submodule" : "flake");
  const allowPnpmGenerate = await shouldAllowPnpmGenerateDuringBootstrap(opts);
  await assertPostCloneTrackedInputsReady(opts, sourceMode);
  await mkdirWithMacosMetadataExclusion(opts.workspaceRoot);
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, ".viberoots"));
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, ".viberoots", "workspace"));
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, ".viberoots", "buck"));
  await mkdirWithMacosMetadataExclusion(path.join(opts.workspaceRoot, "projects"));
  await writeHostPathIfUseful(opts.workspaceRoot);

  await writeBuckroot(opts.workspaceRoot);
  await writeGeneratedFile(opts.workspaceRoot, ".buckconfig", buckconfig(sourceMode));
  await writeGeneratedFile(opts.workspaceRoot, ".envrc", envrc());
  await writeGeneratedFile(
    opts.workspaceRoot,
    ".viberoots/bootstrap/direnv-stage0.sh",
    direnvStage0(),
  );
  if (!isPostCloneBootstrap(opts) || !(await exists(path.join(opts.workspaceRoot, "flake.nix")))) {
    await writeGeneratedFile(opts.workspaceRoot, "flake.nix", rootFlakeNix(opts));
  }
  await writeGeneratedFile(
    opts.workspaceRoot,
    ".viberoots/workspace/flake.nix",
    flakeNix(opts, workspaceViberootsUrl(opts)),
  );
  await writeIfMissing(
    opts.workspaceRoot,
    ".viberoots/workspace/nixpkgs-source-registry-extension.nix",
    emptyRegistryExtension(),
  );
  await writeGeneratedFile(opts.workspaceRoot, ".viberoots/workspace/TARGETS", workspaceTargets());
  await writeIfMissing(opts.workspaceRoot, "README.md", consumerReadme(sourceMode));
  await writeIfMissing(
    opts.workspaceRoot,
    "projects/README.md",
    `# Projects

Project and application source belongs here.
`,
  );
  await writeIfMissing(opts.workspaceRoot, "projects/AGENTS.md", projectsAgentNotes(sourceMode));
  await writeIfMissing(opts.workspaceRoot, "projects/config/README.md", projectConfigReadme());
  await ensureGitignoreEntries(opts.workspaceRoot);
  await initSprinkleRefConfigs({
    dir: path.join(opts.workspaceRoot, "projects", "config"),
    workspaceRoot: opts.workspaceRoot,
  });
  await initLocalSprinkleRefValues(opts.workspaceRoot);

  await repairCurrentSymlinkForBootstrap(opts.workspaceRoot, opts.sourcePath);
  if (opts.lock !== false) {
    await runNixFlakeLock(opts);
    await repairGeneratedWorkspaceLock({ workspaceRoot: opts.workspaceRoot });
  }
  await markBootstrapScaffoldVisibleToGit(opts.workspaceRoot);
  const activation = await activateWorkspace({
    start: opts.workspaceRoot,
    env: { ...process.env, WORKSPACE_ROOT: opts.workspaceRoot },
    sourcePath: opts.sourcePath,
  });
  if (opts.allowDirenv !== false) {
    await setupDirenvIfNeeded({
      mode: opts.setupDirenv || "auto",
      sourcePath: activation.sourcePath,
    });
  }
  if (opts.allowDirenv !== false) {
    await runOptionalDirenvAllow(opts.workspaceRoot, allowPnpmGenerate);
  }
  if (opts.runInstall) await runInstall(opts.workspaceRoot, allowPnpmGenerate);
  ui.ok("workspace initialized", opts.workspaceRoot);
}
