import { createHash } from "node:crypto";
import * as fsp from "node:fs/promises";
import path from "node:path";

export const generatedGlobalInputMarker = "generated by viberoots/init-consumer";

export type GlobalNixInputTargets = {
  projectsConfigTargets: string;
  workspaceTargets: string;
  outputNames: Readonly<Record<string, string>>;
};

function digest(contents: Buffer): string {
  return createHash("sha256").update(contents).digest("hex");
}

function exportFile(name: string, src: string, out: string): string {
  return [
    "export_file(",
    `    name = ${JSON.stringify(name)},`,
    `    src = ${JSON.stringify(src)},`,
    `    out = ${JSON.stringify(out)},`,
    '    visibility = ["PUBLIC"],',
    ")",
  ].join("\n");
}

export function renderGlobalNixInputTargets(inputs: {
  hashesJson: Buffer;
  flakeNix: Buffer;
  flakeLock: Buffer;
  registryExtension: Buffer;
}): GlobalNixInputTargets {
  const outputNames = {
    "root//projects/config:node-modules.hashes.json": `node-modules.hashes.${digest(inputs.hashesJson)}.json`,
    "root//.viberoots/workspace:flake.nix": `flake.${digest(inputs.flakeNix)}.nix`,
    "root//.viberoots/workspace:flake.lock": `flake.${digest(inputs.flakeLock)}.lock`,
    "root//.viberoots/workspace:nixpkgs-source-registry-extension": `nixpkgs-source-registry-extension.${digest(inputs.registryExtension)}.nix`,
  } as const;
  const header = `# ${generatedGlobalInputMarker}\nload("@prelude//:rules.bzl", "export_file")\n\n`;
  return {
    outputNames,
    projectsConfigTargets:
      header +
      `${exportFile(
        "node-modules.hashes.json",
        "node-modules.hashes.json",
        outputNames["root//projects/config:node-modules.hashes.json"],
      )}\n`,
    workspaceTargets:
      header +
      [
        exportFile("flake.nix", "flake.nix", outputNames["root//.viberoots/workspace:flake.nix"]),
        exportFile(
          "flake.lock",
          "flake.lock",
          outputNames["root//.viberoots/workspace:flake.lock"],
        ),
        exportFile(
          "nixpkgs-source-registry-extension",
          "nixpkgs-source-registry-extension.nix",
          outputNames["root//.viberoots/workspace:nixpkgs-source-registry-extension"],
        ),
      ].join("\n\n") +
      "\n",
  };
}

export async function readGlobalNixInputTargets(root: string): Promise<GlobalNixInputTargets> {
  const read = async (relative: string) => await fsp.readFile(path.join(root, relative));
  return renderGlobalNixInputTargets({
    hashesJson: await read("projects/config/node-modules.hashes.json"),
    flakeNix: await read(".viberoots/workspace/flake.nix"),
    flakeLock: await read(".viberoots/workspace/flake.lock"),
    registryExtension: await read(".viberoots/workspace/nixpkgs-source-registry-extension.nix"),
  });
}
