export const PROJECT_ENFORCEMENT_PERFORMANCE_BUDGET_SECS = 30;
export const PROJECT_ENFORCEMENT_WARM_PASS_BUDGET_SECS = 60;
export const PROJECT_ENFORCEMENT_PER_TEST_TIMEOUT_SECS = 120;
export const PROJECT_ENFORCEMENT_OVERALL_TIMEOUT_SECS = 240;
