{
  allowed-impure-env-vars = [
    "BUCK_GRAPH_JSON"
    "ROOT_GOMOD2NIX_TOML"
    "BUCK_TEST_SRC"
    "BUCK_TARGET"
    "NIX_GO_DEV_OVERRIDE_JSON"
    "NIX_CPP_DEV_OVERRIDE_JSON"
    "NIX_PY_DEV_OVERRIDE_JSON"
    "NIX_PY_TEST_RESOLVE_JSON"
    "PLANNER_NO_DEV_OVERRIDE_LOG"
    "PLANNER_TRACE"
    "NIX_PNPM_ALLOW_GENERATE"
    "NIX_PNPM_FETCH_TIMEOUT"
    "NIX_NODE_TEST_PATTERNS"
    "COVERAGE"
    "WORKSPACE_ROOT"
  ];
}


