#!/usr/bin/env zx-wrapper
import fs from "fs-extra";
import assert from "node:assert/strict";
import path from "node:path";
import { test } from "node:test";
import { runInTemp } from "../lib/test-helpers";

test("planner-gen renders deterministic Nix from TS config", async () => {
  await runInTemp("planner-gen-snap", async (tmp, $) => {
    // Bring required files into temp workspace
    const root = process.cwd();
    await fs.copy(
      path.join(root, "build-tools/tools/dev/planner-gen.ts"),
      path.join(tmp, "build-tools/tools/dev/planner-gen.ts"),
    );
    await fs.copy(
      path.join(root, "build-tools/tools/dev/planner.config.schema.json"),
      path.join(tmp, "build-tools/tools/dev/planner.config.schema.json"),
    );
    await fs.copy(
      path.join(root, "build-tools/tools/nix/graph-generator.nix"),
      path.join(tmp, "build-tools/tools/nix/graph-generator.nix"),
    );
    await fs.outputFile(
      path.join(tmp, "build-tools/tools/nix/planner/demo.config.ts"),
      `export default { id: "demo", detect: { ruleTypePrefixes: ["demo_"] }, kindRules: [], modulesFile: { inheritFromGo: true } };\n`,
    );

    // Generate
    await $({ cwd: tmp })`node build-tools/tools/dev/planner-gen.ts --lang demo`;

    const gen = await fs.readFile(path.join(tmp, "build-tools/tools/nix/planner/demo.nix"), "utf8");
    assert.match(gen, /Generated by planner-gen for demo/);
    assert.match(
      gen,
      /isTarget = n: \(lib.any \(p: hasPrefix \(n.rule_type or ""\) p\) \[ "demo_" \]\)\;/,
    );
    assert.match(gen, /modulesFileFor = name: modulesTomlFor name;/);
  });
});
