name: my-app
language: ts
template: webapp-ssr-vite
scaf_src_path: build-tools/tools/scaffolding/templates/ts/webapp-ssr-vite

importer: projects/apps/my-app

lockfilePath: projects/apps/my-app/pnpm-lock.yaml

pkgScope: "@apps"

includeNodeTests: true
