/** @vitest-environment jsdom */
import React from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, describe, expect, it, vi } from "vitest";
import { DEFAULT_PIECE_TRANSFORM } from "../src/game/piece-transform";
import { pleominoGameReducer } from "../src/game/reducer";
import * as solverRuntime from "../src/game/solver/solver-runtime";
import type { GameHistoryState } from "../src/game/types";
import { useGameScreenSolve } from "../src/ui/game-screen-solve";

vi.mock("../src/game/solver/solver-runtime.ts", async () => {
  const actual = await vi.importActual<typeof import("../src/game/solver/solver-runtime")>(
    "../src/game/solver/solver-runtime.ts",
  );
  return {
    ...actual,
    solveBoardWithRuntime: vi.fn(),
  };
});

function flushUi(): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, 0));
}

async function waitFor(assertion: () => boolean, timeoutMs = 3000): Promise<void> {
  const startedAt = Date.now();
  while (Date.now() - startedAt < timeoutMs) {
    if (assertion()) {
      return;
    }
    await flushUi();
  }
  throw new Error("timed out waiting for condition");
}

function createTinyHistoryState(): GameHistoryState {
  return {
    past: [],
    future: [],
    present: {
      board: {
        size: { columns: 1, rows: 1 },
        placedPieces: [],
      },
      pieceCatalog: [
        {
          pieceId: "mono",
          color: "#ffffff",
          baseCells: [{ x: 0, y: 0 }],
        },
      ],
      selectedPieceId: null,
      selectedInstanceId: null,
      previewByPieceId: { mono: null },
      transformByPieceId: { mono: DEFAULT_PIECE_TRANSFORM },
      nextPlacedInstanceId: 0,
    },
  };
}

function SolvePolicyHarness() {
  const [state, dispatch] = React.useReducer(pleominoGameReducer, createTinyHistoryState());
  const solve = useGameScreenSolve({ state, dispatch });
  return (
    <div>
      <button
        data-testid="solve"
        onClick={() => {
          void solve.handleSolve();
        }}
      />
      <button
        data-testid="rotate-placed"
        onClick={() => {
          const placed = state.present.board.placedPieces[0];
          if (!placed) {
            return;
          }
          dispatch({
            type: "piece/select",
            pieceId: placed.pieceId,
            instanceId: placed.instanceId,
          });
          dispatch({
            type: "piece/rotate",
            pieceId: placed.pieceId,
            instanceId: placed.instanceId,
            direction: "cw",
          });
        }}
      />
      <button data-testid="reset" onClick={() => dispatch({ type: "board/reset" })} />
    </div>
  );
}

describe("game screen solve policy", () => {
  let container: HTMLDivElement | null = null;
  let root: Root | null = null;

  afterEach(async () => {
    vi.clearAllMocks();
    if (root) {
      root.unmount();
      root = null;
    }
    if (container) {
      container.remove();
      container = null;
    }
    await flushUi();
  });

  it("regenerates immediately when solved board was fully generated by solver", async () => {
    const solveBoardWithRuntime = vi.mocked(solverRuntime.solveBoardWithRuntime);
    solveBoardWithRuntime.mockResolvedValue({
      status: "solved",
      placements: [
        {
          pieceId: "mono",
          transform: { rotation: 0, flipped: false },
          position: { x: 0, y: 0 },
        },
      ],
      nodeExpansions: 1,
      elapsedMs: 1,
      interestingnessScore: 1,
      selectedSignature: "first",
    });

    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
    root.render(<SolvePolicyHarness />);
    await flushUi();

    const solveButton = document.querySelector('[data-testid="solve"]');
    if (!(solveButton instanceof HTMLElement)) {
      throw new Error("expected solve button");
    }

    solveButton.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await waitFor(() => solveBoardWithRuntime.mock.calls.length === 1);

    solveButton.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await waitFor(() => solveBoardWithRuntime.mock.calls.length === 2);
    expect(solveBoardWithRuntime.mock.calls[1]?.[0]?.lockedPlacements).toHaveLength(0);
  });

  it("no-ops on solved boards after user edits until board is cleared", async () => {
    const solveBoardWithRuntime = vi.mocked(solverRuntime.solveBoardWithRuntime);
    solveBoardWithRuntime.mockResolvedValue({
      status: "solved",
      placements: [
        {
          pieceId: "mono",
          transform: { rotation: 0, flipped: false },
          position: { x: 0, y: 0 },
        },
      ],
      nodeExpansions: 1,
      elapsedMs: 1,
      interestingnessScore: 1,
      selectedSignature: "first",
    });

    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
    root.render(<SolvePolicyHarness />);
    await flushUi();

    const solveButton = document.querySelector('[data-testid="solve"]');
    const rotateButton = document.querySelector('[data-testid="rotate-placed"]');
    const resetButton = document.querySelector('[data-testid="reset"]');
    if (!(solveButton instanceof HTMLElement)) {
      throw new Error("expected solve button");
    }
    if (!(rotateButton instanceof HTMLElement)) {
      throw new Error("expected rotate button");
    }
    if (!(resetButton instanceof HTMLElement)) {
      throw new Error("expected reset button");
    }

    solveButton.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await waitFor(() => solveBoardWithRuntime.mock.calls.length === 1);

    rotateButton.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await flushUi();

    solveButton.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await flushUi();
    expect(solveBoardWithRuntime.mock.calls.length).toBe(1);

    resetButton.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await flushUi();
    solveButton.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await waitFor(() => solveBoardWithRuntime.mock.calls.length === 2);
  });
});
