import React from "react";
import type { GameAction } from "../game/reducer";
import { canonicalPlacementSignature } from "../game/solver/interestingness";
import { solveBoardWithRuntime } from "../game/solver/solver-runtime";
import { createSolverRequestFromGameState } from "../game/solver/solver";
import type { GameHistoryState, GameState } from "../game/types";
import { computeWinState } from "../game/win";

const SOLVER_MAX_NODE_EXPANSIONS = 150_000;
const SOLVER_MAX_WALL_CLOCK_MS = 1_200;
const EMPTY_BOARD_MAX_NODE_EXPANSIONS = 300_000;
const EMPTY_BOARD_SOLUTION_POOL_SIZE = 96;
const EMPTY_BOARD_SELECTION_WINDOW_SIZE = 32;
const DEFAULT_INTERESTINGNESS_THRESHOLD = 0;

export type SolveUiState = "idle" | "solving" | "solved-applied" | "unsolved";

function deferSolveStart(): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, 0));
}

function clampInterestingnessThreshold(value: number): number {
  if (Number.isNaN(value)) {
    return DEFAULT_INTERESTINGNESS_THRESHOLD;
  }
  return Math.max(0, Math.min(1, value));
}

function boardPlacementSignature(state: GameState): string {
  return canonicalPlacementSignature(
    state.board.placedPieces.map((placement) => ({
      pieceId: placement.pieceId,
      transform: placement.transform,
      position: placement.position,
    })),
  );
}

export function useGameScreenSolve(args: {
  state: GameHistoryState;
  dispatch: React.Dispatch<GameAction>;
}) {
  const stateRef = React.useRef<GameState>(args.state.present);
  const lastBoardSignatureRef = React.useRef(boardPlacementSignature(args.state.present));
  const ignoreNextGeneratedBoardMutationRef = React.useRef(false);
  const autoGeneratedSolvedBoardActiveRef = React.useRef(false);
  const blockRegenerateUntilBoardClearsRef = React.useRef(false);
  const requestTokenRef = React.useRef(0);
  const solveSeedRef = React.useRef(0);
  const [solveState, setSolveState] = React.useState<SolveUiState>("idle");
  const [isApplyingSolve, setIsApplyingSolve] = React.useState(false);
  const [interestingnessThreshold, setInterestingnessThreshold] = React.useState(
    DEFAULT_INTERESTINGNESS_THRESHOLD,
  );
  const handleInterestingnessThresholdChange = React.useCallback((value: number) => {
    setInterestingnessThreshold(clampInterestingnessThreshold(value));
  }, []);

  React.useEffect(() => {
    const nextState = args.state.present;
    stateRef.current = nextState;
    const nextSignature = boardPlacementSignature(nextState);
    if (nextSignature === lastBoardSignatureRef.current) {
      return;
    }
    lastBoardSignatureRef.current = nextSignature;
    if (ignoreNextGeneratedBoardMutationRef.current) {
      ignoreNextGeneratedBoardMutationRef.current = false;
      return;
    }
    if (nextState.board.placedPieces.length === 0 || !computeWinState(nextState)) {
      autoGeneratedSolvedBoardActiveRef.current = false;
      blockRegenerateUntilBoardClearsRef.current = false;
      return;
    }
    if (autoGeneratedSolvedBoardActiveRef.current) {
      autoGeneratedSolvedBoardActiveRef.current = false;
      blockRegenerateUntilBoardClearsRef.current = true;
    }
  }, [args.state.present]);

  const handleSolve = React.useCallback(async () => {
    if (solveState === "solving") {
      return;
    }
    const startState = stateRef.current;
    const solvedAtStart = computeWinState(startState);
    const canRegenerateSolvedBoard =
      solvedAtStart &&
      autoGeneratedSolvedBoardActiveRef.current &&
      !blockRegenerateUntilBoardClearsRef.current;
    if (solvedAtStart && !canRegenerateSolvedBoard) {
      return;
    }
    const requestState = canRegenerateSolvedBoard
      ? {
          ...startState,
          board: { ...startState.board, placedPieces: [] },
        }
      : startState;
    const requestToken = requestTokenRef.current + 1;
    requestTokenRef.current = requestToken;
    solveSeedRef.current += 1;
    const solveSeed = solveSeedRef.current;
    args.dispatch({ type: "solve/request" });
    setSolveState("solving");
    await deferSolveStart();
    const isEmptyBoard = requestState.board.placedPieces.length === 0;
    let result: Awaited<ReturnType<typeof solveBoardWithRuntime>>;
    try {
      result = await solveBoardWithRuntime(
        createSolverRequestFromGameState(
          requestState,
          isEmptyBoard ? EMPTY_BOARD_MAX_NODE_EXPANSIONS : SOLVER_MAX_NODE_EXPANSIONS,
          SOLVER_MAX_WALL_CLOCK_MS,
          {
            randomSeed: solveSeed,
            solutionPoolSize: isEmptyBoard ? EMPTY_BOARD_SOLUTION_POOL_SIZE : undefined,
            selectionWindowSize: isEmptyBoard ? EMPTY_BOARD_SELECTION_WINDOW_SIZE : undefined,
            interestingnessThreshold,
          },
        ),
      );
    } catch {
      if (requestToken === requestTokenRef.current) {
        setSolveState("unsolved");
      }
      return;
    }
    if (requestToken !== requestTokenRef.current) {
      return;
    }
    if (stateRef.current !== startState) {
      setSolveState("idle");
      return;
    }
    if (result.status !== "solved") {
      setSolveState("unsolved");
      return;
    }
    const generatedAllPlacements = isEmptyBoard;
    if (generatedAllPlacements) {
      autoGeneratedSolvedBoardActiveRef.current = true;
      blockRegenerateUntilBoardClearsRef.current = false;
      const solvedSignature = canonicalPlacementSignature(result.placements);
      ignoreNextGeneratedBoardMutationRef.current =
        solvedSignature !== boardPlacementSignature(startState);
    } else {
      autoGeneratedSolvedBoardActiveRef.current = false;
    }
    setIsApplyingSolve(true);
    args.dispatch({ type: "solve/apply", placements: result.placements });
    setIsApplyingSolve(false);
    setSolveState("solved-applied");
  }, [args.dispatch, interestingnessThreshold, solveState]);

  React.useEffect(() => {
    return () => {
      requestTokenRef.current += 1;
    };
  }, []);

  return {
    handleSolve,
    solveState,
    isApplyingSolve,
    interestingnessThreshold,
    setInterestingnessThreshold: handleInterestingnessThresholdChange,
  };
}
