import * as fsp from "node:fs/promises";
import path from "node:path";
import { applyNixCacheHealthPolicy } from "../verify/nix-cache-health";
import { activateWorkspace } from "../../lib/workspace-activation";
import {
  BUCK_PROJECT_IGNORE_LINE,
  withBuckProjectIgnorePolicy,
} from "../../lib/buck-project-ignore";
import { writeIfChanged } from "../../lib/fs-helpers";
import { ensureBuckCompatibilityCells } from "../../lib/buck-compatibility-cells";
import { readGlobalNixInputTargets } from "../../lib/global-nix-input-targets";
async function pathExists(p: string): Promise<boolean> {
  try {
    await fsp.access(p);
    return true;
  } catch {
    return false;
  }
}

export async function ensureBuckPreludeConfig(root: string): Promise<boolean> {
  try {
    await applyNixCacheHealthPolicy(root);
    await ensureBuckCompatibilityCells(root);
    try {
      const rootCfgPath = path.join(root, ".buckconfig");
      const preludeFileExists = await pathExists(
        path.join(root, ".viberoots", "workspace", "prelude", "prelude.bzl"),
      );
      const rootCfgExists = await pathExists(rootCfgPath);
      const workspaceProvidersCfgExists = await pathExists(
        path.join(root, ".viberoots", "workspace", "providers", ".buckconfig"),
      );
      const workspaceBuckCfgExists = await pathExists(
        path.join(root, ".viberoots", "workspace", "buck", ".buckconfig"),
      );
      const workspaceTargetsExists = await pathExists(
        path.join(root, ".viberoots", "workspace", "TARGETS"),
      );
      const globalTargets = await readGlobalNixInputTargets(root).catch(() => null);
      const projectsConfigTargetsCurrent = await fsp
        .readFile(path.join(root, "projects/config/TARGETS"), "utf8")
        .catch(() => "");
      const workspaceTargetsCurrent = await fsp
        .readFile(path.join(root, ".viberoots/workspace/TARGETS"), "utf8")
        .catch(() => "");
      if (
        !globalTargets ||
        projectsConfigTargetsCurrent !== globalTargets.projectsConfigTargets ||
        workspaceTargetsCurrent !== globalTargets.workspaceTargets
      ) {
        throw new Error("stale global Nix input TARGETS\nrepair: run u");
      }
      if (
        preludeFileExists &&
        rootCfgExists &&
        workspaceProvidersCfgExists &&
        workspaceBuckCfgExists &&
        workspaceTargetsExists
      ) {
        const rootCfg = await fsp.readFile(rootCfgPath, "utf8");
        if (!rootCfg.includes(BUCK_PROJECT_IGNORE_LINE)) {
          return await writeIfChanged(rootCfgPath, withBuckProjectIgnorePolicy(rootCfg));
        }
        return false;
      }
    } catch (error) {
      if (String(error).includes("stale global Nix input TARGETS")) throw error;
    }

    await $({ cwd: root })`bash --noprofile --norc -c ${`set -euo pipefail
      printf '.\n' > .buckroot
      mkdir -p .viberoots/workspace/providers .viberoots/workspace/buck
      if [ "$(uname -s 2>/dev/null || true)" = "Darwin" ]; then
        [ -e .viberoots/.metadata_never_index ] || : > .viberoots/.metadata_never_index
        [ -e .viberoots/workspace/.metadata_never_index ] || : > .viberoots/workspace/.metadata_never_index
        [ -e .viberoots/workspace/providers/.metadata_never_index ] || : > .viberoots/workspace/providers/.metadata_never_index
        [ -e .viberoots/workspace/buck/.metadata_never_index ] || : > .viberoots/workspace/buck/.metadata_never_index
      fi
      cat > .buckconfig <<'EOF'
# generated by viberoots/init-consumer
[buildfile]
name = TARGETS

[repositories]
root = .
viberoots = ./.viberoots/current
prelude = ./.viberoots/workspace/prelude
toolchains = ./.viberoots/current/toolchains
repo_toolchains = ./.viberoots/workspace/toolchains
fbsource = ./.viberoots/workspace/buck-cell-stubs/fbsource
fbcode = ./.viberoots/workspace/buck-cell-stubs/fbcode
config = ./.viberoots/current/config
workspace_providers = ./.viberoots/workspace/providers
workspace_buck = ./.viberoots/workspace/buck

[cells]
root = .
viberoots = ./.viberoots/current
prelude = ./.viberoots/workspace/prelude
toolchains = ./.viberoots/current/toolchains
repo_toolchains = ./.viberoots/workspace/toolchains
fbsource = ./.viberoots/workspace/buck-cell-stubs/fbsource
fbcode = ./.viberoots/workspace/buck-cell-stubs/fbcode
config = ./.viberoots/current/config
workspace_providers = ./.viberoots/workspace/providers
workspace_buck = ./.viberoots/workspace/buck

[build]
prelude = prelude
user_platform = prelude//platforms:default
target_platforms = prelude//platforms:default

[project]
${BUCK_PROJECT_IGNORE_LINE}
EOF
    `}`;
    await activateWorkspace({ start: root });

    await $({ cwd: root })`bash --noprofile --norc -c ${`set -euo pipefail
      cat > .viberoots/workspace/providers/.buckconfig <<'EOF'
[buildfile]
name = TARGETS
EOF
      cat > .viberoots/workspace/buck/.buckconfig <<'EOF'
[buildfile]
name = TARGETS
EOF
      test -f .viberoots/workspace/nixpkgs-source-registry-extension.nix || printf '{ inputs }: { profiles = { }; }\n' > .viberoots/workspace/nixpkgs-source-registry-extension.nix
    `}`;
    return true;
  } catch (e) {
    console.error("failed to ensure Buck prelude config:", e);
    throw e;
  }
}
