#!/usr/bin/env zx-wrapper
import * as fsp from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { runInTemp } from "../lib/test-helpers";

test("provider wiring present only on affected target after patch", async () => {
  await runInTemp("prov-wiring", async (_tmp, _$) => {
    const $ = _$({ stdio: "pipe" });
    // Use .buckconfig and toolchains generated by runInTemp
    await $`scaf new go lib demo-lib --yes --path=libs/demo-lib`;
    // Initialize module before editing (no tidy; avoid network)
    await $`/usr/bin/env bash --noprofile --norc -lc 'cd libs/demo-lib && test -f go.mod || go mod init example.com/demo-lib && go mod edit -require golang.org/x/text@v0.14.0'`;
    // Generate gomod2nix lock at repo root from the lib module via local stub
    const stubDir = path.join(_tmp, "bin");
    await fsp.mkdir(stubDir, { recursive: true });
    const stubPath = path.join(stubDir, "gomod2nix");
    await fsp.writeFile(
      stubPath,
      [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "DIR=.",
        "while [[ $# -gt 0 ]]; do",
        '  case "$1" in',
        "    --dir)",
        '      DIR="$2"; shift 2;;',
        "    *) shift;;",
        "  esac",
        "done",
        'mkdir -p "$DIR"',
        "cat > \"$DIR/gomod2nix.toml\" <<'EOF'",
        "schema = 3",
        "mod = {}",
        "replace = {}",
        "prune = { go-tests = true, unused-packages = true }",
        "EOF",
      ].join("\n"),
      "utf8",
    );
    await $`chmod +x ${stubPath}`;
    await $({
      cwd: _tmp,
      stdio: "inherit",
      env: { ...process.env, PATH: `${stubDir}:${process.env.PATH || ""}` },
    })`gomod2nix --dir libs/demo-lib`;
    await fsp.copyFile(
      path.join(_tmp, "libs", "demo-lib", "gomod2nix.toml"),
      path.join(_tmp, "gomod2nix.toml"),
    );
    // Create a dummy patch for that module version
    await $`/usr/bin/env bash --noprofile --norc -lc 'mkdir -p patches/go && touch patches/go/golang.org__x__text@v0.14.0.patch'`;
    // Run glue and build via Nix graph-generator
    await $`tools/dev/install-deps.ts --glue-only`;
    const outLinkName = `buck-go-${Date.now()}`;
    const outLinkPath = path.join(_tmp, outLinkName);
    try {
      await fsp.rm(outLinkPath, { recursive: false, force: true });
    } catch {}
    await $({
      cwd: _tmp,
      stdio: "inherit",
    })`nix build .#graph-generator --out-link ${outLinkName}`;
    await $`test -f third_party/providers/auto_map.bzl`;
  });
});
