#!/usr/bin/env zx-wrapper
import fs from "fs-extra";
import path from "node:path";

// Provider-driven third-party Go wiring
// - Reads third_party/providers/auto_map.bzl (generated by gen-auto-map)
// - Reads tools/buck/graph.json (exported via export-graph)
// - Correlates module labels (module:import@version) to provider names
// - Copies sources from GOMODCACHE to third_party/go/<importPath>
// - Generates third_party/go/TARGETS with nix_go_third_party_library targets whose
//   names match provider labels (so go/defs.bzl can rewrite providers -> third_party/go deps)

type Entry = { name: string; importPath: string; version: string };

async function readAutoMap(repoRoot: string): Promise<Record<string, string[]>> {
  const p = path.join(repoRoot, "third_party", "providers", "auto_map.bzl");
  if (!(await fs.pathExists(p))) return {};
  const txt = await fs.readFile(p, "utf8");
  const map: Record<string, string[]> = {};
  const reBlock = /(\"[^\"]+\")\s*:\s*\[([^\]]*)\]/g;
  let m: RegExpExecArray | null;
  while ((m = reBlock.exec(txt))) {
    const key = JSON.parse(m[1]);
    const inner = m[2];
    const provs = Array.from(inner.matchAll(/\"([^\"]+)\"/g)).map((mm) => mm[1]);
    map[key] = provs;
  }
  return map;
}

async function loadGraph(repoRoot: string): Promise<Record<string, string[]>> {
  const p = path.join(repoRoot, "tools", "buck", "graph.json");
  if (!(await fs.pathExists(p))) return {};
  const txt = await fs.readFile(p, "utf8");
  const nodes = JSON.parse(txt) as Array<{ name?: string; labels?: string[] }>;
  const out: Record<string, string[]> = {};
  for (const n of nodes) {
    if (!n || !n.name) continue;
    const mods = (n.labels || []).filter((l) => l.startsWith("module:"));
    if (mods.length > 0) out[n.name] = mods;
  }
  return out;
}

function moduleLabelToEntry(label: string): { importPath: string; version: string } | null {
  const s = label.replace(/^module:/, "");
  const at = s.lastIndexOf("@");
  if (at <= 0) return null;
  return { importPath: s.slice(0, at), version: s.slice(at + 1) };
}

async function computeEntries(repoRoot: string): Promise<Entry[]> {
  const auto = await readAutoMap(repoRoot);
  const graphMods = await loadGraph(repoRoot);
  const seen = new Set<string>();
  const entries: Entry[] = [];
  for (const [target, providers] of Object.entries(auto)) {
    const mods = graphMods[target] || [];
    const firstMod = mods.map(moduleLabelToEntry).find(Boolean);
    if (!firstMod) continue;
    for (const prov of providers) {
      if (!prov.startsWith("//third_party/providers:")) continue;
      const name = prov.split(":")[1];
      if (seen.has(name)) continue;
      seen.add(name);
      entries.push({ name, importPath: firstMod.importPath, version: firstMod.version });
    }
  }
  return entries.sort((a, b) => a.name.localeCompare(b.name));
}

async function copyFromGoModCache(repoRoot: string, importPath: string, version: string) {
  let gomodcache = String(process.env.GOMODCACHE || "").trim();
  if (!gomodcache) {
    try {
      const { stdout } = await $({ stdio: "pipe" })`go env GOMODCACHE`;
      gomodcache = String(stdout || "").trim();
    } catch {}
  }
  if (!gomodcache) return false;
  const origin = path.join(gomodcache, `${importPath}@${version}`);
  const dst = path.join(repoRoot, "third_party", "go", ...importPath.split("/"));
  if (!(await fs.pathExists(origin))) return false;
  await fs.mkdirp(dst);
  const files = await fs.readdir(origin).catch(() => [] as string[]);
  let copied = 0;
  for (const f of files) {
    if (f.endsWith(".go") && !f.endsWith("_test.go")) {
      await fs.copy(path.join(origin, f), path.join(dst, f)).catch(() => {});
      copied++;
    }
  }
  return copied > 0;
}

async function discoverLocalGoImportPaths(
  repoRoot: string,
): Promise<Array<{ importPath: string; srcDir: string }>> {
  const libsDir = path.join(repoRoot, "libs");
  const out: Array<{ importPath: string; srcDir: string }> = [];
  if (!(await fs.pathExists(libsDir))) return out;
  const libs = await fs.readdir(libsDir).catch(() => [] as string[]);
  for (const lib of libs) {
    const base = path.join(libsDir, lib);
    const targets = path.join(base, "TARGETS");
    const gomod = path.join(base, "go.mod");
    if (!(await fs.pathExists(gomod))) continue;
    const modTxt = await fs.readFile(gomod, "utf8").catch(() => "");
    const modMatch = modTxt.match(/^module\s+([^\s]+)\s*$/m);
    const modulePath = modMatch ? modMatch[1] : "";
    let importPath = "";
    if (await fs.pathExists(targets)) {
      const t = await fs.readFile(targets, "utf8");
      const m = t.match(/importpath\s*=\s*"([^"]+)"/);
      if (m) importPath = m[1];
    }
    if (!importPath && modulePath) {
      // Fallback to conventional path: module/pkg/<lib>
      importPath = `${modulePath}/pkg/${lib}`;
    }
    // Guess src directory by tail matching of import path
    const tail = importPath.split("/").slice(-2).join(path.sep);
    const candidate = path.join(base, tail);
    let srcDir = candidate;
    if (!(await fs.pathExists(srcDir))) {
      const alt = path.join(base, "pkg", lib);
      if (await fs.pathExists(alt)) srcDir = alt;
    }
    if (importPath && (await fs.pathExists(srcDir))) {
      out.push({ importPath, srcDir });
    }
  }
  return out;
}

async function copyLocalModuleSources(repoRoot: string, imp: string, srcDir: string) {
  const dst = path.join(repoRoot, "third_party", "go", ...imp.split("/"));
  await fs.mkdirp(dst);
  const files = await fs.readdir(srcDir).catch(() => [] as string[]);
  for (const f of files) {
    if (f.endsWith(".go") && !f.endsWith("_test.go")) {
      await fs.copy(path.join(srcDir, f), path.join(dst, f)).catch(() => {});
    }
  }
}

function renderTargets(
  entries: Entry[],
  localModules: Array<{ importPath: string; srcDir: string }>,
): string {
  const header = ['load("//go:defs.bzl", "nix_go_third_party_library")', ""].join("\n");
  const thirdParty = entries
    .map((e) => {
      return [
        `nix_go_third_party_library(`,
        `    name = "${e.name}",`,
        `    import_path = "${e.importPath}",`,
        `    srcs = ["${e.importPath}/**/*.go"],`,
        `    visibility = ["PUBLIC"],`,
        `)`,
        "",
      ].join("\n");
    })
    .join("\n");
  const locals = localModules
    .map(({ importPath }) => {
      const name = `local_${importPath.replace(/[\/_\.\-]/g, "_")}`;
      return [
        `nix_go_third_party_library(`,
        `    name = "${name}",`,
        `    import_path = "${importPath}",`,
        `    srcs = ["${importPath}/**/*.go"],`,
        `    visibility = ["PUBLIC"],`,
        `)`,
        "",
      ].join("\n");
    })
    .join("\n");
  const body = [thirdParty, locals].filter(Boolean).join("\n");
  return header + (body ? "\n" + body : "\n");
}

async function main() {
  const repoRoot = process.cwd();
  const entries = await computeEntries(repoRoot);
  console.log(`[sync-go-mods] third-party entries: ${entries.length}`);
  for (const e of entries) {
    await copyFromGoModCache(repoRoot, e.importPath, e.version).catch(() => {});
  }
  const localModules = await discoverLocalGoImportPaths(repoRoot);
  console.log(
    `[sync-go-mods] local modules discovered: ${localModules.map((l) => l.importPath).join(", ")}`,
  );
  for (const lm of localModules) {
    await copyLocalModuleSources(repoRoot, lm.importPath, lm.srcDir).catch(() => {});
  }
  await fs.mkdirp(path.join(repoRoot, "third_party", "go"));
  const outFile = path.join(repoRoot, "third_party", "go", "TARGETS");
  const txt = renderTargets(entries, localModules);
  await fs.writeFile(outFile, txt, "utf8");
  console.log(`[sync-go-mods] wrote ${outFile}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
