HEAVY_FANOUT_TESTS = {
    "build-tools/tools/tests/dev/nix-gaps.parity-and-hermeticity.test.ts": True,
    "build-tools/tools/tests/dev/runnable-commands.selected-fast-path.test.ts": True,
    "build-tools/tools/tests/dev/update-command.launcher.integration.test.ts": True,
    "build-tools/tools/tests/dev/update-command.launcher-tool-authority-conflict.integration.test.ts": True,
    "build-tools/tools/tests/dev/update-command.launcher-upgrade-languages.integration.test.ts": True,
    "build-tools/tools/tests/dev/update-command.launcher-upgrade-pnpm.integration.test.ts": True,
    "build-tools/tools/tests/node/node.wasm-inline-module.instantiate.test.ts": True,
    "build-tools/tools/tests/rust/rust.extensions.remote-cache-materialization.test.ts": True,
    "build-tools/tools/tests/rust/rust.node-consumers.stage-native-addon.test.ts": True,
    "build-tools/tools/tests/rust/rust.source-selection.identity-parity.test.ts": True,
    "build-tools/tools/tests/rust/rust.tauri-dependency-patch-identity.test.ts": True,
    "build-tools/tools/tests/rust/rust.tauri-input-invalidation.behavior.test.ts": True,
    "build-tools/tools/tests/rust/rust.tauri-input-invalidation.declared-inputs-2.behavior.test.ts": True,
    "build-tools/tools/tests/rust/rust.tauri-input-invalidation.declared-inputs-3.behavior.test.ts": True,
    "build-tools/tools/tests/rust/rust.tauri-input-invalidation.workspace-control.behavior.test.ts": True,
    "build-tools/tools/tests/rust/rust.wasm-wasi.artifacts.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp-ssr-vite.runnable-contracts.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.wasm-runtime-authority.contract.test.ts": True,
}
