RESOURCE_LIMITED_TESTS = {
    "build-tools/tools/tests/macro/node_macro.nix_runner_smoketest.test.ts": True,
    "build-tools/tools/tests/nix/node-test.no-tests.passes.test.ts": True,
    "build-tools/tools/tests/node/node.asset-stage.webapp-stages-wasm.test.ts": True,
    "build-tools/tools/tests/node/node.wasm-inline-module.instantiate.test.ts": True,
    "build-tools/tools/tests/planner/planner-dev-overrides.go.log.present.test.ts": True,
    "build-tools/tools/tests/scaffolding/go-app.auto-wires-go-tests.test.ts": True,
    "build-tools/tools/tests/scaffolding/go-cli.simple-patched-uuid.runtime.test.ts": True,
    "build-tools/tools/tests/scaffolding/go-lib.auto-wires-go-tests.test.ts": True,
    "build-tools/tools/tests/scaffolding/node-cli.scaffold-lockfile.present.test.ts": True,
    "build-tools/tools/tests/scaffolding/partial-clone.discover-and-build.test.ts": True,
    "build-tools/tools/tests/scaffolding/provider-wiring.scaffold-patch.test.ts": True,
    "build-tools/tools/tests/scaffolding/scaf-new.ts.wasm-linking-app.scaffold-and-build.test.ts": True,
    "build-tools/tools/tests/scaffolding/scaf-go-test.cli.auto-wires.test.ts": True,
    "build-tools/tools/tests/scaffolding/scaf-go-test.lib.auto-wires.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp-ssr-vite.runnable-contracts.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp-ssr.next-contracts.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp-ssr.scaffold-contract-and-runtime-smoke.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp-static-pwa.runtime-offline.contract.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.multi-module.manifest.contract.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.scaffold-and-build.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.wasm-runtime-authority.contract.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.wasm-runtime-authority.ssr-next.contract.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.wasm-runtime-authority.static.contract.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.zero-wasm-default.ssr-next.contract.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.zero-wasm-default.ssr-vite.contract.test.ts": True,
    "build-tools/tools/tests/scaffolding/webapp.zero-wasm-default.static.contract.test.ts": True,
}
