import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import * as fsp from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { findViberootsRoot, immutableViberootsInput } from "./registry-extension-fixture";

const execFileAsync = promisify(execFile);

export async function assertGeneratedRegistryExtensionContract(): Promise<void> {
  const workspace = await fsp.realpath(
    await fsp.mkdtemp(path.join(os.tmpdir(), "viberoots-registry-extension-")),
  );
  try {
    const viberootsRoot = await findViberootsRoot();
    const flakeInput = await immutableViberootsInput(viberootsRoot);
    const { stdout, stderr } = await execFileAsync(
      path.join(viberootsRoot, "build-tools", "tools", "bin", "viberoots"),
      [
        "init-consumer",
        "--workspace-root",
        workspace,
        "--workspace-name",
        "registry-extension",
        "--viberoots-url",
        `path:${flakeInput}`,
        "--source",
        viberootsRoot,
        "--no-lock",
        "--no-direnv",
      ],
      { cwd: workspace, env: { ...process.env, NO_DEV_SHELL: "1" } },
    );
    assert.match(stdout, /ok\s+workspace initialized/);
    assert.equal(stderr, "");
    const hiddenFlake = await fsp.readFile(
      path.join(workspace, ".viberoots", "workspace", "flake.nix"),
      "utf8",
    );
    assert.doesNotMatch(hiddenFlake, /builtins\.toPath root/);
    assert.match(hiddenFlake, /workspaceSrc = \.\.\/\.\.;/);
    assert.doesNotMatch(hiddenFlake, /builtins\.getEnv "WORKSPACE_ROOT"/);
    assert.match(hiddenFlake, /nixpkgs_23_11\.url = "github:NixOS\/nixpkgs\/nixos-23\.11"/);
    assert.match(hiddenFlake, /registryExtensionPath = \.\/nixpkgs-source-registry-extension\.nix/);
    assert.match(hiddenFlake, /import registryExtensionPath \{ inherit inputs; \}/);
    assert.match(hiddenFlake, /inherit nixpkgsRegistryExtension/);

    const targets = await fsp.readFile(
      path.join(workspace, ".viberoots", "workspace", "TARGETS"),
      "utf8",
    );
    assert.match(targets, /generated by viberoots\/init-consumer/);
    assert.match(targets, /load\("@prelude\/\/:rules\.bzl", "export_file"\)/);
    assert.match(targets, /name = "flake\.nix",\n    src = "flake\.nix"/);
    assert.match(targets, /name = "flake\.lock",\n    src = "flake\.lock"/);
    assert.doesNotMatch(targets, /name = "node-modules\.hashes\.json"/);
    const projectsConfigTargets = await fsp.readFile(
      path.join(workspace, "projects", "config", "TARGETS"),
      "utf8",
    );
    assert.match(
      projectsConfigTargets,
      /name = "node-modules\.hashes\.json",\n    src = "node-modules\.hashes\.json"/,
    );
    assert.match(targets, /name = "nixpkgs-source-registry-extension"/);
    assert.match(targets, /src = "nixpkgs-source-registry-extension\.nix"/);
    assert.equal(
      await fsp.readFile(
        path.join(workspace, ".viberoots", "workspace", "nixpkgs-source-registry-extension.nix"),
        "utf8",
      ),
      "{ inputs }: { profiles = { }; }\n",
    );
    assert.equal(
      await fsp.readFile(
        path.join(workspace, "projects", "config", "node-modules.hashes.json"),
        "utf8",
      ),
      "{}\n",
    );
    const rootFlake = await fsp.readFile(path.join(workspace, "flake.nix"), "utf8");
    assert.match(rootFlake, /nixpkgs_23_11\.url = "github:NixOS\/nixpkgs\/nixos-23\.11"/);
    assert.match(
      rootFlake,
      /registryExtensionPath = \.\/\.viberoots\/workspace\/nixpkgs-source-registry-extension\.nix/,
    );
    assert.match(rootFlake, /inherit nixpkgsRegistryExtension/);
  } finally {
    await fsp.rm(workspace, { recursive: true, force: true });
  }
}
