#!/usr/bin/env zx-wrapper
import {
  MOBILE_APP_COMPONENT_KIND,
  SERVICE_COMPONENT_KIND,
  SSR_WEBAPP_COMPONENT_KIND,
  THIRD_PARTY_SERVICE_COMPONENT_KIND,
  type DeploymentComponentKind,
} from "../deployment-component-kinds";
import {
  APP_STORE_CONNECT_PROVIDER,
  CLOUDFLARE_PAGES_PROVIDER,
  CLOUDFLARE_CONTAINERS_PROVIDER,
  GOOGLE_PLAY_PROVIDER,
  KUBERNETES_PROVIDER,
  NIXOS_SHARED_HOST_PROVIDER,
  S3_STATIC_PROVIDER,
} from "../deployment-provider-targets";
import { VERCEL_PROVIDER } from "../vercel-provider-target";
import { APP_STORE_CONNECT_PROVIDER_CAPABILITY } from "./app-store-connect";
import { CLOUDFLARE_PAGES_PROVIDER_CAPABILITY } from "./cloudflare-pages";
import { CLOUDFLARE_CONTAINERS_PROVIDER_CAPABILITY } from "./cloudflare-containers";
import { GOOGLE_PLAY_PROVIDER_CAPABILITY } from "./google-play";
import { KUBERNETES_PROVIDER_CAPABILITY } from "./kubernetes";
import { NIXOS_SHARED_HOST_PROVIDER_CAPABILITY } from "./nixos-shared-host";
import { S3_STATIC_PROVIDER_CAPABILITY } from "./s3-static";
import { VERCEL_PROVIDER_CAPABILITY } from "./vercel";
import type { DeploymentProviderCapability } from "./types";
import { validateProviderCapabilityRegistry } from "./validate";

export const REVIEWED_PROVIDER_IDS = [
  NIXOS_SHARED_HOST_PROVIDER,
  APP_STORE_CONNECT_PROVIDER,
  GOOGLE_PLAY_PROVIDER,
  CLOUDFLARE_PAGES_PROVIDER,
  CLOUDFLARE_CONTAINERS_PROVIDER,
  S3_STATIC_PROVIDER,
  KUBERNETES_PROVIDER,
  VERCEL_PROVIDER,
] as const;

export const REVIEWED_PROVIDER_CAPABILITIES_BY_PROVIDER: Record<
  (typeof REVIEWED_PROVIDER_IDS)[number],
  DeploymentProviderCapability
> = {
  [NIXOS_SHARED_HOST_PROVIDER]: NIXOS_SHARED_HOST_PROVIDER_CAPABILITY,
  [APP_STORE_CONNECT_PROVIDER]: APP_STORE_CONNECT_PROVIDER_CAPABILITY,
  [GOOGLE_PLAY_PROVIDER]: GOOGLE_PLAY_PROVIDER_CAPABILITY,
  [CLOUDFLARE_PAGES_PROVIDER]: CLOUDFLARE_PAGES_PROVIDER_CAPABILITY,
  [CLOUDFLARE_CONTAINERS_PROVIDER]: CLOUDFLARE_CONTAINERS_PROVIDER_CAPABILITY,
  [S3_STATIC_PROVIDER]: S3_STATIC_PROVIDER_CAPABILITY,
  [KUBERNETES_PROVIDER]: KUBERNETES_PROVIDER_CAPABILITY,
  [VERCEL_PROVIDER]: VERCEL_PROVIDER_CAPABILITY,
};

validateProviderCapabilityRegistry(
  REVIEWED_PROVIDER_CAPABILITIES_BY_PROVIDER as Record<string, DeploymentProviderCapability>,
);

export const REVIEWED_PROVIDER_CAPABILITIES = REVIEWED_PROVIDER_IDS.map(
  (provider) => REVIEWED_PROVIDER_CAPABILITIES_BY_PROVIDER[provider],
);

export const REVIEWED_NON_STATIC_COMPONENT_KINDS: DeploymentComponentKind[] = [
  SSR_WEBAPP_COMPONENT_KIND,
  MOBILE_APP_COMPONENT_KIND,
  SERVICE_COMPONENT_KIND,
  THIRD_PARTY_SERVICE_COMPONENT_KIND,
];
