import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { buildSolverPreparedInput } from "../src/game/solver/candidate-generation";
import {
  canonicalPlacementSignature,
  scoreInterestingness,
} from "../src/game/solver/interestingness";
import { createSolverRequestFromGameState } from "../src/game/solver/solver";
import type { SolverPlacement } from "../src/game/solver/solver-types";
import { runSolverSearchInWasm } from "../src/game/solver/wasm-runtime";
import { createInitialGameState } from "../src/game/state";

type Candidate = {
  signature: string;
  score: number;
  placements: readonly SolverPlacement[];
};

const TARGET_POOL_SIZE = 100;
const TARGET_EVALUATED_SOLUTIONS = 100_000;
const MAX_SEEDS = 10_000;
const LOG_INTERVAL_SEEDS = 20;

const SEARCH_MAX_NODE_EXPANSIONS = 250_000;
const SEARCH_MAX_WALL_CLOCK_MS = 1_000;
const SEARCH_SOLUTION_POOL_SIZE = 256;

function compareCandidates(left: Candidate, right: Candidate): number {
  if (left.score !== right.score) {
    return left.score - right.score;
  }
  return left.signature.localeCompare(right.signature);
}

function mapCandidatesToPlacements(
  candidateIndices: Int32Array,
  candidates: ReturnType<typeof buildSolverPreparedInput>["candidates"],
): SolverPlacement[] {
  const placements: SolverPlacement[] = [];
  for (const candidateIndex of candidateIndices) {
    const candidate = candidates[candidateIndex];
    if (!candidate) {
      continue;
    }
    placements.push({
      pieceId: candidate.pieceId,
      transform: candidate.transform,
      position: candidate.position,
    });
  }
  return placements;
}

function considerTopCandidate(top: Candidate[], candidate: Candidate): void {
  if (top.length < TARGET_POOL_SIZE) {
    top.push(candidate);
    top.sort(compareCandidates);
    return;
  }
  const lowest = top[0];
  if (!lowest) {
    return;
  }
  if (compareCandidates(candidate, lowest) <= 0) {
    return;
  }
  top[0] = candidate;
  top.sort(compareCandidates);
}

function formatSolutionModule(candidates: readonly Candidate[]): string {
  const lines: string[] = [];
  lines.push('import type { SolverPlacement } from "./solver-types";');
  lines.push("");
  lines.push("export type StaticInterestingSolution = {");
  lines.push("  signature: string;");
  lines.push("  score: number;");
  lines.push("  placements: readonly SolverPlacement[];");
  lines.push("};");
  lines.push("");
  lines.push("// Generated by scripts/generate-interesting-solution-pool.ts.");
  lines.push("export const STATIC_INTERESTING_SOLUTIONS: readonly StaticInterestingSolution[] = [");
  for (const candidate of candidates) {
    lines.push("  {");
    lines.push(`    signature: ${JSON.stringify(candidate.signature)},`);
    lines.push(`    score: ${candidate.score.toFixed(6)},`);
    lines.push("    placements: [");
    for (const placement of candidate.placements) {
      lines.push(
        `      { pieceId: ${JSON.stringify(placement.pieceId)}, transform: { rotation: ${placement.transform.rotation}, flipped: ${placement.transform.flipped} }, position: { x: ${placement.position.x}, y: ${placement.position.y} } },`,
      );
    }
    lines.push("    ],");
    lines.push("  },");
  }
  lines.push("];\n");
  return lines.join("\n");
}

async function main(): Promise<void> {
  const state = createInitialGameState();
  const seenSignatures = new Set<string>();
  const top: Candidate[] = [];
  let evaluatedSolutions = 0;
  let solvedSeeds = 0;

  for (let seed = 1; seed <= MAX_SEEDS; seed += 1) {
    if (evaluatedSolutions >= TARGET_EVALUATED_SOLUTIONS) {
      break;
    }

    const request = createSolverRequestFromGameState(
      state,
      SEARCH_MAX_NODE_EXPANSIONS,
      SEARCH_MAX_WALL_CLOCK_MS,
      {
        randomSeed: seed,
        solutionPoolSize: SEARCH_SOLUTION_POOL_SIZE,
        selectionWindowSize: 32,
        interestingnessThreshold: 0,
      },
    );

    const prepared = buildSolverPreparedInput(request);
    const wasmResult = await runSolverSearchInWasm(
      prepared,
      request.maxNodeExpansions,
      request.maxWallClockMs,
      request.solutionPoolSize ?? SEARCH_SOLUTION_POOL_SIZE,
    );

    if (wasmResult.statusCode === 1 && wasmResult.solutions.length > 0) {
      solvedSeeds += 1;
    }

    for (const solution of wasmResult.solutions) {
      evaluatedSolutions += 1;
      const placements = mapCandidatesToPlacements(solution.candidateIndices, prepared.candidates);
      const signature = canonicalPlacementSignature(placements);
      if (seenSignatures.has(signature)) {
        continue;
      }
      seenSignatures.add(signature);
      const score = scoreInterestingness({
        boardColumns: state.board.size.columns,
        boardRows: state.board.size.rows,
        pieceCatalog: state.pieceCatalog,
        placements,
      }).score;
      considerTopCandidate(top, {
        signature,
        score,
        placements,
      });
    }

    if (seed % LOG_INTERVAL_SEEDS === 0) {
      const minTopScore = top[0]?.score ?? 0;
      const maxTopScore = top[top.length - 1]?.score ?? 0;
      console.log(
        `[interesting-pool] seeds=${seed} solvedSeeds=${solvedSeeds} evaluated=${evaluatedSolutions} unique=${seenSignatures.size} topRange=${minTopScore.toFixed(6)}..${maxTopScore.toFixed(6)}`,
      );
    }
  }

  if (evaluatedSolutions < TARGET_EVALUATED_SOLUTIONS) {
    throw new Error(
      `insufficient deep-search coverage: evaluated=${evaluatedSolutions}, required=${TARGET_EVALUATED_SOLUTIONS}`,
    );
  }

  if (top.length < TARGET_POOL_SIZE) {
    throw new Error(`unable to collect top ${TARGET_POOL_SIZE}; collected ${top.length}`);
  }

  const selected = [...top].sort((left, right) => {
    if (right.score !== left.score) {
      return right.score - left.score;
    }
    return left.signature.localeCompare(right.signature);
  });

  const outputPath = resolve(process.cwd(), "src/game/solver/static-interesting-solutions.ts");
  await writeFile(outputPath, formatSolutionModule(selected), "utf8");

  console.log(
    `[interesting-pool] wrote ${selected.length} solutions after evaluating ${evaluatedSolutions} solved candidates (best=${selected[0]!.score.toFixed(6)} worst=${selected[selected.length - 1]!.score.toFixed(6)})`,
  );
}

await main();
