#!/usr/bin/env zx-wrapper
import * as fsp from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { runInTemp, workspaceFlakeRef } from "../lib/test-helpers";

test("provider wiring present only on affected target after patch", async () => {
  await runInTemp("prov-wiring", async (_tmp, _$) => {
    const $ = _$({ stdio: "pipe" });
    // Use .buckconfig and toolchains generated by runInTemp
    await $`scaf new go lib demo-lib --yes --path=projects/libs/demo-lib`;
    if (
      !(await fsp.stat(path.join(_tmp, "projects", "libs", "demo-lib", "go.mod")).catch(() => null))
    ) {
      return;
    }
    const moduleDir = path.join(_tmp, "projects", "libs", "demo-lib");
    await $({ cwd: moduleDir })`go mod edit -require golang.org/x/text@v0.14.0`;
    await fsp.mkdir(path.join(moduleDir, "pkg", "dependency"), { recursive: true });
    await fsp.writeFile(
      path.join(moduleDir, "pkg", "dependency", "keep.go"),
      'package dependency\n\nimport _ "golang.org/x/text/language"\n',
      "utf8",
    );
    // Create a dummy patch for that module version
    await $`/usr/bin/env bash --noprofile --norc -lc 'mkdir -p patches/go && touch patches/go/golang.org__x__text@v0.14.0.patch'`;
    await $`viberoots/build-tools/tools/bin/u`;

    // Run read-only glue and build via Nix graph-generator.
    await $`viberoots/build-tools/tools/dev/install-deps.ts --glue-only`;
    const { stdout } = await $({
      cwd: _tmp,
      stdio: "pipe",
      env: {
        ...process.env,
        BUCK_GRAPH_JSON: path.join(_tmp, ".viberoots", "workspace", "buck", "graph.json"),
      },
    })`nix build --impure ${`path:${await workspaceFlakeRef(_tmp)}#graph-generator`} --no-link --print-out-paths --accept-flake-config`;
    const outPath =
      String(stdout || "")
        .trim()
        .split("\n")
        .filter(Boolean)
        .pop() || "";
    await $`test -f .viberoots/workspace/providers/auto_map.bzl`;
  });
});
