#!/usr/bin/env zx-wrapper
import assert from "node:assert/strict";
import { test } from "node:test";
import { runCloudProviderCapabilityHook } from "../../deployments/cloud-control-provider-capability-hooks";
import { renderCloudControlSetupBundle } from "../../deployments/cloud-control-setup-render";
import { validateProviderCapabilityEvidence } from "../../deployments/cloud-control-setup-validate";
import type { CloudControlSetupInput } from "../../deployments/cloud-control-setup-types";
import { privateLinkAwsTopology } from "./cloud-control-cutover-fixture";

const DIGEST_REF =
  "registry.example.com/platform/deployment-control-plane@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const DIGEST = `sha256:${"a".repeat(64)}`;
const BUILD_IDENTITY = `nix-source-${"b".repeat(64)}`;

test("provider-capability hook evidence is required before protected readiness", async () => {
  const capabilities = renderCloudControlSetupBundle(baseInput()).capabilities;
  assert.match(
    validateProviderCapabilityEvidence(capabilities, {}).join("\n"),
    /aws-ec2-control-plane-host: protected\/shared readiness requires hook evidence/,
  );
  const staticRefs = Object.fromEntries(
    capabilities.map((capability) => [capability.id, [...capability.auditEvidence]]),
  );
  assert.match(
    validateProviderCapabilityEvidence(capabilities, staticRefs).join("\n"),
    /protected\/shared readiness requires hook evidence/,
  );
  const completeEvidence = await hookEvidenceFor(capabilities);
  assert.deepEqual(validateProviderCapabilityEvidence(capabilities, completeEvidence), []);
  const incompleteEvidence = {
    ...completeEvidence,
    "aws-s3-artifact-store": {
      ...(completeEvidence["aws-s3-artifact-store"] as Record<string, unknown>),
      auditEvidence: ["preview output digest"],
    },
  };
  assert.match(
    validateProviderCapabilityEvidence(capabilities, incompleteEvidence).join("\n"),
    /aws-s3-artifact-store: missing evidence "s3-apply-digest"/,
  );
});

test("placeholder declarations and raw evidence cannot mark readiness", () => {
  const capabilities = renderCloudControlSetupBundle(baseInput()).capabilities;
  const placeholder = {
    ...capabilities[0],
    targetIdentity: "aws-ec2-control-plane-host:<reviewed-account-or-project>",
  };
  assert.match(
    validateProviderCapabilityEvidence(
      [placeholder, ...capabilities.slice(1)],
      Object.fromEntries(
        capabilities.map((capability) => [
          capability.id,
          { capabilityId: capability.id, auditEvidence: capability.auditEvidence },
        ]),
      ),
    ).join("\n"),
    /aws-ec2-control-plane-host: declaration must match the concrete capability catalog/,
  );
  assert.match(
    validateProviderCapabilityEvidence(capabilities, {
      [capabilities[0].id]: {
        capabilityId: capabilities[0].id,
        source: "dashboard-only",
        auditEvidence: capabilities[0].auditEvidence,
      },
    }).join("\n"),
    /provider-capability evidence must be generated by executable hook/,
  );
});

async function hookEvidenceFor(capabilities: Array<{ id: string }>) {
  const foundation = privateLinkAwsTopology().foundation;
  return Object.fromEntries(
    await Promise.all(
      capabilities.map(async (capability) => [
        capability.id,
        await runCloudProviderCapabilityHook({
          capabilityId: capability.id,
          phase: "evidence",
          deploymentLabel: "//deployments:staging",
          ...(capability.id === "aws-network-foundation" ||
          capability.id === "aws-s3-artifact-store"
            ? { awsFoundationInspection: foundation }
            : {}),
        }),
      ]),
    ),
  );
}

function baseInput(): CloudControlSetupInput {
  return {
    outDir: "unused",
    mode: "compose-podman",
    image: DIGEST_REF,
    expectedImageBuildIdentity: BUILD_IDENTITY,
    imagePublication: {
      image: DIGEST_REF,
      sourceRevision: "source-capability",
      imageBuildIdentity: BUILD_IDENTITY,
      digest: DIGEST,
      inspectedDigest: DIGEST,
      tag: "registry.example.com/platform/deployment-control-plane:source-capability",
    },
    instanceId: "cloud-staging",
    publicUrl: "https://deploy.example.test",
    artifactBucket: "deployment-control-plane-artifacts",
    artifactRegion: "us-east-1",
    artifactBackend: "aws-s3",
    artifactBackendEvidence: "",
    deploymentIds: ["pleomino-staging"],
    reviewedSourceMode: "ssh",
    authCallbackHost: "deploy-auth.example.test",
    authCallbackPath: "/oidc/callback",
    serviceReplicas: 1,
    workerReplicas: 2,
    dryRun: false,
    awsTopology: privateLinkAwsTopology(),
  };
}
