#!/usr/bin/env zx-wrapper
import assert from "node:assert/strict";
import * as fsp from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { runDeploymentControlPlaneCommand } from "../../deployments/deployment-control-plane";
import { writeCloudControlSetupBundle } from "../../deployments/cloud-control-setup";
import { runInTemp } from "../lib/test-helpers";
import { privateLinkAwsTopology } from "./cloud-control-cutover-fixture";
import { withControlPlaneArgv } from "./control-plane-process-entrypoints.helpers";
import { ecrRegistryProfile } from "./control-plane-registry-profile.fixture";

const DIGEST = `sha256:${"d".repeat(64)}`;
const IMAGE = `123456789012.dkr.ecr.us-east-1.amazonaws.com/deployment-control-plane@${DIGEST}`;
const BUILD_IDENTITY = `nix-source-${"e".repeat(64)}`;

test("production AWS setup rejects generated evidence without registry profile", async () => {
  await runInTemp("control-plane-setup-missing-registry-profile", async (tmp) => {
    const evidence = path.join(tmp, "image-publication.json");
    await fsp.writeFile(
      evidence,
      JSON.stringify({ ...generatedEvidence(), registryProfile: undefined }, null, 2),
      "utf8",
    );
    await assert.rejects(
      () =>
        withControlPlaneArgv(
          ["setup", "--host-mode", "aws-ec2", "--image-publication-evidence", evidence],
          runDeploymentControlPlaneCommand,
        ),
      /requires registry profile evidence/,
    );
  });
});

test("lower-level AWS setup rejects non-generated registry evidence", async () => {
  await runInTemp("control-plane-setup-lower-level-direct-evidence", async (tmp) => {
    await assert.rejects(
      () =>
        writeCloudControlSetupBundle({
          outDir: path.join(tmp, "profile"),
          mode: "aws-ec2",
          image: IMAGE,
          expectedImageBuildIdentity: BUILD_IDENTITY,
          imagePublication: {
            image: IMAGE,
            sourceRevision: "source-reviewed",
            imageBuildIdentity: BUILD_IDENTITY,
            digest: DIGEST,
            inspectedDigest: DIGEST,
            tag: "123456789012.dkr.ecr.us-east-1.amazonaws.com/deployment-control-plane:source-reviewed",
          },
          instanceId: "cloud-review",
          publicUrl: "https://deploy.example.test",
          artifactBucket: "deployment-control-plane-artifacts",
          artifactRegion: "us-east-1",
          artifactBackend: "aws-s3",
          artifactBackendEvidence: "",
          deploymentIds: ["pleomino-staging"],
          reviewedSourceMode: "ssh",
          authCallbackHost: "deploy-auth.example.test",
          authCallbackPath: "/oidc/callback",
          serviceReplicas: 1,
          workerReplicas: 2,
          dryRun: false,
          awsTopology: privateLinkAwsTopology(),
        }),
      /must be generated by image-publication/,
    );
  });
});

test("production AWS setup rejects registry pull proof for the wrong digest", async () => {
  await runInTemp("control-plane-setup-wrong-pull-proof", async (tmp) => {
    const evidence = path.join(tmp, "image-publication.json");
    await fsp.writeFile(evidence, JSON.stringify(wrongPullProofEvidence(), null, 2), "utf8");
    const topology = path.join(tmp, "aws-topology-evidence.json");
    await fsp.writeFile(topology, JSON.stringify(privateLinkAwsTopology()), "utf8");
    await assert.rejects(
      () =>
        withControlPlaneArgv(
          [
            "setup",
            "--host-mode",
            "aws-ec2",
            "--image-publication-evidence",
            evidence,
            "--aws-topology-evidence",
            topology,
          ],
          runDeploymentControlPlaneCommand,
        ),
      /runtime pull proof digest does not match/,
    );
  });
});

function generatedEvidence() {
  return {
    schemaVersion: "cloud-control-image-publication@1",
    image: IMAGE,
    sourceRevision: "source-reviewed",
    imageBuildIdentity: BUILD_IDENTITY,
    digest: DIGEST,
    inspectedDigest: DIGEST,
    tag: "123456789012.dkr.ecr.us-east-1.amazonaws.com/deployment-control-plane:source-reviewed",
    evidenceSource: "generated-command",
    registryProfile: ecrRegistryProfile(),
  };
}

function wrongPullProofEvidence() {
  return {
    ...generatedEvidence(),
    registryProfile: {
      ...ecrRegistryProfile(),
      runtimePull: {
        ...ecrRegistryProfile().runtimePull,
        proof: {
          ...ecrRegistryProfile().runtimePull.proof,
          digest: `sha256:${"f".repeat(64)}`,
        },
      },
    },
  };
}
