REVIEWED_DEPLOYMENT_TEST_OWNERSHIP = {
    "build-tools/tools/tests/deployments/cloudflare-containers.contract.test.ts": True, "build-tools/tools/tests/deployments/cloudflare-containers.routing-smoke.test.ts": True, "build-tools/tools/tests/deployments/cloudflare-containers.validation.test.ts": True, "build-tools/tools/tests/deployments/deployment-domain.labels.cquery.test.ts": True, "build-tools/tools/tests/deployments/deployment-domain.file-size-lint.test.ts": True, "build-tools/tools/tests/deployments/deployment-domain.taxonomy-drift.test.ts": True, "build-tools/tools/tests/deployments/deployment-family-composition.cquery.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-query-helpers.test.ts": True, "build-tools/tools/tests/deployments/deployment-docs.front-door-parity.test.ts": True, "build-tools/tools/tests/deployments/deployment-docs.infisical-mini-parity.test.ts": True, "build-tools/tools/tests/deployments/stale-environment-branch.enforcement.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.separated-roles.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.keycloak-claim-grant-mapping.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.admission-requirement-discovery.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.reviewed-source-snapshotting.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.governance-verification.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.auth-group-realm-wiring.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.admin-identity-workflows.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.remote-admin-flow.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.reviewed-remote-admin.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-service.hosted-token-enforcement.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-preview-cleanup.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-secret-fixture-docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.lane-governance.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.cli.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.check-mismatch.test.ts": True, "build-tools/tools/tests/deployments/deployment-admission.policy.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.trusted-reporters.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-boundary-checks.test.ts": True, "build-tools/tools/tests/deployments/deployment-infisical-final-guardrails.test.ts": True, "build-tools/tools/tests/deployments/deployment-infisical-front-door.e2e.test.ts": True, "build-tools/tools/tests/deployments/deployment-infisical-migration-replay.e2e.test.ts": True, "build-tools/tools/tests/deployments/deployment-infisical-worker-fixture.test.ts": True, "build-tools/tools/tests/deployments/deployment-readiness-gates.diagnostics-secret.test.ts": True, "build-tools/tools/tests/deployments/deployment-readiness-gates.phase0-access.fixture.ts": False, "build-tools/tools/tests/deployments/deployment-readiness-gates.phase0-access.test.ts": True, "build-tools/tools/tests/deployments/deployment-readiness-gates.test.ts": True, "build-tools/tools/tests/deployments/external-deployment-requirements.test.ts": True, "build-tools/tools/tests/deployments/github-app-requirements.cquery.test.ts": True, "build-tools/tools/tests/deployments/github-app-requirements.validation.test.ts": True, "build-tools/tools/tests/deployments/real-deployment-requirement-profiles.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.scoped-checks.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.prerequisites.helpers.ts": False,
    "build-tools/tools/tests/deployments/deployment-admission.prerequisites.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.supply-chain.replay.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admission.supply-chain.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-lane-governance.fixture.ts": False, "build-tools/tools/tests/deployments/deployment-lane-governance-defaults.fixture.ts": False, "build-tools/tools/tests/deployments/deployment-lane-governance-github.test.ts": True, "build-tools/tools/tests/deployments/deployment-lane-policy.gitops-schema.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-lane-governance.verify.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-component-kinds.contract.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.approval-grant.helpers.ts": False,
    "build-tools/tools/tests/deployments/deployment-control-plane.authz-idempotency.test.ts": True, "build-tools/tools/tests/deployments/deployment-ci-admission.authz.test.ts": True, "build-tools/tools/tests/deployments/deployment-ci-admission.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.authz-diagnostics.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.approval-grant.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.bootstrap.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.break-glass.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.observability.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.pending-approval.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.lock-and-queue.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.progressive-rollout.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.redaction.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.recovery.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.response-boundary.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.service-instance.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.status-format.test.ts": True, "build-tools/tools/tests/deployments/deployment-current-stage-state.backend.test.ts": True, "build-tools/tools/tests/deployments/deployment-current-stage-state.kubernetes.test.ts": True, "build-tools/tools/tests/deployments/deployment-current-stage-state.listing-audit.test.ts": True, "build-tools/tools/tests/deployments/deployment-stage-state-audit-chain.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.restore.kubernetes.test.ts": True, "build-tools/tools/tests/deployments/deployment-control-plane.restore.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.retention.policy.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-control-plane.admission-reporter-boundary.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.service.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.derived-grants.service.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.admin-groups-principal.service.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-auth-session.claim-mapping.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-keycloak.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-keycloak.realm-shape.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-keycloak.remote-profile.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-keycloak.remote-profile.helpers.ts": False,
    "build-tools/tools/tests/deployments/deployment-admin-keycloak.remote-profile.sync-reviewed-session.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-keycloak.remote-profile.grant-user-errors.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-keycloak.remote-ssh.command-assembly.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-infisical-check.test.ts": True, "build-tools/tools/tests/deployments/deployment-admin-infisical.fixture.ts": False, "build-tools/tools/tests/deployments/deployment-admin-infisical.test.ts": True, "build-tools/tools/tests/deployments/deployment-auth-diagnostics.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-admin-vault.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-browser-launch.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-cli-resolve.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-artifact-proof-keys.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-secret-admission-backend.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-deferred-worker-admission.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-infisical-cache.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-infisical-credentials.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-infisical-paths.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-infisical-redaction.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-infisical-replay.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-infisical.fixture.ts": False, "build-tools/tools/tests/deployments/deployment-secret-infisical.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-runtime.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-runtime-helpers.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-runtime-prepare.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-metadata.cquery.test.ts": True, "build-tools/tools/tests/deployments/deployment-secret-metadata.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-secret-vault-auth.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-secret-vault.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-credential-source.device.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-credential-source.pkce.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-credential-source.runtime.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-credential-source.selection.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-vault-bootstrap.docs.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-vault-bootstrap.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-vault-runtime.test.ts": True,
    "build-tools/tools/tests/deployments/deploy-vault-jwt.fail-closed.test.ts": True,
    "build-tools/tools/tests/deployments/deploy-vault-jwt.success.test.ts": True,
    "build-tools/tools/tests/deployments/deploy-vault-jwt.test-helpers.ts": False,
    "build-tools/tools/tests/deployments/deploy.admit-only.contract.test.ts": True,
    "build-tools/tools/tests/deployments/deploy.admission-requirements.contract.test.ts": True,
    "build-tools/tools/tests/deployments/deploy.front-door.contract.test.ts": True, "build-tools/tools/tests/deployments/deploy.front-door-readiness.test.ts": True,
    "build-tools/tools/tests/deployments/deploy.front-door.control-plane-operator.contract.test.ts": True, "build-tools/tools/tests/deployments/deploy.front-door.current-stage-state.test.ts": True,
    "build-tools/tools/tests/deployments/deploy.front-door.hosted-status-ux.test.ts": True,
    "build-tools/tools/tests/deployments/deploy.front-door.provider-target-identity.contract.test.ts": True, "build-tools/tools/tests/deployments/phase0-deployments.contract.test.ts": True, "build-tools/tools/tests/deployments/phase0-deployments.readiness-secrets.test.ts": True, "build-tools/tools/tests/deployments/phase0-deployments.smoke.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-from-changes.batch.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-from-changes.selection.test.ts": True, "build-tools/tools/tests/deployments/deployment-phase0-admission.test.ts": True, "build-tools/tools/tests/deployments/deployment-phase0-release.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-promotion-compatibility.test.ts": True, "build-tools/tools/tests/deployments/deployment-provider-promotion.stage-state.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-provider-capabilities.contract.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-provider-capabilities.runtime-parity.contract.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-prerequisites.validation.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-requirements.validation.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-retry-policy.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-runner-identities.replay.provenance.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-smoke-exception.validation.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-reviewed-source-provider-wiring.test.ts": True, "build-tools/tools/tests/deployments/deployment-source-ref-policy.test.ts": True, "build-tools/tools/tests/deployments/deployment-target-exceptions.validation.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-verify-scope.boundary.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-git-ref.fetch.test.ts": True,
    "build-tools/tools/tests/deployments/app-store-connect.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/app-store-connect.fixture.ts": False,
    "build-tools/tools/tests/deployments/app-store-connect.validation.test.ts": True,
    "build-tools/tools/tests/deployments/google-play.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/google-play.fixture.ts": False,
    "build-tools/tools/tests/deployments/google-play.validation.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.artifact-input.service.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.backend-recovery.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.contract.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.custom-domain.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.control-plane.service-errors.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.control-plane.service.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-targets.install.cloudflare.test.ts": True,
    "build-tools/tools/tests/deployments/deployment-targets.install.fragments.no-inherited-kill.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.deploy.e2e.test.ts": True, "build-tools/tools/tests/deployments/cloudflare-pages.infisical-admission-records.test.ts": True, "build-tools/tools/tests/deployments/cloudflare-pages.secret-runtime-lifecycle.helpers.ts": False, "build-tools/tools/tests/deployments/cloudflare-pages.secret-runtime-lifecycle.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages-static-smoke.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.publisher-error.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.timeout.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.extraction.from-targets.cquery.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.preview.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.preview-cleanup-secrets.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.project.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.preview.smoke-exception.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.preview.guardrails.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.promotion.helpers.ts": False,
    "build-tools/tools/tests/deployments/cloudflare-pages.rebuild-per-stage.promotion.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.promotion.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.promotion.guardrails.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.publisher.config-drift.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.records.contract.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.rollback.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.rollback.guardrails.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.sprinkle-ref.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.status-profile.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.vault-direct.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.target-transition.test.ts": True,
    "build-tools/tools/tests/deployments/cloudflare-pages.validation.test.ts": True,
    "build-tools/tools/tests/deployments/kubernetes.artifacts.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.contract.test.ts": True,
    "build-tools/tools/tests/deployments/kubernetes.control-plane.reviewed-source.test.ts": True,
    "build-tools/tools/tests/deployments/kubernetes.control-plane.service.test.ts": True,
    "build-tools/tools/tests/deployments/kubernetes.deploy.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/kubernetes.deploy.smoke-failure.test.ts": True,
    "build-tools/tools/tests/deployments/kubernetes.fake-helm.ts": False,
    "build-tools/tools/tests/deployments/kubernetes.fixture.ts": False, "build-tools/tools/tests/deployments/kubernetes.macro-extraction.cquery.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.opentofu-apply.deploy.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.opentofu-apply-plan-contract.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.opentofu-apply.guard.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.opentofu-apply.helpers.ts": False, "build-tools/tools/tests/deployments/kubernetes.opentofu-apply.integration.helpers.ts": False, "build-tools/tools/tests/deployments/kubernetes.opentofu-apply.integration.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.opentofu-apply.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.opentofu-stack.test.ts": True, "build-tools/tools/tests/deployments/opentofu-foundation-checks.helpers.ts": False, "build-tools/tools/tests/deployments/opentofu-foundation-migration.helpers.ts": False, "build-tools/tools/tests/deployments/opentofu-foundation-migration.test.ts": True,
    "build-tools/tools/tests/deployments/kubernetes.public-server.ts": False, "build-tools/tools/tests/deployments/kubernetes.replay.retention.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.service-artifact.fixture.ts": False, "build-tools/tools/tests/deployments/kubernetes.publish-credentials.exact-run.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.publish-credentials.fixture.ts": False, "build-tools/tools/tests/deployments/kubernetes.publish-credentials.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.publisher.config-drift.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.publisher.credentials.test.ts": True, "build-tools/tools/tests/deployments/kubernetes.validation.test.ts": True,
    "build-tools/tools/tests/deployments/s3-static.contract.test.ts": True,
    "build-tools/tools/tests/deployments/s3-static.control-plane.reviewed-source.test.ts": True,
    "build-tools/tools/tests/deployments/s3-static.control-plane.service.test.ts": True,
    "build-tools/tools/tests/deployments/s3-static.deploy.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/s3-static.fake-aws.ts": False,
    "build-tools/tools/tests/deployments/s3-static.fixture.ts": False,
    "build-tools/tools/tests/deployments/s3-static.public-server.ts": False,
    "build-tools/tools/tests/deployments/s3-static.publisher.config-drift.test.ts": True,
    "build-tools/tools/tests/deployments/s3-static.validation.test.ts": True,
    "build-tools/tools/tests/deployments/provider-frozen-kubernetes-worker-execution.test.ts": True, "build-tools/tools/tests/deployments/provider-frozen-replay-admission.test.ts": True, "build-tools/tools/tests/deployments/provider-frozen-snapshot.test.ts": True, "build-tools/tools/tests/deployments/provider-frozen-vercel-replay.test.ts": True,
    "build-tools/tools/tests/deployments/provider-frozen-worker.test.ts": True, "build-tools/tools/tests/deployments/provider-frozen-worker-execution.test.ts": True, "build-tools/tools/tests/deployments/provider-submit-idempotency.test.ts": True,
    "build-tools/tools/tests/deployments/vercel-api.failures.test.ts": True, "build-tools/tools/tests/deployments/vercel-api.poll-context.test.ts": True, "build-tools/tools/tests/deployments/vercel-api.test.ts": True, "build-tools/tools/tests/deployments/vercel.cli-service-handoff.test.ts": True, "build-tools/tools/tests/deployments/vercel.contract.test.ts": True, "build-tools/tools/tests/deployments/vercel.fixture.ts": False,
    "build-tools/tools/tests/deployments/vercel.control-plane.helpers.ts": False, "build-tools/tools/tests/deployments/vercel.control-plane.test.ts": True,
    "build-tools/tools/tests/deployments/vercel.front-door.test.ts": True, "build-tools/tools/tests/deployments/vercel.live-publisher.test.ts": True,
    "build-tools/tools/tests/deployments/vercel.live-poll-records.test.ts": True, "build-tools/tools/tests/deployments/vercel.live-records.test.ts": True, "build-tools/tools/tests/deployments/vercel.local-publisher.test.ts": True, "build-tools/tools/tests/deployments/vercel.validation.test.ts": True,
    "build-tools/tools/tests/deployments/static-webapp-artifact-admission.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.artifact-binding.service.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.challenge-authz.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.challenged-submit.helpers.ts": False,
    "build-tools/tools/tests/deployments/nixos-shared-host.challenged-submit-transaction.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane.direct-reject.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane.backend.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane.governance.service.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane.reviewed-source.github-ssh.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane.reviewed-source.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane-client.errors.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.early-rejection-cleanup.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane.service.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.control-plane-service-env.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deployment-service-module.nix-eval.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy-auth-callback-module.nix-eval.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.failure-records.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.jenkins.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.jenkins.exec.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.multi-component.deploy.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.multi-component.fixture.ts": False,
    "build-tools/tools/tests/deployments/nixos-shared-host.multi-component.promotion.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.multi-component.replay.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.multi-component.replay.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-exec.failures.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-exec.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-reviewed-source.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-auth-admit.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.admit-discoverability.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-auth-session.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-host-apply.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.default-profile.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-plan.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.deploy.remote-ssh.command-assembly.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.explicit-removal.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.extraction.from-targets.cquery.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.host-module.duplicate-hostname.nix.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.host-module.nix-eval.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.host-render.conflicts.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.host-render.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.host-render.duplicate-hostname.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.host-render.partial-slice-preserves.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.remote-execution-transport.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.identity-provider.generated-imports.nix-eval.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.identity-provider.host-secret-boundary.nix-eval.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.service-modules.nix-eval.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.identity-provider.realm-files.nix-eval.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.service-auth-boundary.helpers.ts": False,
    "build-tools/tools/tests/deployments/nixos-shared-host.service-auth-boundary.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.service-auth-reporting.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.service-client-config.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.staged-artifact-cleanup.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.staged-artifact-admission.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.install.dev-machine.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.install.dry-run-and-status.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.install.host-modes.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.install.manifest.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.operator-docs.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.install.prompt.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.install.ssh-guess.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.install.reinstall.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.platform-state.full-reconcile.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.platform-state.remove.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.platform-state.scoped-create.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.platform-state.scoped-omit-preserves.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.platform-state.scoped-update.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.provision-only.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.publish.missing-target.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.promotion.approval.backend-source.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.promotion.backend-source.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.promotion.e2e.test.ts": True, "build-tools/tools/tests/deployments/nixos-shared-host.promotion.stage-state.helpers.ts": False,
    "build-tools/tools/tests/deployments/nixos-shared-host.publisher.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.release-actions.failure-path.replay.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.release-actions.helpers.ts": False,
    "build-tools/tools/tests/deployments/nixos-shared-host.release-actions.failure-path.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.release-actions.replay-policy.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.release-actions.rollback.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.release-actions.validation.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.records.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.remote-transport.fake.ts": False,
    "build-tools/tools/tests/deployments/nixos-shared-host.remote-ssh.command-assembly.fixture.ts": False,
    "build-tools/tools/tests/deployments/nixos-shared-host.replay.contract.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.replay.provenance.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.replay.retention.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.replay.rollback-eligibility.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.service-only.fail-closed.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.target-exceptions.replay.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.reuse.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.rollback.e2e.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.reuse.rollback-guardrails.test.ts": True,
    "build-tools/tools/tests/deployments/nixos-shared-host.validation.test.ts": True,
    "build-tools/tools/tests/deployments/infisical.test-server.ts": False, "build-tools/tools/tests/deployments/vault.test-server.ts": False,
}
