import * as fs from "node:fs/promises";
import path from "node:path";

const cargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "answer-dep"
version = "1.0.0"

[[package]]
name = "autocfg"
version = "1.5.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f2032f911046de80f0a198e0901378627c33f59ea0ac00e363d481118bd70a53"

[[package]]
name = "cfg-if"
version = "1.0.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9330f8b2ff13f34540b44e946ef35111825727b38d33286ef986142615121801"

[[package]]
name = "heck"
version = "0.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2304e00983f87ffb38b55b444b5e3b60a884b5d30c0fca7d82fe33449bbe55ea"

[[package]]
name = "indoc"
version = "2.0.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "79cf5c93f93228cf8efb3ba362535fb11199ac548a09ce117c9b1adc3030d706"
dependencies = ["rustversion"]

[[package]]
name = "libc"
version = "0.2.189"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3eaf3ede3fee6db1a4c2ee091bf8a8b4dccdc6d17f656fb07896ee72867612f2"

[[package]]
name = "memoffset"
version = "0.9.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "488016bfae457b036d996092f6cb448677611ce4449e970ceaf42695203f218a"
dependencies = ["autocfg"]

[[package]]
name = "once_cell"
version = "1.21.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9f7c3e4beb33f85d45ae3e3a1792185706c8e16d043238c593331cc7cd313b50"

[[package]]
name = "portable-atomic"
version = "1.15.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "05c8b63e8d9609db387f0324918f81d68fe27748f084ef092fb35954d0539a85"

[[package]]
name = "proc-macro2"
version = "1.0.107"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "985e7ec9bb745e6ce6535b544d84d6cd6f7ad8bd711c398938ae983b91a766d9"
dependencies = ["unicode-ident"]

[[package]]
name = "pyo3"
version = "0.22.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f402062616ab18202ae8319da13fa4279883a2b8a9d9f83f20dbade813ce1884"
dependencies = ["cfg-if", "indoc", "libc", "memoffset", "once_cell", "portable-atomic", "pyo3-build-config", "pyo3-ffi", "pyo3-macros", "unindent"]

[[package]]
name = "pyo3-build-config"
version = "0.22.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b14b5775b5ff446dd1056212d778012cbe8a0fbffd368029fd9e25b514479c38"
dependencies = ["once_cell", "target-lexicon"]

[[package]]
name = "pyo3-ffi"
version = "0.22.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9ab5bcf04a2cdcbb50c7d6105de943f543f9ed92af55818fd17b660390fc8636"
dependencies = ["libc", "pyo3-build-config"]

[[package]]
name = "pyo3-macros"
version = "0.22.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0fd24d897903a9e6d80b968368a34e1525aeb719d568dba8b3d4bfa5dc67d453"
dependencies = ["proc-macro2", "pyo3-macros-backend", "quote", "syn"]

[[package]]
name = "pyo3-macros-backend"
version = "0.22.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "36c011a03ba1e50152b4b394b479826cad97e7a21eb52df179cd91ac411cbfbe"
dependencies = ["heck", "proc-macro2", "pyo3-build-config", "quote", "syn"]

[[package]]
name = "quote"
version = "1.0.47"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1fbf4db142a473a8d80c26bbf18454ed458bf8d26c8219c331daecfdbd079001"
dependencies = ["proc-macro2"]

[[package]]
name = "rust-pyodide-app"
version = "0.1.0"
dependencies = ["answer-dep", "pyo3"]

[[package]]
name = "rustversion"
version = "1.0.23"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cf54715a573b99ac80df0bc206da022bcd442c974952c7b9720069370852e21f"

[[package]]
name = "syn"
version = "2.0.119"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "872831b642d1a07999a962a351ed35b955ea2cfc8f3862091e2a240a84f17297"
dependencies = ["proc-macro2", "quote", "unicode-ident"]

[[package]]
name = "target-lexicon"
version = "0.12.16"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "61c41af27dd6d1e27b1b16b489db798443478cef1f06a660c96db617ba5de3b1"

[[package]]
name = "unicode-ident"
version = "1.0.24"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e6e4313cd5fcd3dad5cafa179702e2b244f760991f45397d14d4ebf38247da75"

[[package]]
name = "unindent"
version = "0.2.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7264e107f553ccae879d21fbea1d6724ac785e8c3bfc762137959b5802826ef3"
`;

export async function writePyO3PyodideApp(tmp: string) {
  const appRel = path.join("projects", "apps", "rust_pyodide_app");
  const appDir = path.join(tmp, appRel);
  await fs.mkdir(path.join(appDir, "src", "demo"), { recursive: true });
  await fs.mkdir(path.join(appDir, "bin"), { recursive: true });
  await fs.mkdir(path.join(appDir, "vendor", "builddep", "builddep"), { recursive: true });
  await fs.mkdir(path.join(appDir, "answer-dep", "src"), { recursive: true });
  await fs.writeFile(path.join(appDir, "src", "demo", "__init__.py"), "");
  await fs.writeFile(
    path.join(appDir, "bin", "__main__.py"),
    'from demo import _native\nprint(f"RUST_VALUE={_native.answer()}")\ntry:\n    _native.raise_error()\nexcept ValueError as exc:\n    print(f"RUST_ERROR={exc}")\n',
  );
  await fs.writeFile(
    path.join(appDir, "vendor", "builddep", "builddep", "__init__.py"),
    "VALUE = 'build dependency imported from uv lock authority'\n",
  );
  await fs.writeFile(
    path.join(appDir, "uv.lock"),
    '[[package]]\nname = "builddep"\nversion = "1.0.0"\n',
  );
  await fs.writeFile(
    path.join(appDir, "Cargo.toml"),
    '[package]\nname = "rust-pyodide-app"\nversion = "0.1.0"\nedition = "2021"\n\n[lib]\ncrate-type = ["cdylib"]\n\n[dependencies]\npyo3 = { version = "0.22.6", features = ["extension-module"] }\nanswer-dep = { path = "answer-dep" }\n',
  );
  await fs.writeFile(path.join(appDir, "Cargo.lock"), cargoLock);
  await fs.writeFile(
    path.join(appDir, "build.rs"),
    'fn main() { assert_eq!(std::env::var("CARGO_NET_OFFLINE").as_deref(), Ok("true")); let cfg = std::env::var("PYO3_CONFIG_FILE").expect("PYO3_CONFIG_FILE"); assert!(cfg.starts_with("/nix/store/"), "PYO3_CONFIG_FILE must be a Nix store input: {cfg}"); let text = std::fs::read_to_string(&cfg).expect("read PYO3_CONFIG_FILE"); for token in ["implementation=CPython", "version=", "lib_dir=", "pointer_width=32", "suppress_build_script_link_lines=true"] { assert!(text.contains(token), "missing PyO3 config token {token}"); } for k in ["AWS_SECRET_ACCESS_KEY", "PIP_INDEX_URL", "PIP_REQUIRE_VIRTUALENV", "PYTHONPATH", "PYTHONHOME", "HTTPS_PROXY", "CC", "CFLAGS", "EMCC_CFLAGS"] { assert_ne!(std::env::var(k).as_deref(), Ok("poison")); } for k in ["PATH", "HOME", "CARGO_HOME"] { assert!(!std::env::var(k).unwrap_or_default().contains("poison"), "poisoned {k} leaked"); } }\n',
  );
  await fs.writeFile(
    path.join(appDir, "src", "lib.rs"),
    'use pyo3::exceptions::PyValueError;\nuse pyo3::prelude::*;\n#[pyfunction]\nfn answer() -> PyResult<i32> { Ok(answer_dep::value()) }\n#[pyfunction]\nfn raise_error() -> PyResult<()> { Err(PyValueError::new_err("rust pyodide error")) }\n#[pymodule]\nfn _native(m: &Bound<\'_, PyModule>) -> PyResult<()> { m.add_function(wrap_pyfunction!(answer, m)?)?; m.add_function(wrap_pyfunction!(raise_error, m)?)?; Ok(()) }\n',
  );
  await fs.writeFile(
    path.join(appDir, "answer-dep", "Cargo.toml"),
    "[package]\nname='answer-dep'\nversion='1.0.0'\nedition='2021'\n",
  );
  await fs.writeFile(
    path.join(appDir, "answer-dep", "src", "lib.rs"),
    "pub fn value() -> i32 { 42 }\n",
  );
  return { appRel, appDir };
}
