#!/usr/bin/env zx-wrapper
import Ajv from "ajv";
import * as fsp from "node:fs/promises";
import path from "node:path";
import { writeIfChanged as writeIfChangedDeterministic } from "../lib/fs-helpers";
import { getFlagBool, getFlagStr } from "../lib/cli";

type PlannerConfig = {
  id: string;
  detect?: {
    ruleTypePrefixes?: string[];
    requireAnyLabels?: string[];
    fileGlobsAny?: string[];
  };
  kindRules?: Array<{
    ifRuleTypePrefix?: string;
    ifHasAnyLabel?: string[];
    ifPathMatchesAny?: string[];
    thenKind: "bin" | "lib" | "test";
  }>;
  modulesFile?: {
    pattern?: string;
    inheritFromGo?: boolean;
  };
  builders?: {
    mkApp?: { expr: string; args: string[] };
    mkLib?: { expr: string; args: string[] };
  };
};

function repoPath(...parts: string[]): string {
  return path.join(process.cwd(), ...parts);
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fsp.access(p);
    return true;
  } catch {
    return false;
  }
}

async function readSchema(): Promise<any> {
  const p = repoPath("build-tools/tools/dev/planner.config.schema.json");
  return JSON.parse(await fsp.readFile(p, "utf8"));
}

async function loadConfig(lang: string): Promise<PlannerConfig> {
  const cfgPath = repoPath("build-tools/tools/nix/planner", `${lang}.config.ts`);
  if (!(await pathExists(cfgPath))) {
    throw new Error(`Missing planner config: build-tools/tools/nix/planner/${lang}.config.ts`);
  }
  const mod = await import(pathToFileUrlLike(cfgPath));
  const cfg: PlannerConfig = (mod.default ?? mod) as PlannerConfig;
  return cfg;
}

function pathToFileUrlLike(p: string): string {
  const abs = path.resolve(p);
  const pref = abs.startsWith("/") ? "file://" : "file:///";
  return pref + abs;
}

function uniqSorted(xs: string[] | undefined): string[] {
  const s = new Set<string>();
  for (const x of xs || []) if (typeof x === "string" && x.length > 0) s.add(x);
  return Array.from(s).sort();
}

function nixList(xs: string[]): string {
  return "[ " + xs.map((x) => JSON.stringify(x)).join(" ") + " ]";
}

function generateNix(cfg: PlannerConfig): string {
  const detect = cfg.detect || {};
  const rulePrefixes = uniqSorted(detect.ruleTypePrefixes);
  const labels = uniqSorted(detect.requireAnyLabels);
  const kinds = cfg.kindRules || [];
  const inheritGo = !!cfg.modulesFile?.inheritFromGo;
  const pattern = cfg.modulesFile?.pattern || "";
  const mkApp = cfg.builders?.mkApp;
  const mkLib = cfg.builders?.mkLib;

  const isTargetParts: string[] = [];
  if (rulePrefixes.length > 0) {
    isTargetParts.push(`(lib.any (p: hasPrefix (n.rule_type or "") p) ${nixList(rulePrefixes)})`);
  }
  if (labels.length > 0) {
    isTargetParts.push(`(hasAnyLabel (n.labels or []) ${nixList(labels)})`);
  }
  // File globs are not universally available in the graph snapshot; skip for now.
  const isTargetExpr = isTargetParts.length > 0 ? isTargetParts.join(" || ") : "false";

  const kindLines = kinds.map((kr) => {
    const conds: string[] = [];
    if (kr.ifRuleTypePrefix) {
      conds.push(`(hasPrefix (n.rule_type or "") ${JSON.stringify(kr.ifRuleTypePrefix)})`);
    }
    if (kr.ifHasAnyLabel && kr.ifHasAnyLabel.length > 0) {
      conds.push(`(hasAnyLabel (n.labels or []) ${nixList(uniqSorted(kr.ifHasAnyLabel))})`);
    }
    // Path matching omitted; graph nodes typically lack path in our usage.
    const cond = conds.length > 0 ? conds.join(" && ") : "false";
    return `    else if ${cond} then ${JSON.stringify(kr.thenKind)}`;
  });

  const modulesExpr = inheritGo
    ? "modulesTomlFor name"
    : pattern
      ? `repoRoot + "/" + (pkgPathOf name) + "/" + ${JSON.stringify(pattern).replace("{name}", '" + name + "')}`
      : "modulesTomlFor name";

  const mkAppExpr = mkApp
    ? `${mkApp.expr} ${mkApp.args.join(" ")}`
    : "T.goApp { inherit name; modulesToml = modulesTomlFor name; repoRoot = repoRoot; subdir = (pkgPathOf name); }";
  const mkLibExpr = mkLib
    ? `${mkLib.expr} ${mkLib.args.join(" ")}`
    : "T.goLib { inherit name; modulesToml = modulesTomlFor name; repoRoot = repoRoot; subdir = (pkgPathOf name); }";

  return `# Generated by planner-gen for ${cfg.id}\n{ lib }: ctx:\nlet\n  inherit (ctx) T repoRoot modulesTomlFor pkgPathOf;\n  hasAnyLabel = labels: patterns: lib.any (p: lib.elem p labels) patterns;\n  hasPrefix = s: p: lib.hasPrefix p (s or \"\");\nin {\n  isTarget = n: ${isTargetExpr};\n\n  kindOf = n:\n    if hasAnyLabel (n.labels or []) [ \"kind:bin\" ] then \"bin\"\n    else if hasAnyLabel (n.labels or []) [ \"kind:lib\" ] then \"lib\"\n${kindLines.join("\n")}\n    else null;\n\n  modulesFileFor = name: ${modulesExpr};\n\n  mkApp = name: ${mkAppExpr};\n  mkLib = name: ${mkLibExpr};\n}\n`;
}

async function validateConfig(cfg: PlannerConfig) {
  const ajv = new Ajv({ allErrors: true, strict: false });
  const schema = await readSchema();
  const validate = ajv.compile(schema);
  const ok = validate(cfg);
  if (!ok) {
    const msg = (validate.errors || []).map((e) => `- ${e.instancePath} ${e.message}`).join("\n");
    throw new Error(`Invalid planner config for ${cfg.id}:\n${msg}`);
  }
}

async function writePlannerOutput(
  outPath: string,
  content: string,
  checkOnly: boolean,
): Promise<boolean> {
  const exists = await pathExists(outPath);
  if (exists) {
    const prev = await fsp.readFile(outPath, "utf8");
    if (prev === content) return false;
    if (checkOnly) {
      throw new Error(`planner-gen: ${outPath} would change (run without --check to update)`);
    }
  }
  await fsp.mkdir(path.dirname(outPath), { recursive: true });
  await writeIfChangedDeterministic(outPath, content);
  return true;
}

async function main() {
  const check = getFlagBool("check");
  const all = getFlagBool("all");
  const one = getFlagStr("lang", "").trim();

  const changed: string[] = [];
  const langs: string[] = [];
  if (all) {
    const dir = repoPath("build-tools/tools/nix/planner");
    if (await pathExists(dir)) {
      for (const e of await fsp.readdir(dir)) {
        if (e.endsWith(".config.ts")) langs.push(e.slice(0, -".config.ts".length));
      }
    }
  } else if (one) {
    langs.push(one);
  } else {
    throw new Error("Usage: planner-gen --lang <id> | --all [--check]");
  }

  for (const id of langs.sort()) {
    const cfg = await loadConfig(id);
    await validateConfig(cfg);
    const out = generateNix(cfg);
    const outPath = repoPath("build-tools/tools/nix/planner", `${id}.nix`);
    const did = await writePlannerOutput(outPath, out, check);
    if (did) changed.push(outPath);
  }
  if (changed.length > 0) {
    console.log("planner-gen wrote:\n" + changed.map((s) => "- " + s).join("\n"));
  } else {
    console.log("planner-gen: OK (no changes)");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
