#!/usr/bin/env zx-wrapper
import * as fsp from "node:fs/promises";
import path from "node:path";
import { writeIfChanged } from "../lib/fs-helpers";
import { repoRoot } from "../lib/repo";
import { buildToolPath, buildToolsRoot } from "./dev-build/paths";

type ToolchainPaths = {
  go: { bin: string; root: string };
  python: { bin: string };
  zxWrapper: { bin: string };
};

const JSON_REL = path.join("build-tools", "tools", "dev", "toolchain-paths.json");
const BZL_REL = path.join("toolchains", "toolchain_paths.bzl");

function activeViberootsRoot(root: string): string {
  return path.dirname(buildToolsRoot(root));
}

function toolchainJsonPath(root: string): string {
  return buildToolPath(root, "tools/dev/toolchain-paths.json");
}

function toolchainBzlPath(root: string): string {
  return path.join(activeViberootsRoot(root), BZL_REL);
}

function isNixStorePath(p: string): boolean {
  return p === "/nix/store" || p.startsWith("/nix/store/");
}

async function nixPathInfo(root: string, attr: string): Promise<string> {
  const res = await $({
    cwd: root,
    stdio: "pipe",
  })`nix path-info .#${attr} --json --accept-flake-config`.nothrow();
  if (res.exitCode !== 0) return "";
  const txt = String(res.stdout || "").trim();
  if (!txt.startsWith("[")) return "";
  try {
    const arr = JSON.parse(txt) as Array<string | { path?: string; valid?: boolean }>;
    const first = arr[0];
    const out = (typeof first === "string" ? first : String(first?.path || "")).trim();
    if (!out) return "";
    if (typeof first !== "string" && first?.valid === false) return "";
    try {
      await fsp.access(out);
      return out;
    } catch {
      return "";
    }
  } catch {
    return "";
  }
}

async function nixBuildOutPath(root: string, attr: string): Promise<string> {
  const res = await $({
    cwd: root,
    stdio: "pipe",
  })`nix build .#${attr} --no-link --print-out-paths --accept-flake-config`;
  const out =
    String(res.stdout || "")
      .trim()
      .split("\n")
      .filter(Boolean)
      .pop() || "";
  if (!out) {
    throw new Error(`nix build returned no output path for ${attr}`);
  }
  return out;
}

async function resolveToolchainOut(root: string, attr: string): Promise<string> {
  const info = await nixPathInfo(root, attr);
  if (info) return info;
  return await nixBuildOutPath(root, attr);
}

async function resolveGoRoot(goBin: string): Promise<string> {
  try {
    const res = await $({ stdio: "pipe" })`${goBin} env GOROOT`;
    return String(res.stdout || "").trim();
  } catch {
    return "";
  }
}

function renderBzl(paths: ToolchainPaths): string {
  const q = (v: string) => `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  return [
    "# GENERATED FILE — DO NOT EDIT.",
    "# Generated by build-tools/tools/dev/gen-toolchain-paths.ts",
    `NIX_GO_BIN = ${q(paths.go.bin)}`,
    `NIX_GO_ROOT = ${q(paths.go.root)}`,
    `NIX_PYTHON_BIN = ${q(paths.python.bin)}`,
    `NIX_ZX_WRAPPER_BIN = ${q(paths.zxWrapper.bin)}`,
    "",
  ].join("\n");
}

async function readExistingToolchainPaths(repo: string): Promise<ToolchainPaths | null> {
  const jsonPath = toolchainJsonPath(repo);
  let raw = "";
  try {
    raw = await fsp.readFile(jsonPath, "utf8");
  } catch {
    return null;
  }
  const txt = raw.trim();
  if (!txt) return null;
  try {
    const parsed = JSON.parse(txt) as Partial<ToolchainPaths>;
    const goBin = String(parsed?.go?.bin || "").trim();
    const goRoot = String(parsed?.go?.root || "").trim();
    const pyBin = String(parsed?.python?.bin || "").trim();
    const zxWrapperBin = String(parsed?.zxWrapper?.bin || "").trim();
    if (!goBin || !pyBin || !zxWrapperBin) return null;
    if (!isNixStorePath(goBin) || !isNixStorePath(pyBin) || !isNixStorePath(zxWrapperBin)) {
      return null;
    }
    try {
      await fsp.access(goBin);
      await fsp.access(pyBin);
      await fsp.access(zxWrapperBin);
    } catch {
      return null;
    }
    const root = goRoot || (await resolveGoRoot(goBin)) || "";
    if (!root || !isNixStorePath(root)) return null;
    try {
      await fsp.access(root);
    } catch {
      return null;
    }
    const out: ToolchainPaths = {
      go: { bin: goBin, root },
      python: { bin: pyBin },
      zxWrapper: { bin: zxWrapperBin },
    };
    const bzlPath = toolchainBzlPath(repo);
    await writeIfChanged(jsonPath, JSON.stringify(out, null, 2) + "\n");
    await writeIfChanged(bzlPath, renderBzl(out));
    return out;
  } catch {
    return null;
  }
}

export async function ensureToolchainPathsFiles(root?: string): Promise<ToolchainPaths> {
  const repo = root || repoRoot();
  const existing = await readExistingToolchainPaths(repo);
  if (existing) return existing;
  const goOut = await resolveToolchainOut(repo, "toolchains.go");
  const pyOut = await resolveToolchainOut(repo, "toolchains.python");
  const zxWrapperOut = await resolveToolchainOut(repo, "zx-wrapper");
  const goBin = path.join(goOut, "bin", "go");
  const pyBin = path.join(pyOut, "bin", "python3");
  const zxWrapperBin = path.join(zxWrapperOut, "bin", "zx-wrapper");
  if (!isNixStorePath(goOut) || !isNixStorePath(pyOut) || !isNixStorePath(zxWrapperOut)) {
    throw new Error(
      `expected Nix store toolchains; got go=${goOut || "<missing>"} python=${
        pyOut || "<missing>"
      } zx-wrapper=${zxWrapperOut || "<missing>"}`,
    );
  }
  const goRoot = (await resolveGoRoot(goBin)) || path.join(goOut, "share", "go");
  const pathsObj: ToolchainPaths = {
    go: { bin: goBin, root: goRoot },
    python: { bin: pyBin },
    zxWrapper: { bin: zxWrapperBin },
  };
  const jsonPath = toolchainJsonPath(repo);
  const bzlPath = toolchainBzlPath(repo);
  await writeIfChanged(jsonPath, JSON.stringify(pathsObj, null, 2) + "\n");
  await writeIfChanged(bzlPath, renderBzl(pathsObj));
  await fsp.access(jsonPath);
  await fsp.access(bzlPath);
  return pathsObj;
}
