#!/usr/bin/env zx-wrapper
import * as fsp from "node:fs/promises";
import path from "node:path";
import { writeIfChanged } from "../lib/fs-helpers.ts";
import { repoRoot } from "../lib/repo.ts";

type ToolchainPaths = {
  go: { bin: string; root: string };
  python: { bin: string };
};

const JSON_REL = path.join("build-tools", "tools", "dev", "toolchain-paths.json");
const BZL_REL = path.join("toolchains", "toolchain_paths.bzl");

function isNixStorePath(p: string): boolean {
  return p === "/nix/store" || p.startsWith("/nix/store/");
}

async function nixPathInfo(root: string, attr: string): Promise<string> {
  const res = await $({
    cwd: root,
    stdio: "pipe",
  })`nix path-info .#${attr} --json --accept-flake-config`.nothrow();
  if (res.exitCode !== 0) return "";
  const txt = String(res.stdout || "").trim();
  if (!txt.startsWith("[")) return "";
  try {
    const arr = JSON.parse(txt) as Array<string | { path?: string }>;
    const first = arr[0];
    const out = typeof first === "string" ? first : String(first?.path || "");
    return out || "";
  } catch {
    return "";
  }
}

async function nixBuildOutPath(root: string, attr: string): Promise<string> {
  const res = await $({
    cwd: root,
    stdio: "pipe",
  })`nix build .#${attr} --no-link --print-out-paths --accept-flake-config`;
  const out =
    String(res.stdout || "")
      .trim()
      .split("\n")
      .filter(Boolean)
      .pop() || "";
  if (!out) {
    throw new Error(`nix build returned no output path for ${attr}`);
  }
  return out;
}

async function resolveToolchainOut(root: string, attr: string): Promise<string> {
  const info = await nixPathInfo(root, attr);
  if (info) return info;
  return await nixBuildOutPath(root, attr);
}

async function resolveGoRoot(goBin: string): Promise<string> {
  try {
    const res = await $({ stdio: "pipe" })`${goBin} env GOROOT`;
    return String(res.stdout || "").trim();
  } catch {
    return "";
  }
}

function renderBzl(paths: ToolchainPaths): string {
  const q = (v: string) => `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  return [
    "# GENERATED FILE — DO NOT EDIT.",
    "# Generated by build-tools/tools/dev/gen-toolchain-paths.ts",
    `NIX_GO_BIN = ${q(paths.go.bin)}`,
    `NIX_GO_ROOT = ${q(paths.go.root)}`,
    `NIX_PYTHON_BIN = ${q(paths.python.bin)}`,
    "",
  ].join("\n");
}

async function readExistingToolchainPaths(repo: string): Promise<ToolchainPaths | null> {
  const jsonPath = path.join(repo, JSON_REL);
  let raw = "";
  try {
    raw = await fsp.readFile(jsonPath, "utf8");
  } catch {
    return null;
  }
  const txt = raw.trim();
  if (!txt) return null;
  try {
    const parsed = JSON.parse(txt) as Partial<ToolchainPaths>;
    const goBin = String(parsed?.go?.bin || "").trim();
    const goRoot = String(parsed?.go?.root || "").trim();
    const pyBin = String(parsed?.python?.bin || "").trim();
    if (!goBin || !pyBin) return null;
    if (!isNixStorePath(goBin) || !isNixStorePath(pyBin)) return null;
    const root = goRoot || (await resolveGoRoot(goBin)) || "";
    if (!root || !isNixStorePath(root)) return null;
    const out: ToolchainPaths = { go: { bin: goBin, root }, python: { bin: pyBin } };
    const bzlPath = path.join(repo, BZL_REL);
    await writeIfChanged(jsonPath, JSON.stringify(out, null, 2) + "\n");
    await writeIfChanged(bzlPath, renderBzl(out));
    return out;
  } catch {
    return null;
  }
}

export async function ensureToolchainPathsFiles(root?: string): Promise<ToolchainPaths> {
  const repo = root || repoRoot();
  const existing = await readExistingToolchainPaths(repo);
  if (existing) return existing;
  const goOut = await resolveToolchainOut(repo, "toolchains.go");
  const pyOut = await resolveToolchainOut(repo, "toolchains.python");
  const goBin = path.join(goOut, "bin", "go");
  const pyBin = path.join(pyOut, "bin", "python3");
  if (!isNixStorePath(goOut) || !isNixStorePath(pyOut)) {
    throw new Error(
      `expected Nix store toolchains; got go=${goOut || "<missing>"} python=${
        pyOut || "<missing>"
      }`,
    );
  }
  const goRoot = (await resolveGoRoot(goBin)) || path.join(goOut, "share", "go");
  const pathsObj: ToolchainPaths = { go: { bin: goBin, root: goRoot }, python: { bin: pyBin } };
  const jsonPath = path.join(repo, JSON_REL);
  const bzlPath = path.join(repo, BZL_REL);
  await writeIfChanged(jsonPath, JSON.stringify(pathsObj, null, 2) + "\n");
  await writeIfChanged(bzlPath, renderBzl(pathsObj));
  await fsp.access(jsonPath);
  await fsp.access(bzlPath);
  return pathsObj;
}
