import { REVIEWED_PUBLIC_KEYS, REVIEWED_SUBSTITUTERS } from "../lib/artifact-nix-policy";

export type RenderedToolchainPaths = {
  artifactTools: { root: string };
  go: { bin: string; root: string };
  python: { bin: string };
  zxWrapper: { bin: string };
};

function quote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function list(values: readonly string[]): string {
  return `[${values.map(quote).join(", ")}]`;
}

export function renderToolchainBzl(paths: RenderedToolchainPaths): string {
  return [
    "# GENERATED FILE - DO NOT EDIT.",
    "# Generated by build-tools/tools/dev/gen-toolchain-paths.ts",
    `NIX_GO_BIN = ${quote(paths.go.bin)}`,
    `NIX_GO_ROOT = ${quote(paths.go.root)}`,
    `NIX_PYTHON_BIN = ${quote(paths.python.bin)}`,
    `NIX_ZX_WRAPPER_BIN = ${quote(paths.zxWrapper.bin)}`,
    `NIX_ARTIFACT_TOOLS_ROOT = ${quote(paths.artifactTools.root)}`,
    `NIX_ARTIFACT_SUBSTITUTERS = ${list(REVIEWED_SUBSTITUTERS)}`,
    `NIX_ARTIFACT_TRUSTED_PUBLIC_KEYS = ${list(REVIEWED_PUBLIC_KEYS)}`,
    "",
  ].join("\n");
}
