#!/usr/bin/env zx-wrapper
import assert from "node:assert/strict";
import * as fsp from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import {
  binWrapper,
  escapeRegExp,
  makeFakeAgentTools,
  repoRoot,
  scratchRoot,
} from "./agent-wrapper-test-helpers.ts";

const wrapper = binWrapper("codex");
const makeFakeTools = (tmp: string, gitRoot: string) => makeFakeAgentTools(tmp, gitRoot, "codex");
test("codex --remove-worktree removes the worktree, branch, and stale metadata", async () => {
  await fsp.mkdir(scratchRoot, { recursive: true });
  const tmp = await fsp.mkdtemp(path.join(scratchRoot, "codex-wrapper-"));
  try {
    const gitRoot = path.join(tmp, "repo");
    const worktreeRoot = path.join(gitRoot, ".codex", "worktrees", "remove-me");
    await fsp.mkdir(worktreeRoot, { recursive: true });
    await fsp.writeFile(path.join(worktreeRoot, ".git"), "gitdir: fake\n", "utf8");
    const fake = await makeFakeTools(tmp, gitRoot);
    const res = await $({
      cwd: gitRoot,
      stdio: "pipe",
      env: {
        ...process.env,
        PATH: `${path.dirname(wrapper)}:${fake.bin}:/usr/bin:/bin`,
      },
    })`${wrapper} --remove-worktree remove-me`;

    assert.equal(res.exitCode, 0, String(res.stderr || res.stdout));
    await assert.rejects(fsp.stat(worktreeRoot), /ENOENT/);
    const log = await fsp.readFile(fake.log, "utf8");
    assert.match(log, new RegExp(`git worktree remove ${escapeRegExp(worktreeRoot)}`));
    assert.match(log, /git branch -D worktree-remove-me/);
    assert.match(log, /git worktree prune/);
    assert.doesNotMatch(log, /codex /);
  } finally {
    await fsp.rm(tmp, { recursive: true, force: true });
  }
});

test("codex --remove-worktree removes a clean submodule-containing worktree", async () => {
  await fsp.mkdir(scratchRoot, { recursive: true });
  const tmp = await fsp.mkdtemp(path.join(scratchRoot, "codex-wrapper-"));
  try {
    const gitRoot = path.join(tmp, "repo");
    const worktreeRoot = path.join(gitRoot, ".codex", "worktrees", "remove-me");
    await fsp.mkdir(worktreeRoot, { recursive: true });
    await fsp.writeFile(path.join(worktreeRoot, ".git"), "gitdir: fake\n", "utf8");
    await fsp.writeFile(path.join(worktreeRoot, "SUBMODULE_GUARD"), "", "utf8");
    const fake = await makeFakeTools(tmp, gitRoot);
    const res = await $({
      cwd: gitRoot,
      stdio: "pipe",
      env: {
        ...process.env,
        PATH: `${path.dirname(wrapper)}:${fake.bin}:/usr/bin:/bin`,
      },
    })`${wrapper} --remove-worktree remove-me`;

    assert.equal(res.exitCode, 0, String(res.stderr || res.stdout));
    await assert.rejects(fsp.stat(worktreeRoot), /ENOENT/);
    const log = await fsp.readFile(fake.log, "utf8");
    assert.match(log, /git worktree remove .*remove-me/);
    assert.match(log, /git -C .*remove-me submodule deinit -f --all/);
    assert.match(log, /git worktree remove --force .*remove-me/);
    assert.match(String(res.stderr), /contains clean submodules/);
  } finally {
    await fsp.rm(tmp, { recursive: true, force: true });
  }
});

test("codex --remove-worktree ignores appended launch arguments", async () => {
  await fsp.mkdir(scratchRoot, { recursive: true });
  const tmp = await fsp.mkdtemp(path.join(scratchRoot, "codex-wrapper-"));
  try {
    const gitRoot = path.join(tmp, "repo");
    const worktreeRoot = path.join(gitRoot, ".codex", "worktrees", "remove-me");
    await fsp.mkdir(worktreeRoot, { recursive: true });
    await fsp.writeFile(path.join(worktreeRoot, ".git"), "gitdir: fake\n", "utf8");
    const fake = await makeFakeTools(tmp, gitRoot);
    const res = await $({
      cwd: gitRoot,
      stdio: "pipe",
      env: {
        ...process.env,
        PATH: `${path.dirname(wrapper)}:${fake.bin}:/usr/bin:/bin`,
      },
    })`${wrapper} --remove-worktree remove-me exec task`;

    assert.equal(res.exitCode, 0, String(res.stderr || res.stdout));
    await assert.rejects(fsp.stat(worktreeRoot), /ENOENT/);
    const log = await fsp.readFile(fake.log, "utf8");
    assert.match(log, new RegExp(`git worktree remove ${escapeRegExp(worktreeRoot)}`));
    assert.match(log, /git branch -D worktree-remove-me/);
    assert.match(log, /git worktree prune/);
    assert.doesNotMatch(log, /codex /);
  } finally {
    await fsp.rm(tmp, { recursive: true, force: true });
  }
});

test("codex --remove-worktree auto-forces only autogenerated provider changes", async () => {
  await fsp.mkdir(scratchRoot, { recursive: true });
  const tmp = await fsp.mkdtemp(path.join(scratchRoot, "codex-wrapper-"));
  try {
    const gitRoot = path.join(tmp, "repo");
    const worktreeRoot = path.join(gitRoot, ".codex", "worktrees", "remove-me");
    await fsp.mkdir(worktreeRoot, { recursive: true });
    await fsp.writeFile(path.join(worktreeRoot, ".git"), "gitdir: fake\n", "utf8");
    await fsp.writeFile(path.join(worktreeRoot, "AUTOGEN_ONLY"), "", "utf8");
    const fake = await makeFakeTools(tmp, gitRoot);
    const res = await $({
      cwd: gitRoot,
      stdio: "pipe",
      env: {
        ...process.env,
        PATH: `${path.dirname(wrapper)}:${fake.bin}:/usr/bin:/bin`,
      },
    })`${wrapper} --remove-worktree remove-me`;

    assert.equal(res.exitCode, 0, String(res.stderr || res.stdout));
    await assert.rejects(fsp.stat(worktreeRoot), /ENOENT/);
    const log = await fsp.readFile(fake.log, "utf8");
    assert.match(log, new RegExp(`git worktree remove --force ${escapeRegExp(worktreeRoot)}`));
    assert.match(String(res.stderr), /only discardable autogenerated provider changes/);
  } finally {
    await fsp.rm(tmp, { recursive: true, force: true });
  }
});

test("codex --remove-worktree does not force unrelated dirty changes", async () => {
  await fsp.mkdir(scratchRoot, { recursive: true });
  const tmp = await fsp.mkdtemp(path.join(scratchRoot, "codex-wrapper-"));
  try {
    const gitRoot = path.join(tmp, "repo");
    const worktreeRoot = path.join(gitRoot, ".codex", "worktrees", "remove-me");
    await fsp.mkdir(worktreeRoot, { recursive: true });
    await fsp.writeFile(path.join(worktreeRoot, ".git"), "gitdir: fake\n", "utf8");
    await fsp.writeFile(path.join(worktreeRoot, "REAL_DIRTY"), "", "utf8");
    const fake = await makeFakeTools(tmp, gitRoot);
    const res = await $({
      cwd: gitRoot,
      stdio: "pipe",
      reject: false,
      nothrow: true,
      env: {
        ...process.env,
        PATH: `${path.dirname(wrapper)}:${fake.bin}:/usr/bin:/bin`,
      },
    })`${wrapper} --remove-worktree remove-me`;

    assert.equal(res.exitCode, 13);
    assert.equal((await fsp.stat(worktreeRoot)).isDirectory(), true);
    const log = await fsp.readFile(fake.log, "utf8");
    assert.match(log, new RegExp(`git worktree remove ${escapeRegExp(worktreeRoot)}`));
    assert.doesNotMatch(log, /git worktree remove --force/);
    assert.doesNotMatch(log, /git branch -D worktree-remove-me/);
    assert.doesNotMatch(log, /git worktree prune/);
  } finally {
    await fsp.rm(tmp, { recursive: true, force: true });
  }
});

test("codex --remove-worktree --force removes unrelated dirty changes", async () => {
  await fsp.mkdir(scratchRoot, { recursive: true });
  const tmp = await fsp.mkdtemp(path.join(scratchRoot, "codex-wrapper-"));
  try {
    const gitRoot = path.join(tmp, "repo");
    const worktreeRoot = path.join(gitRoot, ".codex", "worktrees", "remove-me");
    await fsp.mkdir(worktreeRoot, { recursive: true });
    await fsp.writeFile(path.join(worktreeRoot, ".git"), "gitdir: fake\n", "utf8");
    await fsp.writeFile(path.join(worktreeRoot, "REAL_DIRTY"), "", "utf8");
    const fake = await makeFakeTools(tmp, gitRoot);
    const res = await $({
      cwd: gitRoot,
      stdio: "pipe",
      env: {
        ...process.env,
        PATH: `${path.dirname(wrapper)}:${fake.bin}:/usr/bin:/bin`,
      },
    })`${wrapper} --remove-worktree remove-me --force`;

    assert.equal(res.exitCode, 0, String(res.stderr || res.stdout));
    await assert.rejects(fsp.stat(worktreeRoot), /ENOENT/);
    const log = await fsp.readFile(fake.log, "utf8");
    assert.match(log, new RegExp(`git worktree remove --force ${escapeRegExp(worktreeRoot)}`));
    assert.match(log, /git branch -D worktree-remove-me/);
    assert.match(log, /git worktree prune/);
  } finally {
    await fsp.rm(tmp, { recursive: true, force: true });
  }
});

test("codex --force is only accepted for removal", async () => {
  await fsp.mkdir(scratchRoot, { recursive: true });
  const tmp = await fsp.mkdtemp(path.join(scratchRoot, "codex-wrapper-"));
  try {
    const gitRoot = path.join(tmp, "repo");
    await fsp.mkdir(gitRoot, { recursive: true });
    const fake = await makeFakeTools(tmp, gitRoot);
    const res = await $({
      cwd: gitRoot,
      stdio: "pipe",
      reject: false,
      nothrow: true,
      env: {
        ...process.env,
        PATH: `${path.dirname(wrapper)}:${fake.bin}:/usr/bin:/bin`,
      },
    })`${wrapper} --force exec task`;

    assert.equal(res.exitCode, 2);
    assert.match(String(res.stderr), /--force can only be combined/);
  } finally {
    await fsp.rm(tmp, { recursive: true, force: true });
  }
});
