#!/usr/bin/env zx-wrapper
import assert from "node:assert/strict";
import * as fsp from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { ensureBuckPreludeConfig } from "../../dev/dev-build/prelude";

test("ensureBuckPreludeConfig repairs legacy current prelude cell paths", async () => {
  const root = await fsp.mkdtemp(path.join(os.tmpdir(), "vbr-prelude-config-"));
  try {
    await fsp.writeFile(path.join(root, ".buckroot"), ".\n", "utf8");
    await fsp.mkdir(path.join(root, ".viberoots", "current"), { recursive: true });
    await fsp.writeFile(
      path.join(root, ".buckconfig"),
      [
        "# generated by viberoots/init-consumer",
        "[repositories]",
        "root = .",
        "viberoots = ./.viberoots/current",
        "prelude = ./.viberoots/current/prelude",
        "[cells]",
        "root = .",
        "viberoots = ./.viberoots/current",
        "prelude = ./.viberoots/current/prelude",
        "",
      ].join("\n"),
      "utf8",
    );

    assert.equal(await ensureBuckPreludeConfig(root), true);

    const buckconfig = await fsp.readFile(path.join(root, ".buckconfig"), "utf8");
    assert.match(buckconfig, /prelude = \.\/\.viberoots\/workspace\/prelude/);
    assert.doesNotMatch(buckconfig, /prelude = \.\/\.viberoots\/current\/prelude/);
  } finally {
    await fsp.rm(root, { recursive: true, force: true });
  }
});
