import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import * as fsp from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { promisify } from "node:util";
import { direnvStage0 } from "../../lib/consumer-direnv";
import { ensureNixStoreToolPathSync } from "../../lib/tool-paths";
import { VIBEROOTS_SOURCE_ROOT } from "../lib/test-helpers/source-paths";

const execFileAsync = promisify(execFile);

async function staleConsumer(): Promise<{ root: string; stage0: string }> {
  const root = await fsp.mkdtemp(path.join(os.tmpdir(), "vbr-s-stale-shell-"));
  const workspace = path.join(root, ".viberoots/workspace");
  const stage0 = path.join(root, ".viberoots/bootstrap/direnv-stage0.sh");
  await Promise.all([
    fsp.mkdir(path.dirname(stage0), { recursive: true }),
    fsp.mkdir(path.join(workspace, "prelude"), { recursive: true }),
  ]);
  await Promise.all([
    fsp.symlink(VIBEROOTS_SOURCE_ROOT, path.join(root, "viberoots")),
    fsp.symlink("../viberoots", path.join(root, ".viberoots/current")),
    fsp.writeFile(path.join(workspace, "flake.nix"), "{ outputs = _: {}; }\n"),
    fsp.writeFile(path.join(workspace, "flake.lock"), "{}\n"),
    fsp.writeFile(path.join(workspace, "prelude/prelude.bzl"), "\n"),
    fsp.writeFile(
      stage0,
      "# stale generated fixture\nnix run .#viberoots -- exact-pnpm-store-env\n",
    ),
  ]);
  return { root, stage0 };
}

async function writeExecutable(file: string, source: string): Promise<void> {
  await fsp.mkdir(path.dirname(file), { recursive: true });
  await fsp.writeFile(file, source, { mode: 0o755 });
}

test("s refreshes stale stage-0 before direnv reload with Nix-store zx-wrapper", async () => {
  const { root, stage0 } = await staleConsumer();
  const fakeBin = path.join(root, "fake-bin");
  const wrapperLog = path.join(root, "wrapper.log");
  try {
    await writeExecutable(
      path.join(fakeBin, "direnv"),
      `#!/usr/bin/env bash
set -euo pipefail
test "$1" = exec
root="$2"
shift 2
wrapper="$(command -v zx-wrapper)"
case "$wrapper" in /nix/store/*/bin/zx-wrapper) ;; *) exit 91 ;; esac
grep -q 'generated by viberoots/init-consumer' "$root/.viberoots/bootstrap/direnv-stage0.sh"
! grep -q 'exact-pnpm-store-env' "$root/.viberoots/bootstrap/direnv-stage0.sh"
printf '%s\n' "$wrapper" > ${JSON.stringify(wrapperLog)}
IN_NIX_SHELL=1 exec "$@"
`,
    );
    const wrapper = ensureNixStoreToolPathSync("zx-wrapper");
    const result = await execFileAsync(
      path.join(VIBEROOTS_SOURCE_ROOT, "build-tools/tools/bin/s"),
      ["--json", "99999999"],
      {
        cwd: root,
        env: {
          ...process.env,
          PATH: `${fakeBin}:${path.dirname(wrapper)}:${process.env.PATH || ""}`,
          WORKSPACE_ROOT: root,
          VIBEROOTS_SOURCE_ROOT,
          VBR_TAIL_LOG_STATUS_INTERVAL: "0.01",
          BUCK_TEST_TARGET: "",
          BUCK_TEST_SRC: "",
          VBR_VERIFY_LOG_FILE: "",
          VBR_VERIFY_PROCESS_STATE_FILE: "",
          VBR_TEST_SEED_STORE_PATH: "",
          VBR_RUN_IN_TEMP_REPO: "",
        },
        timeout: 30_000,
      },
    );
    assert.match(result.stderr, /dev shell inputs changed/);
    assert.doesNotMatch(result.stderr, /unknown command|zx-wrapper.*not found/);
    assert.equal(await fsp.readFile(stage0, "utf8"), direnvStage0());
    assert.equal((await fsp.readFile(wrapperLog, "utf8")).trim(), wrapper);
  } finally {
    await fsp.rm(root, { recursive: true, force: true });
  }
});

test("stale reload rejects a host zx-wrapper without running direnv", async () => {
  const { root, stage0 } = await staleConsumer();
  const fakeBin = path.join(root, "fake-bin");
  const direnvLog = path.join(root, "direnv.log");
  try {
    await writeExecutable(path.join(fakeBin, "zx-wrapper"), "#!/bin/sh\nexit 92\n");
    await writeExecutable(
      path.join(fakeBin, "direnv"),
      `#!/bin/sh\nprintf 'called\n' > ${JSON.stringify(direnvLog)}\nexit 93\n`,
    );
    await assert.rejects(
      execFileAsync(path.join(VIBEROOTS_SOURCE_ROOT, "build-tools/tools/bin/s"), [], {
        cwd: root,
        env: {
          PATH: `${fakeBin}:/usr/bin:/bin:/usr/sbin:/sbin`,
          WORKSPACE_ROOT: root,
          VIBEROOTS_SOURCE_ROOT,
        },
        timeout: 30_000,
      }),
      (error: unknown) => {
        const stderr = String((error as { stderr?: unknown }).stderr || "");
        assert.match(stderr, /stale dev shell inputs require the current Nix-store zx-wrapper/);
        assert.match(stderr, /repair: run viberoots post-clone, then retry the command/);
        return true;
      },
    );
    await assert.rejects(fsp.access(direnvLog), { code: "ENOENT" });
    assert.match(await fsp.readFile(stage0, "utf8"), /exact-pnpm-store-env/);
  } finally {
    await fsp.rm(root, { recursive: true, force: true });
  }
});
