import type { RunbookCommand } from "./cloud-control-runbook";
import { rootPrelude } from "./cloud-control-runbook-root";
import type { CloudControlSetupInput } from "./cloud-control-setup-types";
import { awsTopologyRequiredCapabilityIds } from "./cloud-control-aws-topology-capabilities";

export function providerCapabilityEvidenceCommands(
  input: CloudControlSetupInput,
): RunbookCommand[] {
  return awsTopologyRequiredCapabilityIds(input.awsTopology)
    .filter((id) => id !== "supabase-managed-postgres")
    .map((id) => providerCapabilityEvidenceCommand(input, id));
}

function providerCapabilityEvidenceCommand(
  input: CloudControlSetupInput,
  capabilityId: string,
): RunbookCommand {
  const output = `$PROFILE_ROOT/provider-capability-${capabilityId}.json`;
  return {
    id: `provider-capability-${capabilityId}`,
    command: `${rootPrelude(input.outDir)}; deployment-control-plane provider-capability --deployment-id ${shellQuote(
      input.deploymentIds[0] || "<missing-deployment>",
    )} --record --provider-capability ${capabilityId}${inputFlags(capabilityId)} > "${output}"`,
    cwd: "profile-root",
    inputs: inputs(capabilityId),
    outputs: [output],
    mustPass: `${capabilityId} evidence is generated by provider-capability hook`,
  };
}

function inputFlags(capabilityId: string): string {
  const topology = ' --aws-topology-evidence "$PROFILE_ROOT/aws-topology-evidence.json"';
  if (capabilityId === "aws-ecr-control-plane-registry") {
    return [
      topology,
      ' --registry-profile "$PROFILE_ROOT/registry-profile.json"',
      ' --image-publication-evidence "$PROFILE_ROOT/image-publication.json"',
      ' --ecr-opentofu-plan "$PROFILE_ROOT/ecr-opentofu-plan.json"',
      ' --ecr-opentofu-apply "$PROFILE_ROOT/ecr-opentofu-apply.json"',
      ' --ecr-readonly-evidence "$PROFILE_ROOT/ecr-readonly-evidence.json"',
    ].join("");
  }
  if (capabilityId === "supabase-privatelink-prerequisite") {
    return [
      topology,
      ' --supabase-privatelink-opentofu-plan "$PROFILE_ROOT/supabase-privatelink-opentofu-plan.json"',
      ' --supabase-privatelink-opentofu-apply "$PROFILE_ROOT/supabase-privatelink-opentofu-apply.json"',
      ' --supabase-privatelink-readonly-evidence "$PROFILE_ROOT/supabase-privatelink-readonly-evidence.json"',
    ].join("");
  }
  if (capabilityId !== "aws-ec2-control-plane-host") return topology;
  return `${topology} --aws-ec2-profile "$PROFILE_ROOT/aws-ec2-profile.yaml"`;
}

function inputs(capabilityId: string): string[] {
  const values = [
    "$PROFILE_ROOT/provider-capabilities.json",
    "$PROFILE_ROOT/aws-topology-evidence.json",
  ];
  if (capabilityId === "aws-ecr-control-plane-registry") {
    return [
      ...values,
      "$PROFILE_ROOT/registry-profile.json",
      "$PROFILE_ROOT/image-publication.json",
      "$PROFILE_ROOT/ecr-opentofu-plan.json",
      "$PROFILE_ROOT/ecr-opentofu-apply.json",
      "$PROFILE_ROOT/ecr-readonly-evidence.json",
    ];
  }
  if (capabilityId === "supabase-privatelink-prerequisite") {
    return [
      ...values,
      "$PROFILE_ROOT/supabase-privatelink-opentofu-plan.json",
      "$PROFILE_ROOT/supabase-privatelink-opentofu-apply.json",
      "$PROFILE_ROOT/supabase-privatelink-readonly-evidence.json",
    ];
  }
  return capabilityId === "aws-ec2-control-plane-host"
    ? [...values, "$PROFILE_ROOT/aws-ec2-profile.yaml"]
    : values;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
