import type { ProviderCapabilityDeclaration } from "./cloud-control-setup-types";

export const CLOUD_PROVIDER_CAPABILITY_HOOK_EVIDENCE_SCHEMA =
  "cloud-provider-capability-hook-evidence@1";
export const CLOUD_PROVIDER_CAPABILITY_HOOK_EVIDENCE_SOURCE =
  "control-plane-provider-capability-hook";

export type CloudProviderCapabilityHookEvidenceLike = {
  schemaVersion?: unknown;
  source?: unknown;
  capabilityId?: unknown;
  phase?: unknown;
  declaration?: unknown;
  auditEvidence?: unknown;
};

export type ProviderCapabilityHookEvidenceValidationOptions = {
  allowedPhases?: readonly string[];
};

export function providerCapabilityHookEvidenceRecord(
  value: unknown,
): Record<string, unknown> | undefined {
  if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;
  return value as Record<string, unknown>;
}

export function hasProviderCapabilityHookEvidenceIdentity(value: Record<string, unknown>) {
  return (
    value.schemaVersion === CLOUD_PROVIDER_CAPABILITY_HOOK_EVIDENCE_SCHEMA &&
    value.source === CLOUD_PROVIDER_CAPABILITY_HOOK_EVIDENCE_SOURCE
  );
}

export function validateProviderCapabilityHookEvidenceShape(
  id: string,
  value: Record<string, unknown>,
  opts: ProviderCapabilityHookEvidenceValidationOptions = {},
): string[] {
  const errors: string[] = [];
  if (!hasProviderCapabilityHookEvidenceIdentity(value)) {
    errors.push(`${id}: provider-capability evidence must be generated by executable hook`);
  }
  if (String(value.capabilityId || "") !== id) {
    errors.push(`${id}: provider-capability evidence is attached to an unrelated capability`);
  }
  if (!hasHookAdapterEvidence(value)) {
    errors.push(`${id}: missing executable hook adapter evidence`);
  }
  if (opts.allowedPhases && !opts.allowedPhases.includes(String(value.phase || ""))) {
    errors.push(`${id}: provider-capability evidence has wrong hook phase`);
  }
  errors.push(...validateRedactedOutputEvidence(id, value));
  errors.push(...validateNoUnsafeEvidenceContent(id, value));
  return errors;
}

export function hookEvidenceDeclaration(
  value: Record<string, unknown>,
): ProviderCapabilityDeclaration | undefined {
  const declaration = value.declaration;
  if (!declaration || typeof declaration !== "object" || Array.isArray(declaration)) {
    return undefined;
  }
  return declaration as ProviderCapabilityDeclaration;
}

export function hookEvidenceRefs(value: Record<string, unknown>): string[] {
  const refs = value.auditEvidence;
  return Array.isArray(refs) ? refs.map(String).filter(Boolean) : [];
}

function hasHookAdapterEvidence(value: Record<string, unknown>): boolean {
  const hook = value.hook;
  return (
    !!hook &&
    typeof hook === "object" &&
    !Array.isArray(hook) &&
    typeof (hook as Record<string, unknown>).adapter === "string" &&
    String((hook as Record<string, unknown>).adapter).trim() !== ""
  );
}

function validateRedactedOutputEvidence(id: string, value: Record<string, unknown>): string[] {
  const output = value.output;
  if (!output || typeof output !== "object" || Array.isArray(output)) {
    return [`${id}: missing redacted hook output evidence`];
  }
  const record = output as Record<string, unknown>;
  const errors: string[] = [];
  if (record.classification !== "redact_before_display" || record.redacted !== true) {
    errors.push(`${id}: hook output must be redacted before evidence use`);
  }
  const summary = typeof record.summary === "string" ? record.summary.trim() : "";
  if (!summary || typeof record.fingerprint !== "string" || !record.fingerprint.trim()) {
    errors.push(`${id}: missing redacted hook output evidence`);
  }
  if (UNSAFE_EVIDENCE_PATTERN.test(summary)) {
    errors.push(`${id}: hook output summary contains unsafe secret-looking content`);
  }
  return errors;
}

function validateNoUnsafeEvidenceContent(id: string, value: Record<string, unknown>): string[] {
  const unsafePath = findUnsafeEvidencePath(value);
  return unsafePath
    ? [`${id}: hook evidence contains unsafe secret-looking content at ${unsafePath}`]
    : [];
}

function findUnsafeEvidencePath(value: unknown, path = "$"): string | undefined {
  if (typeof value === "string") {
    return UNSAFE_EVIDENCE_PATTERN.test(value) ? path : undefined;
  }
  if (!value || typeof value !== "object") return undefined;
  if (Array.isArray(value)) {
    for (let index = 0; index < value.length; index += 1) {
      const unsafe = findUnsafeEvidencePath(value[index], `${path}[${index}]`);
      if (unsafe) return unsafe;
    }
    return undefined;
  }
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    const childPath = evidencePath(path, key);
    if (UNSAFE_EVIDENCE_KEY_PATTERN.test(key) || UNSAFE_EVIDENCE_PATTERN.test(key)) {
      return childPath;
    }
    const unsafe = findUnsafeEvidencePath(child, childPath);
    if (unsafe) return unsafe;
  }
  return undefined;
}

function evidencePath(path: string, key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? `${path}.${key}` : `${path}[${JSON.stringify(key)}]`;
}

const UNSAFE_EVIDENCE_PATTERN =
  /authorization\s*[:=]|bearer\s+\S+|cookie\s*[:=]|passwd\s*[:=]|password\s*[:=]|private[_-]?key\s*[:=]|secret\s*[:=]|sk_(live|test)_\S+|token\s*[:=]|api[_-]?key\s*[:=]|-----begin/i;

const UNSAFE_EVIDENCE_KEY_PATTERN =
  /^(authorization|cookie|passwd|password|token|api[_-]?key|apiKey|client[_-]?secret|clientSecret|private[_-]?key|privateKey)$/i;
