import type { RunbookCommand } from "./cloud-control-runbook";
import { rootPrelude } from "./cloud-control-runbook-root";
import type { CloudControlSetupInput } from "./cloud-control-setup-types";

export function supabasePostgresEvidenceCommand(input: CloudControlSetupInput): RunbookCommand {
  return {
    id: "supabase-managed-postgres-evidence",
    command: `${rootPrelude(input.outDir)}; deploy --deployment ${shellQuote(
      input.deploymentIds[0] || "<missing-deployment>",
    )} --record --provider-capability supabase-managed-postgres --supabase-postgres-profile "$PROFILE_ROOT/supabase-postgres.profile.json" > "$PROFILE_ROOT/supabase-managed-postgres-evidence.json"`,
    cwd: "profile-root",
    inputs: [
      "$PROFILE_ROOT/config.yaml",
      "$PROFILE_ROOT/runtime-input.yaml",
      "$PROFILE_ROOT/credential-manifest.json",
      "$PROFILE_ROOT/credential-map.json",
      "$PROFILE_ROOT/auth-provider-profile.json",
      "$PROFILE_ROOT/residual-action-checklist.json",
      "$PROFILE_ROOT/commands.json",
      "$PROFILE_ROOT/supabase-postgres.profile.json",
    ],
    outputs: ["$PROFILE_ROOT/supabase-managed-postgres-evidence.json"],
    mustPass: "Supabase lifecycle evidence is generated by provider-capability hook",
  };
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
