import type { RunbookCommand } from "./cloud-control-runbook";
import { rootPrelude } from "./cloud-control-runbook-root";
import type { CloudControlSetupInput } from "./cloud-control-setup-types";
import { awsTopologyRequiredCapabilityIds } from "./cloud-control-aws-topology-capabilities";
import { EC2_ASG_IAC_PATHS } from "./cloud-control-aws-ec2-asg-iac-evidence";

export function providerCapabilityEvidenceCommands(input: CloudControlSetupInput) {
  return awsTopologyRequiredCapabilityIds(input.awsTopology)
    .filter((id) => id !== "supabase-managed-postgres")
    .map((id) => providerCapabilityEvidenceCommand(input, id));
}

function providerCapabilityEvidenceCommand(
  input: CloudControlSetupInput,
  capabilityId: string,
): RunbookCommand {
  const output = `$PROFILE_ROOT/provider-capability-${capabilityId}.json`;
  const base = `${rootPrelude(input.outDir)}; ${providerCommand(input, capabilityId)}`;
  if (requiresPreviewApply(input, capabilityId)) {
    const previewOutput = `$PROFILE_ROOT/provider-capability-${capabilityId}-preview.json`;
    const applyOutput = `$PROFILE_ROOT/provider-capability-${capabilityId}-apply.json`;
    return {
      id: `provider-capability-${capabilityId}`,
      command: [
        rootPrelude(input.outDir),
        `${providerCommand(input, capabilityId)} --preview${inputFlags(input, capabilityId)} > "${previewOutput}"`,
        `${providerCommand(input, capabilityId)} --provider-capability-phase apply${inputFlags(
          input,
          capabilityId,
        )} > "${applyOutput}"`,
        `${providerCommand(input, capabilityId)} --record${inputFlags(input, capabilityId)} > "${output}"`,
      ].join("; "),
      cwd: "profile-root",
      inputs: inputs(input, capabilityId),
      outputs: [previewOutput, applyOutput, output],
      mustPass: `${capabilityId} preview, apply, and evidence phases validate reviewed IaC artifacts`,
    };
  }
  return {
    id: `provider-capability-${capabilityId}`,
    command: `${base} --record${inputFlags(input, capabilityId)} > "${output}"`,
    cwd: "profile-root",
    inputs: inputs(input, capabilityId),
    outputs: [output],
    mustPass: `${capabilityId} evidence is generated by provider-capability hook`,
  };
}

function providerCommand(input: CloudControlSetupInput, capabilityId: string): string {
  return `deployment-control-plane provider-capability --deployment-id ${shellQuote(
    input.deploymentIds[0] || "<missing-deployment>",
  )} --provider-capability ${capabilityId}${modeFlag(input, capabilityId)}`;
}

function requiresPreviewApply(input: CloudControlSetupInput, capabilityId: string): boolean {
  return (
    capabilityId === "aws-ecr-control-plane-registry" ||
    (capabilityId === "aws-ec2-control-plane-host" && input.ec2HostMode === "repo-owned-asg")
  );
}

function inputFlags(input: CloudControlSetupInput, capabilityId: string): string {
  const topology = ' --aws-topology-evidence "$PROFILE_ROOT/aws-topology-evidence.json"';
  if (capabilityId === "aws-ecr-control-plane-registry") {
    return `${topology} --registry-profile "$PROFILE_ROOT/registry-profile.json" --image-publication-evidence "$PROFILE_ROOT/image-publication.json" --ecr-opentofu-plan "$PROFILE_ROOT/ecr-opentofu-plan.json" --ecr-opentofu-apply "$PROFILE_ROOT/ecr-opentofu-apply.json" --ecr-readonly-evidence "$PROFILE_ROOT/ecr-readonly-evidence.json"`;
  }
  if (capabilityId === "supabase-privatelink-prerequisite") {
    return `${topology} --supabase-privatelink-opentofu-plan "$PROFILE_ROOT/supabase-privatelink-opentofu-plan.json" --supabase-privatelink-opentofu-apply "$PROFILE_ROOT/supabase-privatelink-opentofu-apply.json" --supabase-privatelink-readonly-evidence "$PROFILE_ROOT/supabase-privatelink-readonly-evidence.json"`;
  }
  if (capabilityId !== "aws-ec2-control-plane-host") return topology;
  const asg =
    input.ec2HostMode === "repo-owned-asg"
      ? ` --ec2-asg-opentofu-plan "${EC2_ASG_IAC_PATHS.plan}" --ec2-asg-opentofu-apply "${EC2_ASG_IAC_PATHS.apply}" --ec2-asg-readonly-evidence "${EC2_ASG_IAC_PATHS.readOnly}"`
      : "";
  return `${topology} --aws-ec2-profile "$PROFILE_ROOT/aws-ec2-profile.yaml"${asg}`;
}

function inputs(input: CloudControlSetupInput, capabilityId: string): string[] {
  const values = [
    "$PROFILE_ROOT/provider-capabilities.json",
    "$PROFILE_ROOT/aws-topology-evidence.json",
  ];
  if (capabilityId === "aws-ecr-control-plane-registry") {
    return [
      ...values,
      "$PROFILE_ROOT/registry-profile.json",
      "$PROFILE_ROOT/image-publication.json",
      "$PROFILE_ROOT/ecr-opentofu-plan.json",
      "$PROFILE_ROOT/ecr-opentofu-apply.json",
      "$PROFILE_ROOT/ecr-readonly-evidence.json",
    ];
  }
  if (capabilityId === "supabase-privatelink-prerequisite") {
    return [
      ...values,
      "$PROFILE_ROOT/supabase-privatelink-opentofu-plan.json",
      "$PROFILE_ROOT/supabase-privatelink-opentofu-apply.json",
      "$PROFILE_ROOT/supabase-privatelink-readonly-evidence.json",
    ];
  }
  if (capabilityId !== "aws-ec2-control-plane-host") return values;
  const ec2 = [...values, "$PROFILE_ROOT/aws-ec2-profile.yaml"];
  if (input.ec2HostMode !== "repo-owned-asg") return ec2;
  return [...ec2, EC2_ASG_IAC_PATHS.plan, EC2_ASG_IAC_PATHS.apply, EC2_ASG_IAC_PATHS.readOnly];
}

function modeFlag(input: CloudControlSetupInput, capabilityId: string): string {
  if (capabilityId !== "aws-ec2-control-plane-host") return "";
  return ` --ec2-host-mode ${input.ec2HostMode || "external-reviewed-host"}`;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
