import {
  type ControlPlaneImagePublicationEvidence,
  verifiedControlPlaneImageDigestContract,
} from "./control-plane-image-publication";
import { validateControlPlaneRegistryProfile } from "./control-plane-registry-profile";

export function validateControlPlaneImagePublicationEvidence(
  evidence: ControlPlaneImagePublicationEvidence | undefined,
  expectedImageRef: string,
  expectedBuildIdentity?: string,
  opts: {
    requireGeneratedEvidence?: boolean;
    requireRegistryProfile?: boolean;
    expectedRuntimeHostProfile?: string;
    expectedRegistryAccountId?: string;
    expectedRegistryRegion?: string;
  } = {},
): string[] {
  const errors: string[] = [];
  if (!evidence) return ["control-plane image requires verified publication evidence"];
  try {
    verifiedControlPlaneImageDigestContract(evidence);
  } catch (error) {
    errors.push(error instanceof Error ? error.message : String(error));
  }
  if (evidence.image !== expectedImageRef) {
    errors.push("control-plane image publication evidence does not match requested image");
  }
  if (expectedBuildIdentity && evidence.imageBuildIdentity !== expectedBuildIdentity) {
    errors.push("control-plane image publication evidence does not match expected build identity");
  }
  if (opts.requireGeneratedEvidence && evidence.evidenceSource !== "generated-command") {
    errors.push("control-plane image publication evidence must be generated by image-publication");
  }
  if (opts.requireRegistryProfile && !evidence.registryProfile) {
    errors.push("control-plane image publication evidence requires registry profile evidence");
  }
  if (evidence.registryProfile) {
    errors.push(
      ...validateControlPlaneRegistryProfile(evidence.registryProfile, {
        expectedImageRef,
        expectedDigest: evidence.digest,
        expectedHostProfile: opts.expectedRuntimeHostProfile,
        expectedAccountId: opts.expectedRegistryAccountId,
        expectedRegion: opts.expectedRegistryRegion,
      }),
    );
  }
  return errors;
}
