#!/usr/bin/env zx-wrapper

import { DEPLOYMENT_CQUERY_ATTRS } from "../../../deployments/deployment-query-attrs";

export const attrList = Array.from(
  new Set([
    "name",
    "rule_type",
    "buck.type",
    "provider",
    "component",
    "component_kind",
    "publisher",
    "provisioner",
    "protection_class",
    "app_name",
    "container_port",
    "health_path",
    "target_group",
    "module",
    "build_py_deps",
    "srcs",
    "buck.srcs",
    "nix_srcs",
    "deps",
    "link_deps",
    "header_deps",
    "link_closure",
    "link_closure_overrides",
    "link_mode",
    "nixpkgs_profile",
    "nixpkg_pins",
    "cargo_manifest",
    "cargo_lock",
    "crate",
    "features",
    "default_features",
    "profile",
    "target",
    "local_patch_dirs",
    "buck.link_mode",
    "buck.link_kind",
    "buck.deps",
    "labels",
    "buck.labels",
    "args",
    "env",
    "cmd",
    "out",
    "main",
    "main_class",
    "includes",
    "defines",
    "cflags",
    "ldflags",
    "module_kind",
    "source_roots",
    "artifact_mapping_policy",
    "watch_hints",
    ...DEPLOYMENT_CQUERY_ATTRS,
  ]),
);
